const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);const report={checks:[],errors:[]};const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){const c=await b.newContext({viewport:{width,height:1000},hasTouch:width===390,isMobile:width===390});await c.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:4176'&&r.request().method()==='GET'?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:4176');await A(p,'new-book').click();await p.locator('#new-title').fill('纸面直接输入验证');await A(p,'create-book').click();await p.locator('#canvas-page').waitFor();
const clickBlank=async(x,y)=>{const r=await p.locator('#canvas-page').boundingBox();if(width===390)await p.touchscreen.tap(r.x+r.width*x,r.y+r.height*y);else await p.mouse.click(r.x+r.width*x,r.y+r.height*y);};
await clickBlank(.23,.3);const input=p.locator('.inline-text-input');await input.waitFor();assert.equal(await p.locator('#dialog').evaluate(n=>n.open),false);assert.equal(await p.evaluate(()=>currentPage().elements.length),0);await input.fill('今天的光，\n刚刚好。');await p.keyboard.press('End');await p.keyboard.press('Backspace');assert.equal(await p.evaluate(()=>currentPage().elements.length),1);const typed=await input.inputValue();assert.equal(typed,'今天的光，\n刚刚好');const pos=await p.evaluate(()=>({x:currentPage().elements[0].x,y:currentPage().elements[0].y}));assert.ok(Math.abs(pos.x-23)<1&&Math.abs(pos.y-30)<1);assert.equal(await input.evaluate(el=>getComputedStyle(el).outlineStyle),'none');await p.screenshot({path:path.join(out,`typing-${width}.png`)});await p.keyboard.press('Escape');assert.equal(await input.count(),0);assert.equal(await p.evaluate(()=>currentPage().elements[0].text),typed);
await A(p,'undo').click();assert.equal(await p.evaluate(()=>currentPage().elements.length),0);await A(p,'redo').click();assert.equal(await p.evaluate(()=>currentPage().elements.length),1);const id=await p.evaluate(()=>currentPage().elements[0].id);await p.locator(`#canvas-page [data-element="${id}"] .text-content`).dblclick();await input.fill('在原地改一改');await input.evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.value='在原地改一改，中文输入';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文输入'}));});assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'在原地改一改，中文输入');await p.keyboard.press('Escape');assert.deepEqual(await p.evaluate(()=>({x:currentPage().elements[0].x,y:currentPage().elements[0].y})),pos);
// A text drag still moves the element; dragging blank paper does not start input.
const box=await p.locator(`#canvas-page [data-element="${id}"]`).boundingBox();await p.mouse.move(box.x+10,box.y+10);await p.mouse.down();await p.mouse.move(box.x+40,box.y+30,{steps:6});await p.mouse.up();assert.equal(await input.count(),0);assert.ok(await p.evaluate(()=>currentPage().elements[0].x)>pos.x);const rect=await p.locator('#canvas-page').boundingBox();await p.mouse.move(rect.x+rect.width*.1,rect.y+rect.height*.8);await p.mouse.down();await p.mouse.move(rect.x+rect.width*.3,rect.y+rect.height*.8,{steps:5});await p.mouse.up();assert.equal(await input.count(),0);
await clickBlank(.1,.75);await input.waitFor();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>currentPage().elements.length),1);
// Click away commits before changing page/mode; failed persistence keeps editing available.
await p.locator(`#canvas-page [data-element="${id}"] .text-content`).dblclick();await input.fill('保存失败也保留输入');await p.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('test quota','QuotaExceededError')}});await A(p,'mode','read').click();await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='保存失败，请重试');assert.equal(await p.locator('#canvas-page').count(),1);assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'保存失败也保留输入');await p.evaluate(()=>IDBObjectStore.prototype.put=window.originalPut);await A(p,'mode','read').click();await p.locator('.read-mode').waitFor();const leaf=await p.locator('.reader-spread').boundingBox();await p.mouse.click(leaf.x+leaf.width*.6,leaf.y+leaf.height*.8);assert.equal(await input.count(),0);const bookId=await p.evaluate(()=>currentBook().id);await p.reload();await p.locator('[data-action="nav"][data-view="shelf"]').click();await p.locator(`[data-action="open-book"][data-id="${bookId}"]`).click();await A(p,'mode','edit').click();assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'保存失败也保留输入');
await A(p,'drawer','text').click();await A(p,'add-text').click();await input.fill('工具栏也可直接输入');await A(p,'page-add').click();assert.equal(await p.evaluate(()=>currentBook().pages[0].elements.length),2);assert.equal(await p.evaluate(()=>currentPage().elements.length),0);assert.equal(await input.count(),0);report.checks.push({width,status:'PASS',checks:'tap/click positioning; multiline; Backspace; IME events; grouped undo/redo; inline re-edit; text drag; blank drag; empty input; save failure/retry; readonly; reload; toolbar and page switch'});console.log(width+' PASS');await c.close();}}finally{await b.close();}assert.deepEqual(report.errors,[]);})().catch(e=>{report.failure=e.stack;process.exitCode=1;console.error(e);}).finally(()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)));
