const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);let server,browser;const results=[];
(async()=>{const {createApp}=await import(path.join(root,'dist/server/app.js'));const {app}=await createApp({runtime:fs.mkdtempSync(path.join(os.tmpdir(),'shiye-manual-')),staticRoot:path.join(root,'shiye-editorial-prototype')});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [1440,390,320]){const c=await browser.newContext({viewport:{width,height:950},isMobile:width<500,hasTouch:width<500}),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);const A=a=>p.locator(`[data-action="${a}"]`).first();await c.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());try{
await p.goto(base,{waitUntil:'networkidle'});await A('home-create-sticker').click();await p.locator('[data-shelf-create-sticker]').click();await A('crop-example').click();await A('edge-disable').click();await p.locator('.manual-crop-panel').waitFor();
for(const [x,y] of [[.2,.2],[.8,.2],[.8,.8],[.2,.8]]){const stage=p.locator('#crop-stage'),r=await stage.boundingBox();await stage.click({position:{x:r.width*x,y:r.height*y}});}await A('finish-scissors').click();await p.locator('.crop-vertex').first().waitFor();
const stage=await p.locator('#crop-stage').boundingBox(),panel=await p.locator('.manual-crop-panel').boundingBox(),layout=await p.locator('.workshop-layout').boundingBox();assert.ok(panel.y>=stage.y+stage.height);assert.ok(stage.width>=layout.width*.98);assert.equal(await p.locator('.workshop-aside').count(),0);assert.equal(await p.locator('.manual-selection-row [data-action="select-crop"]').count(),0);assert.deepEqual(await p.locator('.manual-crop-tools [data-action]').evaluateAll(es=>es.map(e=>e.dataset.action)),['undo-crop','redo-crop','clear-crops']);
const before=await p.evaluate(()=>workshop.crops[0].points[0].x);await p.locator('.crop-vertex').first().focus();await p.keyboard.press('ArrowRight');assert.ok(await p.evaluate(()=>workshop.crops[0].points[0].x)>before);await A('undo-crop').click();assert.equal(await p.evaluate(()=>workshop.crops[0].points[0].x),before);await A('redo-crop').click();assert.ok(await p.evaluate(()=>workshop.crops[0].points[0].x)>before);await A('clear-crops').click();assert.equal(await p.evaluate(()=>workshop.crops.length),0);await A('undo-crop').click();assert.equal(await p.evaluate(()=>workshop.crops.length),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:path.join(out,'manual-'+width+'.png'),fullPage:true});
await A('generate').click();await p.locator('#sticker-preview').waitFor();await A('save-stickers').click();await p.locator('.collection-header').waitFor();await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');assert.equal(await p.evaluate(()=>state.assets.length),1);assert.deepEqual(errors,[]);results.push({width,status:'PASS'});
}catch(e){results.push({width,status:'FAIL',error:e.stack});await p.screenshot({path:path.join(out,'failure-'+width+'.png'),fullPage:true});}finally{await c.close();}}console.log(JSON.stringify(results));})().catch(e=>{results.push({fatal:e.stack});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));if(results.some(r=>r.status==='FAIL'||r.fatal))process.exitCode=1;});
