const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'sync-browser-results.json'),checks=[],errors=[];let browser,server,p;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js')),{default:sharp}=await import(path.join(root,'node_modules/sharp/lib/index.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-autosync-ui-')),batch=generateInvites(3),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'test',secretKey:'test',cutout:false,naming:false},path.join(dir,'receipt'));
 for(const [i,name] of ['sync-user-a','sync-user-b'].entries()){const grant=await access.verify(batch.codes[i],name,'local');await admin.register(grant.token,{username:name,password:'test-password-123'});}
 const runtime=path.join(dir,'runtime'),{app}=await createApp({runtime,staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});
 async function context(width=1440){const c=await browser.newContext({viewport:{width,height:950}});await c.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());return c;}
 async function open(c){const page=await c.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>typeof savedWorkspace!=='undefined'&&savedWorkspace);return page;}
 async function login(c,name){await c.request.get(base+'/api/access/session');const r=await c.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:name,password:'test-password-123'}});assert.equal(r.status(),200);}
 async function ready(page){await page.waitForFunction(()=>typeof workSync!=='undefined'&&workSync&&!workSync.running&&workSync.label==='已同步到当前服务',{},{timeout:20000});}
 async function reconnect(page){await page.waitForFunction(()=>typeof workSync!=='undefined'&&workSync);await page.evaluate(()=>{workSync.status('等待同步');window.dispatchEvent(new Event('online'));});}
 async function remote(c){return (await(await c.request.get(base+'/api/works/workspace')).json()).content;}
 const a=await context(),b=await context();p=await open(a);
 assert.ok((await p.locator('body').innerText()).includes('开始创作'));assert.equal(await p.locator('.vite-error-overlay,[data-nextjs-dialog]').count(),0);
 await p.screenshot({path:path.join(__dirname,'entry.png')});checks.push('Entry renders without errors');
 // Real account-password UI, with a visitor workspace left explicitly outside the account.
 await p.locator('[data-action="access-open"]').click();await p.locator('[data-value="account"]').click();await p.locator('#account-username').fill('sync-user-a');await p.locator('#account-password').fill('test-password-123');await p.locator('#account-form button').click();await p.locator('#import-guest').waitFor();assert.equal((await remote(a)).books.length,0);await p.locator('[data-action="close-dialog"]').first().click();await ready(p);
 assert.ok(await p.evaluate(async()=>!!(await localRecord('workspace'))));checks.push('Guest import is optional; declining does not sync guest works');
 const png=await sharp({create:{width:96,height:72,channels:4,background:{r:120,g:180,b:130,alpha:.5}}}).png().toBuffer();
 const ids=await p.evaluate(async image=>{
  const books=seed().books,book=books[0];book.id='sync-book';book.title='自动保存测试';book.editorLayout='spread';book.stickerPlacement='spread';
  book.pages=[{id:'left',paper:'plain',spreadKey:'pair',spreadSide:'left',paperSpread:{paper:'texture-butterfly-botanical',side:'left'},elements:[{id:'text',type:'text',text:'原位输入，保留竖排字体',font:'fangsong',direction:'vertical',size:23,color:'#556644',x:12,y:5,w:40,h:65,rotation:2},{id:'sticker',type:'sticker',assetId:'placed',x:80,y:40,w:40,rotation:-8,flip:true,spreadWith:'right'}]},{id:'right',paper:'plain',spreadKey:'pair',spreadSide:'right',paperSpread:{paper:'texture-butterfly-botanical',side:'right'},elements:[]}];
  state.books=books;const blob=await(await fetch('data:image/png;base64,'+image)).blob();pendingAssetBlobs.set('blob:test',blob);
  state.assets=[{id:'unplaced',name:'未使用素材',category:'照片',favorite:true,pinned:true,createdAt:Date.now(),blobKey:'blob:test',borderBaked:true},{...builtin[3],id:'example-copy',name:'官方插画副本'}];
  state.archivedAssets=[{id:'placed',name:'书中保留贴纸',category:'照片',blobKey:'blob:test',borderBaked:true}];dirty();await saveNow();renderShelf();return {book:book.id};
 },png.toString('base64'));
 await ready(p);let r=await remote(a);assert.equal(r.books.length,3);assert.equal(r.assets.length,2);assert.equal(r.archivedAssets.length,1);assert.ok(r.assets[0].image);assert.ok(!JSON.stringify(r).includes('data:image'));checks.push('Existing account works, independent PNG and built-in stickers automatically sync');
 await login(b,'sync-user-a');const q=await open(b);await ready(q);assert.equal(await q.evaluate(()=>state.books.length),3);assert.equal(await q.evaluate(()=>state.assets.find(a=>a.id==='unplaced').favorite),true);assert.equal(await q.evaluate(()=>state.books.find(b=>b.id==='sync-book').pages[0].elements[0].font),'fangsong');assert.ok(await q.evaluate(()=>asset('placed').src.startsWith('blob:')));checks.push('Independent browser automatically restores editable spread, fonts, archived and unused stickers');
 await q.evaluate(()=>{currentView='collection';render();});await q.locator('[data-asset-id="unplaced"] img').waitFor();assert.ok(await q.locator('[data-asset-id="unplaced"] img').evaluate(i=>i.complete&&i.naturalWidth===96));await q.screenshot({path:path.join(__dirname,'restored-library.png'),fullPage:true});
 // Automatic upload leaves the live inline textarea and caret in place.
 await p.evaluate(()=>openBook('sync-book',true));await p.locator('#canvas-page [data-element="text"]').dblclick();await p.locator('[data-element-command="edit"]').click();await p.locator('.inline-text-input').fill('双页纸面直接输入');await p.waitForFunction(()=>saveStatus==='已保存到本机');await ready(p);assert.equal(await p.locator('.inline-text-input').inputValue(),'双页纸面直接输入');assert.ok(await p.locator('.inline-text-input').evaluate(e=>document.activeElement===e));
 await p.locator('.inline-text-input').press('Escape');await p.locator('[data-action="shelve"]').first().click();await p.locator('[data-action="new-book"]').first().waitFor();await ready(p);await reconnect(q);await ready(q);assert.equal(await q.evaluate(()=>state.books.find(b=>b.id==='sync-book').pages[0].elements[0].text),'双页纸面直接输入');checks.push('Inline typing keeps textarea focus during automatic save and restores structured text');
 await a.route('**/api/access/session',route=>route.abort());assert.equal(await p.evaluate(async()=>{const before=currentIdentity.accountId;await refreshIdentity();return currentIdentity?.accountId===before;}),true);await a.unroute('**/api/access/session');checks.push('Temporary identity endpoint outage does not log out an already verified account');
 // Network failure leaves local edits intact across a page reload, then retries on online.
 await a.route('**/api/works/**',route=>route.abort());await p.evaluate(async()=>{state.books.find(b=>b.id==='sync-book').title='离线改名';dirty();await saveNow();});await p.waitForFunction(()=>workSync.error);
 await p.reload();await p.waitForFunction(()=>state?.books?.some(b=>b.title==='离线改名'));await a.unroute('**/api/works/**');await reconnect(p);await ready(p);assert.ok((await remote(a)).books.some(b=>b.title==='离线改名'));checks.push('Offline edit survives reload and reconnect submits automatically');
 await reconnect(q);await ready(q);assert.ok(await q.evaluate(()=>state.books.some(b=>b.title==='离线改名')));
 // Commit succeeded but the acknowledgement was lost: replay exact persisted operation.
 let lost=false;await a.route('**/api/works/workspace',async route=>{if(route.request().method()==='PUT'&&!lost){lost=true;await route.fetch();await route.abort();}else await route.continue();});
 await p.evaluate(async()=>{state.books.find(b=>b.id==='sync-book').title='回包丢失也不重复';dirty();await saveNow();});await p.waitForFunction(async()=>!!(await localRecord(workspaceKey+':sync-v1'))?.pending);await pause(600);await p.reload();await a.unroute('**/api/works/workspace');await p.waitForFunction(()=>workSync);await reconnect(p);await ready(p);assert.equal((await remote(a)).books.filter(b=>b.id==='sync-book').length,1);checks.push('Lost acknowledgement replays persisted operation without duplicate works');
 await reconnect(q);await ready(q);
 // Both browsers modify the same book while separated. Preserve both versions.
 await b.route('**/api/works/**',route=>route.abort());await q.evaluate(async()=>{state.books.find(b=>b.id==='sync-book').title='乙浏览器版本';dirty();await saveNow();});
 await p.evaluate(async()=>{state.books.find(b=>b.id==='sync-book').title='甲浏览器版本';dirty();await saveNow();});await ready(p);
 await b.unroute('**/api/works/**');await reconnect(q);await ready(q);r=await remote(a);assert.ok(r.books.some(b=>b.title==='甲浏览器版本'));assert.ok(r.books.some(b=>b.title==='乙浏览器版本（冲突副本）'));checks.push('Concurrent edits keep server version and a conflict copy');
 await reconnect(p);await ready(p);
 await p.evaluate(async()=>{state.books=state.books.filter(b=>b.id!=='sync-book');state.assets.find(a=>a.id==='unplaced').name='改名收藏';state.assets.find(a=>a.id==='unplaced').pinned=false;state.assets.find(a=>a.id==='unplaced').favorite=false;dirty();await saveNow();});await ready(p);await reconnect(q);await ready(q);assert.ok(!await q.evaluate(()=>state.books.some(b=>b.id==='sync-book')));assert.equal(await q.evaluate(()=>state.assets.find(a=>a.id==='unplaced').name),'改名收藏');checks.push('Book deletion, sticker rename, pin and favorite updates propagate');
 // An old queued write must never follow a changed cookie into another account.
 let release,intercepted=false;await a.route('**/api/works/workspace',async route=>{if(route.request().method()==='PUT'&&!intercepted){intercepted=true;await new Promise(r=>release=r);}await route.continue();});
 await p.evaluate(async()=>{state.assets.find(a=>a.id==='unplaced').name='原账号待传素材';dirty();await saveNow();});for(let i=0;i<50&&!intercepted;i++)await pause(100);assert.ok(intercepted);await login(a,'sync-user-b');release();await p.waitForFunction(()=>workSync.error?.includes('账号已切换'));assert.equal((await remote(a)).assets.length,0);
 await a.unroute('**/api/works/workspace');await p.reload();await p.waitForFunction(()=>state&&currentIdentity?.username==='sync-user-b');if(await p.locator('#import-guest').count())await p.locator('[data-action="close-dialog"]').first().click();await ready(p);assert.equal(await p.evaluate(()=>state.assets.length),0);
 await login(a,'sync-user-a');await p.reload();await ready(p);assert.ok((await remote(a)).assets.some(a=>a.name==='原账号待传素材'));checks.push('Account header blocks delayed old-account write; pending work resumes only on original login');
 // Imported guest works merge with existing account contents instead of replacing them.
 const c=await context(390),g=await open(c);await g.evaluate(async image=>{state.books=[{id:'guest-book',title:'明确归入的访客手账',updated:Date.now(),cover:'cream',page:0,pages:[blankPage()]}];state.assets=[{id:'guest-sticker',name:'归入的素材',category:'照片',src:'data:image/png;base64,'+image}];await saveNow();},png.toString('base64'));await login(c,'sync-user-a');await g.reload();await g.locator('#import-guest').waitFor();assert.ok(!(await remote(c)).books.some(b=>b.id==='guest-book'));await Promise.all([g.waitForEvent('load'),g.locator('#import-guest').click()]);await ready(g);r=await remote(c);assert.ok(r.books.some(b=>b.id==='guest-book'));assert.ok(r.books.some(b=>b.title==='乙浏览器版本（冲突副本）'));assert.ok(r.assets.some(a=>a.id==='guest-sticker'));checks.push('Explicit guest import merges with existing server account and carries images');
 await g.evaluate(()=>{currentView='shelf';render();});await g.screenshot({path:path.join(__dirname,'mobile-shelf.png'),fullPage:true});assert.ok(await g.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 // Builtin sample structures were carried through the same strict server schema.
 assert.deepEqual(errors,[]);checks.push('Desktop and mobile rendering have no uncaught JavaScript errors');
 console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);console.error(await p?.evaluate(()=>({sync:typeof workSync!=='undefined'&&workSync?{label:workSync.label,error:workSync.error}:null})).catch(()=>null));checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png'),fullPage:true,timeout:3000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(out,JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
