const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();

 const sharp=require(path.join(root,'node_modules/sharp'));
 await p.evaluate(async()=>{const b=currentBook();b.pages[0].elements=samplePage('lake').elements;b.pages[1].elements=samplePage('lake').elements;b.pages[2].elements=samplePage('coffee').elements;b.pages[3].elements=samplePage('forest').elements;b.pages[2].paper='texture-0444';b.pages[3].paper='texture-0487';b.pages[2].elements.push({id:'spanning-flower',type:'sticker',assetId:'flower',spreadWith:'p3',x:88,y:45,w:30,rotation:0});dirty();await saveNow();editing=false;renderEditor();await readyTurnImages($('.reader-spread'));});
 await p.evaluate(()=>{window.oldLeaves=$$(':scope>.reader-leaf',$('.reader-spread'));window.realGet=ShiyePageTextures.get;window.waitGate=new Promise(r=>window.releaseGate=r);ShiyePageTextures.get=async(...args)=>{await waitGate;return realGet(...args);};window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,0);});
 assert.equal(await p.evaluate(()=>oldLeaves.every(el=>el.isConnected)),true);assert.equal(await p.locator('.reader-turn-layer').evaluate(e=>getComputedStyle(e).visibility),'hidden');
 await p.evaluate(()=>{releaseGate();ShiyePageTextures.get=realGet;});await p.waitForFunction(()=>testTurn.ready);await p.evaluate(()=>{drawSideTurn(testTurn,.7);cancelReaderTurn();});assert.equal(await p.evaluate(()=>oldLeaves.every(el=>el.isConnected)),true);checks.push('Preparation retains original leaves; cancelling restores the same nodes');
 const shot=async name=>{const buf=await p.locator('.reader-spread').screenshot();fs.writeFileSync(path.join(__dirname,name+'.png'),buf);return buf;};
 async function pixelDiff(a,b){const meta=await sharp(a).metadata(),aa=await sharp(a).removeAlpha().raw().toBuffer(),bb=await sharp(b).removeAlpha().raw().toBuffer();assert.equal(aa.length,bb.length);let sum=0,hinge=0,count=0;for(let i=0;i<aa.length;i++){const d=Math.abs(aa[i]-bb[i]);sum+=d;const x=Math.floor(i/3)%meta.width;if(Math.abs(x-meta.width/2)<12){hinge+=d;count++;}}return {page:sum/aa.length,hinge:hinge/count};}
 async function endpoint(direction,target,name){
  await p.evaluate(direction=>{window.readerRoot=$('.reader-spread');window.testTurn=prepareReaderTurn(direction);drawSideTurn(testTurn,0);},direction);await p.waitForFunction(()=>testTurn.ready);
  await p.evaluate(()=>{drawSideTurn(testTurn,.6);});await shot(name+'-turn');
  await p.evaluate(()=>{drawSideTurn(testTurn,1);window.landedLeaves=[$('.demo-fold-back-content>.reader-leaf',testTurn.back),testTurn.underPage];window.landedImages=landedLeaves.flatMap(el=>$$('.element img',el));});const end=await shot(name+'-before-handoff');
  await p.evaluate(()=>finishReaderTurn(testTurn,true));const final=await shot(name+'-after-handoff');
  const result=await p.evaluate(()=>({page:currentBook().page,rootSame:readerRoot===$('.reader-spread'),leavesSame:landedLeaves.every(el=>el.parentElement===readerRoot),imagesSame:$$('.reader-spread .element img').every(img=>landedImages.includes(img)&&img.complete&&img.naturalWidth>0),imageCount:$$('.reader-spread .element img').length,active:$('#canvas-page').dataset.readerPage,thumb:$('.page-thumb.active').dataset.value,meta:$('.workspace-meta>span').textContent}));
  assert.equal(result.page,target);assert.equal(result.rootSame,true);assert.equal(result.leavesSame,true);assert.equal(result.imagesSame,true);assert.equal(result.active,String(target));assert.equal(result.thumb,String(target));assert.equal(await p.locator('.reader-turn-layer').count(),0);
  const diff=await pixelDiff(end,final);assert.ok(diff.page<2,JSON.stringify(diff));assert.ok(diff.hinge<2,JSON.stringify(diff));checks.push({check:name,result,diff});
 }
 await endpoint(1,2,'forward');assert.equal(await p.locator('.reader-spread [data-element="spanning-flower"] img').count(),2);assert.equal(await p.locator('.reader-spread>.texture-0444').count(),1);assert.equal(await p.locator('.reader-spread>.texture-0487').count(),1);
 await p.evaluate(async()=>{currentBook().pages[2].paperSpread={paper:'texture-star-heart-grid',side:'left'};currentBook().pages[3].paperSpread={paper:'texture-star-heart-grid',side:'right'};dirty();await saveNow();renderEditor();});await endpoint(-1,0,'reverse');await endpoint(1,2,'changed-paper');assert.equal(await p.locator('.reader-spread .spread-paper.texture-star-heart-grid').count(),2);
 // Exercise natural completion and both cancellation paths with the actual animation scheduler.
 await p.locator('[data-action="page-prev"]').click();await p.waitForFunction(()=>!readerTurn&&currentBook().page===0);
 await p.evaluate(()=>{window.oldLeaves=$$(':scope>.reader-leaf',$('.reader-spread'));window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.35);});await p.waitForFunction(()=>testTurn.ready);await p.evaluate(()=>animateReaderTurn(testTurn,false));await p.waitForFunction(()=>!readerTurn);assert.equal(await p.evaluate(()=>currentBook().page===0&&oldLeaves.every(el=>el.isConnected)),true);
 await p.evaluate(()=>{window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.2);cancelReaderTurn();});await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>oldLeaves.every(el=>el.isConnected)),true);checks.push('Natural previous turn, animated snap-back and cancellation during preparation retain correct pages');
 // In-place reader keeps its original pointer and keyboard bindings.
 const box=await p.locator('.reader-spread').boundingBox();await p.mouse.move(box.x+box.width*.8,box.y+box.height*.6);await p.mouse.down();await p.mouse.move(box.x+box.width*.25,box.y+box.height*.6,{steps:10});await p.mouse.up();await p.waitForFunction(()=>!readerTurn&&currentBook().page===2);await p.keyboard.press('ArrowLeft');await p.waitForFunction(()=>!readerTurn&&currentBook().page===0);checks.push('Mouse swipe and keyboard work after successive in-place landings');
 await p.locator('[data-action="page-prev"]').click();assert.equal(await p.evaluate(()=>readerCover),'front');await p.locator('[data-action="reader-open"]').click();await p.waitForFunction(()=>!readerCover);checks.push('Cover navigation still works');
 await p.locator('[data-action="mode"][data-value="edit"]').click();await p.waitForFunction(()=>editing);assert.equal(await p.locator('#canvas-page .element').count()>0,true);checks.push('Switching from reading to editing retains editable source elements');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
