const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),sharp=require('sharp');const {pathToFileURL}=require('url');const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);let browser,server;const report={checks:[],errors:[],external:[],providerCalls:[]};
(async()=>{const {createApp}=await import(pathToFileURL(path.join(root,'dist/server/app.js'))),{fixture,mask}=await import(pathToFileURL(path.join(root,'dist/server/images.js')));const source=await fixture();
const {app}=await createApp({runtime:fs.mkdtempSync(path.join(os.tmpdir(),'shiye-prebox-')),staticRoot:path.join(root,'shiye-editorial-prototype'),mode:'live',ttl:600000,live:{maxCalls:null,approvedUntil:null,provider:{segment:async(source,box)=>{const m=await sharp(source).metadata();report.providerCalls.push({box,width:m.width,height:m.height});return {requestId:String(report.providerCalls.length),mask:await mask(0)};}}}});
server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [1440,390,320]){const ctx=await browser.newContext({viewport:{width,height:900},isMobile:width<=390,hasTouch:width<=390,reducedMotion:'reduce'}),p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>report.errors.push(e.message));const posts=[];await ctx.route('**/*',r=>{const req=r.request(),u=new URL(req.url());if(u.origin!==base){report.external.push(u.origin);return r.abort();}if(req.method()==='POST')posts.push({path:u.pathname,body:u.pathname.startsWith('/api/segmentation/')?req.postDataJSON():undefined});return r.continue();});const A=a=>p.locator(`[data-action="${a}"]`).first();
try{await p.goto(base,{waitUntil:'networkidle'});assert.ok((await p.locator('body').innerText()).length>100);await A('home-create-sticker').click();await A('seg-open').click();await p.locator('#seg-photo').waitFor({state:'attached'});assert.equal(await p.locator('#seg-consent').count(),0);assert.equal(await A('seg-upload').isDisabled(),true);assert.equal(await A('seg-pick-box').isDisabled(),true);
await p.locator('#seg-photo').setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:source});await p.waitForFunction(()=>document.querySelector('#seg-source')?.naturalWidth===600&&!document.querySelector('[data-action="seg-upload"]').disabled);assert.equal(posts.length,0);assert.equal(await p.locator('.page-heading,.seg-notice,.workshop-aside').count(),0);assert.equal(await p.locator('.seg-help').getAttribute('open'),null);assert.equal((await p.locator('body').innerText()).includes('最大 10 MB'),false);await p.screenshot({path:path.join(out,'preview-'+width+'.png'),fullPage:true});await A('seg-pick-box').click();await A('seg-upload').click();await p.locator('.seg-error').waitFor();assert.equal(posts.length,0);
const svg=p.locator('#seg-prompts');await svg.scrollIntoViewIfNeeded();const r=await svg.boundingBox();
if(width<=390){const cdp=await ctx.newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width*.1,y:r.y+r.height*.15}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+r.width*.6,y:r.y+r.height*.8}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
else{await p.mouse.move(r.x+r.width*.1,r.y+r.height*.15);await p.mouse.down();await p.mouse.move(r.x+r.width*.6,r.y+r.height*.8,{steps:8});await p.mouse.up();}
await p.screenshot({path:path.join(out,'box-'+width+'.png'),fullPage:true});assert.equal(posts.length,0);const before=report.providerCalls.length;await A('seg-upload').click();await p.waitForFunction(()=>document.querySelectorAll('.seg-candidate').length===1&&!document.querySelector('[data-action="seg-confirm"]').disabled);assert.equal(report.providerCalls.length,before+1);assert.deepEqual(posts.map(x=>x.path),['/api/uploads/photo','/api/segmentation/refine']);const b=posts[1].body.box;assert.ok(Math.abs(b.x-.1)<.01&&Math.abs(b.y-.15)<.01&&Math.abs(b.width-.5)<.01&&Math.abs(b.height-.65)<.01);assert.equal(await p.locator('[data-action="seg-target"],[data-action="seg-refine"],#seg-prompts').count(),0);assert.equal(await A('seg-retouch-open').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);assert.equal(await p.locator('#seg-source,[data-action="seg-new"],.seg-candidates,.workshop-aside').count(),0);await p.locator('#seg-cutout').waitFor();const left=await A('seg-retouch-open').boundingBox(),right=await A('seg-confirm').boundingBox();assert.ok(left.x+left.width<=right.x&&Math.abs(left.y-right.y)<2);assert.ok(right.y+right.height<900-64);await p.screenshot({path:path.join(out,'result-'+width+'.png'),fullPage:true});
await A('seg-retouch-open').click();await p.locator('#seg-retouch-canvas').waitFor();await A('seg-retouch-cancel').click();assert.equal(report.providerCalls.length,before+1);
await A('workshop-back').click();await p.locator('#seg-photo').setInputFiles({name:'portrait.jpg',mimeType:'image/jpeg',buffer:await sharp(source).jpeg().withMetadata({orientation:6}).toBuffer()});await p.waitForFunction(()=>document.querySelector('#seg-source')?.naturalWidth===400&&!document.querySelector('[data-action="seg-upload"]').disabled);assert.equal(await p.locator('#seg-prompts').count(),0);assert.equal(await p.locator('#seg-source').evaluate(i=>i.naturalHeight),600);await A('seg-pick-box').click();await A('seg-pick-box').click();assert.equal(await A('seg-upload').innerText(),'上传并自动抠图');assert.equal(posts.length,2);
await p.locator('#seg-photo').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('invalid image')});await p.locator('.seg-error').waitFor();assert.equal(await A('seg-upload').isDisabled(),true);assert.equal(await p.locator('[data-action="seg-restore"]').count(),0);assert.equal(await p.locator('#seg-source').count(),0);assert.equal(posts.length,2);
await p.locator('#seg-photo').setInputFiles({name:'oversized.png',mimeType:'image/png',buffer:Buffer.alloc(10*1024*1024+1)});await p.waitForFunction(()=>document.querySelector('.seg-error')?.textContent.includes('10 MB'));assert.equal(posts.length,2);
report.checks.push({width,pass:true,checks:['local preview without POST','empty box blocked locally','mouse/touch normalized box','one direct refine call','result controls removed','local retouch preserved','no horizontal overflow']});
}catch(e){report.checks.push({width,pass:false,error:e.stack});await p.screenshot({path:path.join(out,'failure-'+width+'.png'),fullPage:true});}finally{await ctx.close();}}
})().catch(e=>report.errors.push(e.stack)).finally(async()=>{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exit(report.errors.length||report.checks.some(c=>!c.pass)?1:0);});
