const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();


 await p.emulateMedia({reducedMotion:'no-preference'});
 const sharp=require(path.join(root,'node_modules/sharp'));
 await p.evaluate(()=>{const paper=paperGroups.flatMap(g=>g.items).find(a=>a[0].startsWith('texture-'))[0];currentBook().pages[1].paper=paper;currentBook().pages[1].elements=[{id:'front-label',type:'text',text:'山风与春日 ABC',font:'serif',size:30,bold:true,color:'#d75436',x:12,y:12,w:65,rotation:0},{id:'front-orange',type:'sticker',assetId:'orange',x:20,y:38,w:38,rotation:-12}];currentBook().pages[2].elements=[{id:'back-label',type:'text',text:'下一页 BACK',font:'sans',size:24,color:'#315b90',x:15,y:20,w:65,rotation:0}];editing=false;renderEditor();});
 await p.evaluate(async()=>{await Promise.all([...document.images].map(im=>im.decode().catch(()=>{})));window.testTurn=prepareReaderTurn(1);testTurn.back.style.visibility='hidden';});
 const reference=await p.locator('.demo-fold-front').screenshot();fs.writeFileSync(path.join(__dirname,'face-reference.png'),reference);
 await p.evaluate(()=>drawSideTurn(testTurn,0));await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>!!testTurn.simple),false);
 const src=await p.evaluate(()=>testTurn.strips[0].querySelector('.side-front').style.backgroundImage.match(/url\(["']?(.*?)["']?\)/)[1]);const png=Buffer.from(src.split(',')[1],'base64');fs.writeFileSync(path.join(__dirname,'face-texture.png'),png);
 const meta=await sharp(reference).metadata(),a=await sharp(reference).removeAlpha().raw().toBuffer(),b=await sharp(png).resize(meta.width,meta.height).removeAlpha().raw().toBuffer();let diff=0;for(let i=0;i<a.length;i++)diff+=Math.abs(a[i]-b[i]);assert.ok(diff/a.length<12,'texture mismatch '+diff/a.length);checks.push({check:'Text, font, sticker and textured paper match original face',meanChannelDifference:diff/a.length});
 for(const progress of [.25,.5,.8]){await p.evaluate(progress=>drawSideTurn(testTurn,progress),progress);await p.screenshot({path:path.join(__dirname,`reader-${progress}.png`)});}
 await p.evaluate(()=>animateReaderTurn(testTurn));await p.waitForFunction(()=>currentBook().page===2&&!readerTurn);assert.equal(await p.locator('.side-strip').count(),0);assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'下一页 BACK');
 await p.locator('[data-action="page-prev"]').click();await p.waitForFunction(()=>currentBook().page===0&&!readerTurn);checks.push('Reader forward/back animations end on the correct editable source content with no leftover strips');
 await p.locator('[data-action="mode"][data-value="edit"]').click();await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===1&&!editingPageTurn);assert.equal(await p.locator('.page-frame').getAttribute('inert'),null);assert.equal(await p.locator('.editor-tools-panel').count(),0);
 await p.locator('#canvas-page [data-element="front-label"]').dblclick();await p.locator('[data-element-command="edit"]').click();await p.locator('.inline-text-input').fill('翻完仍可编辑');await p.locator('.inline-text-input').press('Escape');assert.equal(await p.evaluate(()=>currentElement().text),'翻完仍可编辑');checks.push('Single-page editor animation restores pointer interaction, inline editing, and closed tool state');
 await p.locator('[data-action="editor-layout"][data-value="spread"]').click();await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===2&&!editingPageTurn);await p.locator('[data-action="page-prev"]').click();await p.waitForFunction(()=>currentBook().page===0&&!editingPageTurn);checks.push('Double-page editing keeps paired-page navigation in both directions');
 await p.evaluate(()=>{editing=false;currentBook().page=0;renderEditor();window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.25);cancelReaderTurn();});await p.waitForTimeout(400);assert.equal(await p.locator('.side-strip').count(),0);checks.push('Cancelled preparations do not append textures after the turn has been removed');
 // Deliberate texture failure must keep a visible two-face fallback and finish the turn.
 await p.evaluate(()=>{window.originalGet=window.ShiyePageTextures.get;window.ShiyePageTextures.get=()=>Promise.reject(new Error('fixture capture unavailable'));window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.3);});await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>testTurn.simple),true);await p.screenshot({path:path.join(__dirname,'fallback.png')});await p.evaluate(()=>{window.ShiyePageTextures.get=originalGet;animateReaderTurn(testTurn);});await p.waitForFunction(()=>currentBook().page===2&&!readerTurn);checks.push('Capture failure falls back to the original two faces and never strands the book');
 await p.setViewportSize({width:390,height:844});const touchSession=await context.newCDPSession(p);await touchSession.send('Emulation.setTouchEmulationEnabled',{enabled:true});await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{currentBook().page=0;renderEditor();window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.35);});await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>testTurn.strips.length),12);await p.screenshot({path:path.join(__dirname,'mobile-turn.png')});await p.evaluate(()=>animateReaderTurn(testTurn));await p.waitForFunction(()=>currentBook().page===1&&!readerTurn);checks.push('Mobile single-page reading completes with textures');
 await p.evaluate(()=>{cancelReaderTurn();currentView='home';render();homeDemo.open=true;homeDemo.busy=false;document.querySelector('.home-stage').classList.add('is-open');document.querySelector('#home-book').classList.add('is-open');showHomeSpread();});await p.waitForTimeout(500);await p.evaluate(()=>{window.testTurn=prepareHomeTurn(1);drawSideTurn(testTurn,.4);});await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>!!testTurn.simple),false);await p.screenshot({path:path.join(__dirname,'home-turn.png')});await p.evaluate(()=>animateHomeTurn(testTurn));await p.waitForFunction(()=>homeDemo.spread===1&&!homeDemo.busy);checks.push('Homepage photo-and-sticker demo uses the same texture animation and finishes correctly');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
