const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const label=process.argv[2];if(!/^[a-z0-9-]+$/.test(label||''))throw Error('unique label required');
const out=path.join(__dirname,label);fs.mkdirSync(out);const src=path.resolve(__dirname,'../../shiye-editorial-prototype'),url='http://127.0.0.1:4176';
const report={target:url,checks:[],errors:[],externalRequests:[],screenshots:[]};let browser;
const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
const click=async(p,a,v)=>{await A(p,a,v).click();if(a==='mode')await p.locator(v==='read'?'.read-mode':'.editor-dock').waitFor();};
const shot=async(p,n)=>{await p.screenshot({path:path.join(out,n+'.png'),fullPage:true});report.screenshots.push(n+'.png');};
const saved=async p=>{await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');return p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('shiye-concept-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('data').objectStore('data').get('workspace');q.onsuccess=()=>{db.close();resolve(q.result)};};}));};
const newBook=async(p,title)=>{await click(p,'new-book');await p.locator('#new-title').fill(title);await click(p,'create-book');await p.locator('#canvas-page').waitFor();return (await saved(p)).books.find(b=>b.title===title).id;};
const text=async(p,value,direction='horizontal')=>{await click(p,'drawer','text');await click(p,'add-text');await p.locator('#text-content').fill(value);await p.locator('#text-direction').selectOption(direction);await click(p,'save-text');};
const drag=async(p,from,to)=>{await p.mouse.move(from.x,from.y);await p.mouse.down();await p.mouse.move(to.x,to.y,{steps:16});await p.mouse.up();};
const geom=p=>p.locator('#canvas-page .selected').evaluate(e=>({x:parseFloat(e.style.left),y:parseFloat(e.style.top),w:parseFloat(e.style.width),rotation:e.style.transform}));
async function flow(name,fn,options={}){const c=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce',...options});const p=await c.newPage();p.setDefaultTimeout(6000);p.on('pageerror',e=>report.errors.push({name,message:e.message}));await c.route('**/*',r=>{if(new URL(r.request().url()).origin===url)return r.continue();report.externalRequests.push(r.request().url());r.abort();});try{await p.goto(url,{waitUntil:'networkidle'});await p.locator('.home-copy').waitFor();const result=await fn(p,c);report.checks.push({name,status:'PASS',result});console.log('PASS '+name);}catch(e){report.checks.push({name,status:'FAIL',error:e.message});await shot(p,name+'-failure');console.log('FAIL '+name+': '+e.message);}finally{await c.close();}}
async function main(){
 const baseline=JSON.parse(fs.readFileSync(path.join(__dirname,'interaction-baseline.json')));report.hashes={};for(const name of ['index.html','app.js','styles.css']){const bytes=fs.readFileSync(path.join(src,name)),hash=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(hash,baseline[name]);const res=await fetch(url+'/'+name);assert.equal(res.status,200);assert.ok(bytes.equals(Buffer.from(await res.arrayBuffer())));report.hashes[name]=hash;}
 browser=await chromium.launch({channel:'chrome',headless:true});report.browser=browser.version();
 await flow('return-to-original-page',async p=>{const id=await newBook(p,'原页回流验证');await click(p,'page-add');await text(p,'原来的第二页');const before=(await saved(p)).books.find(b=>b.id===id),pageId=before.pages[1].id;await click(p,'workshop-from-editor');await click(p,'sample');await click(p,'generate');await click(p,'save-and-use');await p.locator('.editor-dock').waitFor();const state=await saved(p),book=state.books.find(b=>b.id===id);assert.equal(book.pages[book.page].id,pageId);assert.equal(book.pages[1].elements.filter(e=>e.type==='sticker').length,2);assert.equal(book.pages[0].elements.length,0);assert.equal(state.assets.length,2);await shot(p,'save-use-original-page');return {pageId,stickers:2,assets:2};});
 await flow('warehouse-creation-picker',async p=>{await click(p,'home-create-sticker');await click(p,'sample');await click(p,'generate');await click(p,'save-and-use');await p.locator('.creation-books').waitFor();await click(p,'creation-new-book');await p.locator('#new-title').fill('从收藏新建');await click(p,'create-book');const state=await saved(p),b=state.books.find(b=>b.title==='从收藏新建');assert.equal(b.pages[0].elements.length,2);await p.locator('[data-action="nav"][data-view="collection"]').click();await p.locator('.sticker-use').first().click();await p.locator('.creation-books').waitFor();await click(p,'close-dialog');await click(p,'enter-creation');await p.locator('.creation-books').waitFor();return {savedBeforePicker:true,newBookContainsAll:true,directWarehouseEntry:true};});
 await flow('desktop-transform-text-drag',async p=>{const id=await newBook(p,'控件验证');await click(p,'drawer','sticker');const tile=await A(p,'insert-sticker').boundingBox(),canvas=await p.locator('#canvas-page').boundingBox();await drag(p,{x:tile.x+tile.width/2,y:tile.y+tile.height/2},{x:canvas.x+canvas.width*.6,y:canvas.y+canvas.height*.4});assert.equal(await p.locator('#canvas-page .element').count(),1);const old=await geom(p),handle=await p.locator('#canvas-page .handle-se').boundingBox();await drag(p,{x:handle.x+handle.width/2,y:handle.y+handle.height/2},{x:handle.x+handle.width/2+26,y:handle.y+handle.height/2+30});assert.ok((await geom(p)).w>old.w);await click(p,'undo');assert.ok(Math.abs((await p.locator('#canvas-page .element').evaluate(e=>parseFloat(e.style.width)))-old.w)<.01);await p.locator('#canvas-page .element').click();const el=await p.locator('#canvas-page .selected').boundingBox(),rot=await p.locator('.handle-rotate').boundingBox();await drag(p,{x:rot.x+rot.width/2,y:rot.y+rot.height/2},{x:el.x+el.width+35,y:el.y+el.height/2});assert.notEqual((await geom(p)).rotation,old.rotation);await text(p,'山风穿过树林\n把日子慢慢收好','vertical');assert.equal(await p.locator('#canvas-page .vertical-text').evaluate(e=>getComputedStyle(e).writingMode),'vertical-rl');await shot(p,'vertical-text-and-handles');await p.locator('#canvas-page .vertical-text').dblclick({delay:100});assert.equal(await p.locator('#text-direction').inputValue(),'vertical');await click(p,'close-dialog');const state=await saved(p);await p.reload();await p.locator('[data-action="nav"][data-view="shelf"]').click();await p.locator(`[data-action="open-book"][data-id="${id}"]`).click();assert.equal(await p.locator('#canvas-page .vertical-text').count(),1);assert.equal(state.books.find(b=>b.id===id).pages[0].elements.find(e=>e.type==='text').direction,'vertical');return {dragFromWarehouse:true,resizeUndo:true,rotateHandle:true,verticalPersisted:true,doubleClick:true};});
 await flow('real-book-front-back',async p=>{const id=await newBook(p,'真正的正反页');for(let i=0;i<4;i++){if(i)await click(p,'page-add');await text(p,'第'+(i+1)+'页独立内容');}const pages=(await saved(p)).books.find(b=>b.id===id).pages;await p.locator('.page-strip [data-value="0"]').click();await click(p,'mode','read');assert.deepEqual(await p.locator('.reader-spread > [data-reader-page]').evaluateAll(es=>es.map(e=>Number(e.dataset.readerPage))),[0]);await click(p,'page-next');await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.deepEqual(await p.locator('.reader-spread > [data-reader-page]').evaluateAll(es=>es.map(e=>Number(e.dataset.readerPage))),[1,2]);await shot(p,'real-book-spread');await click(p,'page-prev');await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.equal(await p.locator('.reader-spread > [data-reader-page="0"]').count(),1);await click(p,'reader-cover');await p.locator('.reader-cover-button').waitFor();await click(p,'reader-open');await click(p,'page-next');await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));await click(p,'page-next');await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.equal(await p.locator('.reader-spread > [data-reader-page="3"]').count(),1);await click(p,'page-next');assert.equal(await p.locator('.reader-back').count(),1);await click(p,'page-prev');await click(p,'mode','edit');assert.equal(await p.locator('#canvas-page').count(),1);assert.deepEqual((await saved(p)).books.find(b=>b.id===id).pages,pages);return {fourFacesDistinct:true,insideCovers:true,frontBackCovers:true,noPageContentMutation:true,singlePageEditing:true};});
 await flow('reader-corner-commit-cancel',async p=>{await p.locator('[data-action="nav"][data-view="shelf"]').click();await A(p,'open-book').click();const b=await p.locator('.reader-spread').boundingBox();await p.mouse.move(b.x+b.width*.97,b.y+b.height*.95);await p.mouse.down();await p.mouse.move(b.x+b.width*.92,b.y+b.height*.9,{steps:8});await p.mouse.up();await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.equal(await p.locator('.reader-spread > [data-reader-page="0"]').count(),1);await p.mouse.move(b.x+b.width*.97,b.y+b.height*.95);await p.mouse.down();await p.mouse.move(b.x+b.width*.45,b.y+b.height*.62,{steps:16});await shot(p,'real-book-corner-fold');assert.equal(await p.locator('.reader-turn-layer .demo-fold-back [data-reader-page="1"]').count(),1);await p.mouse.up();await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.equal(await p.locator('.reader-spread > [data-reader-page="1"]').count(),1);return {smallDragRollsBack:true,cornerHasDifferentBackContent:true,commit:true};},{reducedMotion:'no-preference'});
 await flow('local-outline-boundary',async p=>{await click(p,'home-create-sticker');await p.locator('#photo-input').setInputFiles(path.join(src,'assets/lake.jpg'));await click(p,'crop-mode','outline');const r=await p.locator('#crop-stage').boundingBox();const points=[[.2,.2],[.8,.2],[.55,.48],[.8,.8],[.2,.8],[.4,.48],[.2,.2]];await p.mouse.move(r.x+r.width*points[0][0],r.y+r.height*points[0][1]);await p.mouse.down();for(const [x,y] of points.slice(1))await p.mouse.move(r.x+r.width*x,r.y+r.height*y,{steps:10});await p.mouse.up();assert.match(await p.locator('.workshop-aside').innerText(),/不会自动贴边/);assert.equal(await p.locator('.crop-outline').count(),1);await shot(p,'local-outline-not-ai');await click(p,'generate');const stats=await p.locator('#sticker-preview').evaluate(async el=>{await el.decode();const c=document.createElement('canvas');c.width=el.naturalWidth;c.height=el.naturalHeight;const x=c.getContext('2d');x.drawImage(el,0,0);const a=x.getImageData(0,0,c.width,c.height).data;let transparent=0,opaque=0;for(let i=3;i<a.length;i+=4){if(a[i]===0)transparent++;if(a[i]===255)opaque++;}return {transparent,opaque};});assert.ok(stats.transparent>100&&stats.opaque>100);await click(p,'save-stickers');assert.equal((await saved(p)).assets.length,1);return {...stats,actualAI:false,localOnly:true};});
 await flow('mobile-pinch-rotate',async(p,c)=>{await newBook(p,'双指测试');await click(p,'drawer','sticker');await click(p,'insert-sticker');const before=await geom(p),el=await p.locator('#canvas-page .selected').boundingBox(),x=el.x+el.width/2,y=el.y+el.height/2;const client=await c.newCDPSession(p);const touch=(type,pts)=>client.send('Input.dispatchTouchEvent',{type,touchPoints:pts.map(([x,y],id)=>({x,y,id,radiusX:2,radiusY:2,force:1}))});await touch('touchStart',[[x-15,y],[x+15,y]]);for(let i=1;i<=8;i++)await touch('touchMove',[[x-15-i*1.2,y-i],[x+15+i*1.2,y+i]]);await touch('touchEnd',[]);const after=await geom(p);assert.ok(after.w>before.w);assert.notEqual(after.rotation,before.rotation);await click(p,'undo');const restored=await p.locator('#canvas-page .element').evaluate(e=>parseFloat(e.style.width));assert.equal(restored,before.w);await click(p,'mode','read');assert.equal(await p.locator('.reader-spread.single').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);await shot(p,'mobile-reading');return {before,after,undoOneGesture:true,physicalDevice:false,chromeTouchInput:true};},{viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 await flow('mobile-longpress-drag',async(p,c)=>{await newBook(p,'长按测试');await click(p,'drawer','sticker');const t=await A(p,'insert-sticker').boundingBox(),r=await p.locator('#canvas-page').boundingBox(),client=await c.newCDPSession(p);const x=t.x+t.width/2,y=t.y+t.height/2;await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:0}]});await p.waitForTimeout(360);await p.locator('.sticker-drag-ghost').waitFor();for(let i=1;i<=12;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(r.x+r.width*.7-x)*i/12,y:y+(r.y+r.height*.35-y)*i/12,id:0}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.locator('#canvas-page .element').count(),1);assert.equal(await p.locator('.sticker-drag-ghost').count(),0);await saved(p);await shot(p,'mobile-longpress-result');return {longPressDrag:true,noDuplicateInsertion:true,physicalDevice:false};},{viewport:{width:390,height:844},isMobile:true,hasTouch:true});
}
main().catch(e=>{report.fatal=e.stack;console.error(e);}).finally(async()=>{await browser?.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,pass:report.checks.filter(c=>c.status==='PASS').length,fail:report.checks.filter(c=>c.status==='FAIL').length,errors:report.errors,fatal:report.fatal}));process.exitCode=report.fatal||report.checks.some(c=>c.status==='FAIL')||report.errors.length?1:0;});
