const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const label=process.argv[2];if(!/^[a-z0-9-]+$/.test(label||''))throw Error('unique label required');
const out=path.join(__dirname,label);fs.mkdirSync(out);const src=path.resolve(__dirname,'../../shiye-editorial-prototype'),url='http://127.0.0.1:4176';
const report={target:url,checks:[],errors:[],externalRequests:[],screenshots:[]};let browser;
const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
const click=async(p,a,v)=>{await A(p,a,v).click();if(a==='mode')await p.locator(v==='read'?'.read-mode':'.editor-dock').waitFor();};
const shot=async(p,n)=>{await p.screenshot({path:path.join(out,n+'.png'),fullPage:true});report.screenshots.push(n+'.png');};
const saved=async p=>{await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');return p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('shiye-concept-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('data').objectStore('data').get('workspace');q.onsuccess=()=>{db.close();resolve(q.result)};};}));};
const newBook=async(p,title)=>{await click(p,'new-book');await p.locator('#new-title').fill(title);await click(p,'create-book');await p.locator('#canvas-page').waitFor();return (await saved(p)).books.find(b=>b.title===title).id;};
const text=async(p,value,direction='horizontal')=>{await click(p,'drawer','text');await click(p,'add-text');await p.locator('#text-content').fill(value);await p.locator('#text-direction').selectOption(direction);await click(p,'save-text');};
const drag=async(p,from,to)=>{await p.mouse.move(from.x,from.y);await p.mouse.down();await p.mouse.move(to.x,to.y,{steps:16});await p.mouse.up();};
const geom=p=>p.locator('#canvas-page .selected').evaluate(e=>({x:parseFloat(e.style.left),y:parseFloat(e.style.top),w:parseFloat(e.style.width),rotation:e.style.transform}));
async function flow(name,fn,options={}){const c=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce',...options});const p=await c.newPage();p.setDefaultTimeout(6000);p.on('pageerror',e=>report.errors.push({name,message:e.message}));await c.route('**/*',r=>{if(new URL(r.request().url()).origin===url)return r.continue();report.externalRequests.push(r.request().url());r.abort();});try{await p.goto(url,{waitUntil:'networkidle'});await p.locator('.home-copy').waitFor();const result=await fn(p,c);report.checks.push({name,status:'PASS',result});console.log('PASS '+name);}catch(e){report.checks.push({name,status:'FAIL',error:e.message});await shot(p,name+'-failure');console.log('FAIL '+name+': '+e.message);}finally{await c.close();}}
async function main(){
 report.hashes={};for(const n of ['app.js','styles.css'])report.hashes[n]=crypto.createHash('sha256').update(fs.readFileSync(path.join(src,n))).digest('hex');
 browser=await chromium.launch({channel:'chrome',headless:true});
 await flow('editing-turn-resize-cancel',async p=>{const id=await newBook(p,'取消翻页');await text(p,'原页');await click(p,'page-add');await text(p,'第二页');const before=(await saved(p)).books.find(b=>b.id===id).pages;await click(p,'page-prev');await p.locator('.side-strip').first().waitFor();await p.setViewportSize({width:800,height:900});await p.waitForFunction(()=>!document.querySelector('.editing-turn-layer'));assert.equal(await p.locator('#canvas-page .text').innerText(),'第二页');assert.equal(await p.locator('.page-frame').evaluate(e=>e.inert),false);assert.deepEqual((await saved(p)).books.find(b=>b.id===id).pages,before);return {canceledWithoutPageChange:true,unlocked:true};},{reducedMotion:'no-preference'});
 await flow('editing-turn-save-failure',async p=>{await newBook(p,'失败不翻页');await click(p,'page-add');await text(p,'未保存时留在这页');await saved(p);await p.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('test quota','QuotaExceededError')}});await click(p,'page-prev');await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='保存失败，请重试');assert.equal(await p.locator('.side-strip').count(),0);assert.equal(await p.locator('#canvas-page .text').innerText(),'未保存时留在这页');return {failedSaveBlocksTurn:true};});
}
main().catch(e=>report.fatal=e.stack).finally(async()=>{await browser?.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exitCode=report.fatal||report.checks.some(c=>c.status==='FAIL')?1:0;});

