const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.SHIYE_PLAYWRIGHT_PATH||'/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),src=path.join(root,'shiye-editorial-prototype'),url='http://127.0.0.1:4176';
const label=process.argv.find(x=>x.startsWith('--label='))?.slice(8),baseline=process.argv.includes('--baseline');
const interaction=process.argv.includes('--interactions');
const revision=process.argv.includes('--four-fixes')||interaction;
if(!label||!/^[a-z0-9_-]+$/.test(label))throw Error('Unique --label=NAME required');
const out=path.join(__dirname,label);fs.mkdirSync(out);
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const names=['index.html','app.js','styles.css','assets/lake.jpg','assets/forest.jpg','assets/coffee.jpg','assets/home-landscape-sticker.png'];
const protectedFiles=[...names.map(n=>path.join(src,n)),...['拾页-PRD.md','拾页-产品设计文档.md','拾页-AI与后端技术方案.md'].map(n=>path.join(root,n))];
const hashes=Object.fromEntries(protectedFiles.map(n=>[n,hash(fs.readFileSync(n))]));
const report={target:url,identity:'米白底左文右书首页；非木桌版',started:new Date().toISOString(),scriptHash:hash(fs.readFileSync(__filename)),hashes,http:[],checks:[],flows:[],errors:[],httpErrors:[],externalRequests:[],screenshots:[]};
let browser,flowName='baseline';
const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`);
const click=async(p,a,v)=>A(p,a,v).first().click();
const shot=async(p,n)=>{await p.screenshot({path:path.join(out,n+'.png'),fullPage:true});report.screenshots.push(n+'.png');};
async function stored(p){return p.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('shiye-concept-v1',1);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const d=r.result,q=d.transaction('data','readonly').objectStore('data').get('workspace');q.onsuccess=()=>{d.close();resolve(q.result)};q.onerror=()=>{d.close();reject(q.error)};};}));}
async function saved(p){await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');return stored(p);}
async function view(p,n){const markers={editor:'#canvas-page',shelf:'.books-grid',collection:'#collection-results',workshop:'.workshop-layout',home:'.home-copy'};await p.locator(markers[n]).waitFor({state:'visible'});}
async function nav(p,n){await p.locator(`[data-action="nav"][data-view="${n}"]`).first().click();await view(p,n);}
async function newBook(p,title){await click(p,'new-book');await p.locator('#new-title').fill(title);await click(p,'create-book');await view(p,'editor');return (await saved(p)).books.find(b=>b.title===title).id;}
async function addText(p,text){await click(p,'drawer','text');await click(p,'add-text');await p.locator('#text-content').fill(text);await click(p,'save-text');}
const book=(s,id)=>{const b=s.books.find(b=>b.id===id);assert.ok(b,'stored book exists');return b;};
async function step(id,fn){try{const evidence=await fn();report.checks.push({flow:flowName,id,status:'PASS',evidence});console.log('PASS '+id);}catch(e){report.checks.push({flow:flowName,id,status:'FAIL',error:e.message});console.log('FAIL '+id+': '+e.message);throw e;}}
async function ctx(opts={}){const c=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce',...opts});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===url||['data:','blob:'].includes(u.protocol))return r.continue();report.externalRequests.push({origin:u.origin,path:u.pathname});return r.abort();});c.on('page',p=>{p.setDefaultTimeout(5000);p.on('pageerror',e=>report.errors.push({flow:flowName,error:e.message}));p.on('response',r=>{if(r.status()>=400)report.httpErrors.push({flow:flowName,status:r.status(),path:new URL(r.url()).pathname});});});return c;}
async function fresh(c){const p=await c.newPage();await p.goto(url,{waitUntil:'networkidle'});await p.locator('.home-copy').waitFor();assert.equal(await p.locator('.desk-backdrop,.desk-workspace').count(),0);assert.match(await p.locator('.home-description').innerText(),/从照片里拾起一点喜欢/);return p;}
async function flow(name,fn,opts={}){flowName=name;const c=await ctx(opts);let p;try{p=await fresh(c);await fn(p,c);report.flows.push({name,status:'COMPLETED'});}catch(e){report.flows.push({name,status:'STOPPED_AT_FIRST_FAILURE',error:e.message});if(p)await shot(p,name+'-failure').catch(()=>{});}finally{await c.close();}}
async function injectQuota(p){await p.evaluate(()=>{const original=IDBObjectStore.prototype.put;window.__verificationRestorePut=()=>{IDBObjectStore.prototype.put=original;};IDBObjectStore.prototype.put=function(...args){if(this.name==='data')throw new DOMException('Synthetic quota failure','QuotaExceededError');return original.apply(this,args);};});}
async function main(){
 for(const n of ['index.html','app.js','styles.css']){
  if(revision){const pinned=JSON.parse(fs.readFileSync(path.join(__dirname,interaction?'interaction-baseline.json':'four-fixes-baseline.json')));assert.equal(hash(fs.readFileSync(path.join(src,n))),pinned[n],'Not pinned baseline: '+n);}
  else assert.ok(fs.readFileSync(path.join(src,n)).equals(cp.execFileSync('tar',['-xOzf',path.join(src,'checkpoint-before-desk-20260907.tar.gz'),n])),'Not cream checkpoint: '+n);
 }
 for(const n of names){const r=await fetch(url+'/'+(n==='index.html'?'':n));const bytes=Buffer.from(await r.arrayBuffer());assert.equal(r.status,200);assert.ok(bytes.equals(fs.readFileSync(path.join(src,n))),'HTTP mismatch: '+n);report.http.push({file:n,status:r.status,sha256:hash(bytes)});}
 browser=await chromium.launch({channel:'chrome',headless:true});report.browser=browser.version();
 if(baseline){await flow('identity',async p=>{await step('IDENTITY',async()=>{const broken=await p.locator('img').evaluateAll(ns=>ns.filter(n=>!n.complete||!n.naturalWidth).map(n=>n.getAttribute('src')));assert.deepEqual(broken,[]);await shot(p,'cream-home-identity');return {brokenImages:broken,layout:'left home-copy and right home-stage; no desk background',title:await p.title()};});});return;}
 await flow('home',async p=>{
  await step('HOME-01',async()=>{const before=await stored(p);assert.equal(await p.locator('.home-demo-controls').isVisible(),false);await p.locator('.home-watch').click();await p.locator('.home-demo-controls').waitFor();assert.equal(await A(p,'home-prev').isDisabled(),true);await click(p,'home-next');await p.waitForFunction(()=>document.querySelector('.demo-progress').textContent.includes('03'));await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('.demo-progress').textContent.includes('05'));assert.equal(await A(p,'home-next').isDisabled(),true);await shot(p,'cream-demo-open');await p.keyboard.press('Escape');assert.equal(await p.locator('.home-demo-controls').isVisible(),false);assert.deepEqual(await stored(p),before);await click(p,'home-create-sticker');await p.locator('#upload-zone').waitFor();return {openNextKeyboardClose:true,demoDoesNotWrite:true,workshopEntry:true};});
 });
 await flow('corner-motion',async p=>{await step('HOME-02',async()=>{await p.locator('.home-watch').click();await p.waitForFunction(()=>!document.querySelector('.demo-next').disabled);await p.waitForTimeout(350);const b=await p.locator('#home-book').boundingBox();await p.mouse.move(b.x+b.width*.95,b.y+b.height*.9);await p.mouse.down();await p.mouse.move(b.x+b.width*.2,b.y+b.height*.4,{steps:20});await shot(p,'cream-corner-turn');await p.mouse.up();await p.waitForFunction(()=>document.querySelector('.demo-progress').textContent.includes('03'));return {cornerDragCommitted:true,reducedMotion:false};});},{reducedMotion:'no-preference'});
 await flow('sample-multiselect',async p=>{await step('DEMO-01',async()=>{await click(p,'home-create-sticker');await click(p,'sample');await p.locator('.subject-buttons [data-id="coffee"]').click();await p.locator('.subject-buttons [data-id="flower"]').click();assert.equal(await A(p,'generate').isDisabled(),true);for(const id of ['coffee','flower','camera'])await p.locator(`.subject-buttons [data-id="${id}"]`).click();await click(p,'generate');await p.locator('#sticker-preview').waitFor();assert.equal(await p.locator('.preview-switch button').count(),3);await click(p,'save-stickers');await view(p,'collection');const s=await stored(p);assert.equal(s.assets.length,3);assert.equal(new Set(s.assets.map(a=>a.id)).size,3);assert.ok(s.assets.every(a=>a.src.startsWith('data:image/svg+xml')));return {selected:3,stored:3,kind:'prebuilt SVG demonstration, not real segmentation'};});});
 await flow('file-errors',async p=>{await click(p,'home-create-sticker');await step('PHOTO-01',async()=>{for(const [name,mimeType,buffer,message] of [['bad.txt','text/plain',Buffer.from('test'),'JPG'],['large.png','image/png',Buffer.alloc(10*1024*1024+1),'10 MB'],['broken.png','image/png',Buffer.from('not PNG'),'无法读取']]){await p.locator('#photo-input').setInputFiles({name,mimeType,buffer});await p.waitForFunction(m=>document.querySelector('#toast').textContent.includes(m),message);assert.equal(await p.locator('#upload-zone').isVisible(),true);}return {invalidType:true,oversize:true,corruptImage:true};});});
 await flow('photo-to-book',async p=>{
  let assetId,bookId,secondId,pagesBefore;
  await step('CHAIN-01',async()=>{await click(p,'home-create-sticker');await p.locator('#photo-input').setInputFiles(path.join(src,'assets/lake.jpg'));await p.locator('#crop-stage').waitFor();const b=await p.locator('#crop-stage').boundingBox();for(const [x1,x2] of [[.18,.46],[.52,.8]]){await p.mouse.move(b.x+b.width*x1,b.y+b.height*.3);await p.mouse.down();await p.mouse.move(b.x+b.width*x2,b.y+b.height*.65,{steps:10});await p.mouse.up();}assert.match(await p.locator('#selected-count').innerText(),/2/);await click(p,'generate');await p.locator('#sticker-preview').waitFor();assert.equal(await p.locator('.preview-switch button').count(),2);await p.locator('#preview-name').fill('米白版验证山湖');await p.locator('#preview-name').press('Tab');await p.locator('#border-range').fill('8');await click(p,'save-stickers');await view(p,'collection');const s=await stored(p);assert.equal(s.assets.length,2);assetId=s.assets[0].id;secondId=s.assets[1].id;const alpha=await p.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const x=c.getContext('2d');x.drawImage(i,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let count=0;for(let n=3;n<d.length;n+=4)if(d[n]<255)count++;return {width:i.width,height:i.height,transparentPixels:count,pixels:d.length/4};},s.assets[0].src);assert.equal(s.assets[0].border,8);return {count:2,assetId,alpha,mode:'rectangular crop, NOT AI cutout'};});
  await step('CHAIN-02',async()=>{await nav(p,'shelf');bookId=await newBook(p,'米白版端到端验证');await click(p,'drawer','sticker');await p.locator(`[data-action="insert-sticker"][data-id="${assetId}"]`).click();let el=p.locator('#canvas-page .element').first();const old=await el.getAttribute('style'),b=await el.boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+40,b.y+b.height/2+28,{steps:12});await p.mouse.up();assert.notEqual(await el.getAttribute('style'),old);const w=await el.evaluate(n=>parseFloat(n.style.width));await click(p,'larger');assert.ok(await el.evaluate(n=>parseFloat(n.style.width))>w);await click(p,'rotate-right');assert.match(await el.getAttribute('style'),/rotate\(5deg\)/);await click(p,'flip');await click(p,'duplicate');assert.equal(await p.locator('#canvas-page .element').count(),2);await click(p,'layer-down');let s=await saved(p);assert.equal(book(s,bookId).pages[0].elements[1].assetId,assetId);await click(p,'undo');await click(p,'undo');assert.equal(await p.locator('#canvas-page .element').count(),1);await click(p,'redo');assert.equal(await p.locator('#canvas-page .element').count(),2);await p.locator('#canvas-page .element').last().click();await click(p,'delete-element');assert.equal(await p.locator('#canvas-page .element').count(),1);return {createdOnePage:true,generatedAssetInserted:true,dragScaleRotateFlipCopyLayerUndoRedoDelete:true};});
  await step('CHAIN-03',async()=>{await addText(p,'米白版：初始文字');await click(p,'edit-text');await p.locator('#text-content').fill('米白版：刷新后仍可编辑');await click(p,'save-text');const s=await saved(p);assert.equal(book(s,bookId).pages[0].elements.find(e=>e.type==='text').text,'米白版：刷新后仍可编辑');await shot(p,'cream-editor');return {createText:true,editViaToolbar:true};});
  await step('CHAIN-04',async()=>{await click(p,'page-add');await click(p,'drawer','paper');await click(p,'paper','grid');const b=book(await saved(p),bookId);assert.deepEqual(b.pages.map(p=>p.paper),['plain','grid']);assert.equal(b.pages[0].elements.length,2);pagesBefore=b.pages;return {pagePaperIndependent:true,papers:b.pages.map(p=>p.paper)};});
  await step('CHAIN-05',async()=>{await click(p,'shelve');await view(p,'shelf');await p.reload({waitUntil:'networkidle'});await nav(p,'shelf');await p.locator(`[data-action="open-book"][data-id="${bookId}"]`).click();assert.equal(await p.locator('.read-mode').count(),1);assert.equal(await p.locator('.editor-dock').count(),0);let s=await stored(p);assert.deepEqual(book(s,bookId).pages,pagesBefore);assert.ok(s.assets.some(a=>a.id===assetId));await p.locator('.page-strip [data-value="0"]').click();const html=await p.locator('#canvas-page').innerHTML();let b=await p.locator('#canvas-page .element').first().boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+45,b.y+b.height/2+30,{steps:8});await p.mouse.up();await p.keyboard.press('Delete');assert.equal(await p.locator('#canvas-page').innerHTML(),html);await click(p,'mode','edit');assert.equal(await p.locator('.editor-dock').count(),1);assert.equal(await p.locator('#canvas-page img').evaluateAll(ns=>ns.every(n=>n.complete&&n.naturalWidth>0)),true);return {dataAndReferencesRestored:true,readModeProtected:true,explicitEdit:true};});
  await step('CHAIN-06',async()=>{await nav(p,'collection');await click(p,'collection-tab','mine');await p.locator(`[data-action="sticker-detail"][data-id="${assetId}"]`).click();await click(p,'manage-sticker');await click(p,'remove-sticker');await saved(p);await p.reload({waitUntil:'networkidle'});await nav(p,'shelf');await p.locator(`[data-action="open-book"][data-id="${bookId}"]`).click();const s=await stored(p);assert.equal(s.assets.some(a=>a.id===assetId),false);assert.ok(s.archivedAssets.some(a=>a.id===assetId));assert.ok(s.assets.some(a=>a.id===secondId));await p.locator('#canvas-page img').first().waitFor();assert.equal(await p.locator('#canvas-page img').first().evaluate(n=>n.complete&&n.naturalWidth>0),true);return {removedFromCollection:true,usedAssetPreservedAcrossReload:true};});
 });
 await flow('page-management',async p=>{let id;await step('PAGE-01',async()=>{id=await newBook(p,'页面管理验证');await click(p,'drawer','pages');assert.equal(await A(p,'delete-page').isDisabled(),true);await click(p,'close-drawer');await addText(p,'第一页');await click(p,'drawer','pages');await click(p,'duplicate-page');let b=book(await saved(p),id);assert.equal(b.pages.length,2);assert.notEqual(b.pages[0].id,b.pages[1].id);assert.notEqual(b.pages[0].elements[0].id,b.pages[1].elements[0].id);const copy=b.pages[1].id;await click(p,'move-page-up','1');b=book(await saved(p),id);assert.equal(b.pages[0].id,copy);await click(p,'delete-page');assert.equal(await p.locator('#dialog').evaluate(n=>n.open),true);await click(p,'confirm-delete-page');assert.equal(book(await saved(p),id).pages.length,1);await click(p,'undo');assert.equal(book(await saved(p),id).pages.length,2);return {lastPageProtected:true,copyIdsUnique:true,reorder:true,deleteConfirmed:true,undoDelete:true};});});
 await flow('text-doubleclick',async p=>{await newBook(p,'双击文字验证');await addText(p,'双击这段测试文字');await step('TEXT-01',async()=>{await p.locator('#canvas-page .element.text').dblclick({delay:100});await p.waitForTimeout(200);const opened=await p.locator('#dialog').evaluate(n=>n.open);await shot(p,'text-doubleclick');assert.equal(opened,true,'Double-click selected text but editor dialog did not open');return {opened};});});
 await flow('save-failure-and-retry',async p=>{const id=await newBook(p,'失败保存验证');const before=await stored(p);await injectQuota(p);await addText(p,'等待重试的测试内容');await step('SAVE-01',async()=>{await click(p,'shelve');await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent.includes('保存失败'));assert.equal(await p.locator('#canvas-page').count(),1);assert.deepEqual(await stored(p),before);await shot(p,'quota-failure-editor');return {shelveBlocked:true,failureVisible:true,storedUnchanged:true,unsavedContentRetained:true};});await step('SAVE-02',async()=>{await p.evaluate(()=>window.__verificationRestorePut());await click(p,'shelve');await view(p,'shelf');const s=await stored(p);assert.equal(book(s,id).pages[0].elements[0].text,'等待重试的测试内容');return {retryViaShelveCommitted:true};});});
 await flow('failed-read-switch',async p=>{await newBook(p,'失败切换验证');await injectQuota(p);await addText(p,'没有保存的测试内容');await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent.includes('保存失败'));await step('SAVE-03',async()=>{await click(p,'mode','read');await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='保存失败，请重试');await shot(p,'failed-read-switch');assert.equal(await p.locator('.read-mode').count(),0,'Save failed but switched to reading mode');return {staysEditing:true};});});
 await flow('two-tabs',async(p,c)=>{const q=await fresh(c);await step('DATA-01',async()=>{const aid=await newBook(p,'标签页A创建');assert.ok((await stored(p)).books.some(b=>b.id===aid));const bid=await newBook(q,'标签页B创建');const s=await stored(q);await shot(q,'two-tabs-final');const found=s.books.filter(b=>!b.sample).map(b=>b.title);assert.ok(s.books.some(b=>b.id===aid)&&s.books.some(b=>b.id===bid),'Expected both books, stored '+JSON.stringify(found));return {found};});});
 if(revision)await flow('same-book-conflict',async(p,c)=>{
  const q=await fresh(c);const id=(await stored(p)).books[0].id;
  for(const page of [p,q]){await nav(page,'shelf');await page.locator(`[data-action="open-book"][data-id="${id}"]`).click();await click(page,'mode','edit');}
  await step('DATA-02',async()=>{await addText(p,'标签A的新内容');await saved(p);await addText(q,'标签B的新内容');const s=await saved(q),original=book(s,id),copies=s.books.filter(b=>b.title.includes('冲突副本'));assert.equal(copies.length,1);assert.ok(original.pages[0].elements.some(e=>e.text==='标签A的新内容'));assert.ok(copies[0].pages[0].elements.some(e=>e.text==='标签B的新内容'));assert.equal(original.pages[0].elements.some(e=>e.text==='标签B的新内容'),false);assert.equal(await q.locator('#book-title').inputValue(),copies[0].title);await shot(q,'conflict-copy');await click(q,'shelve');await view(q,'shelf');assert.equal((await stored(q)).books.filter(b=>b.title.includes('冲突副本')).length,1);return {bothContentsPreserved:true,activeBookIsCopy:true,noDuplicateOnRetry:true};});
 });
 if(revision)await flow('old-photo-vs-new-choice',async p=>{await step('ASYNC-02',async()=>{await click(p,'home-create-sticker');let release,started;const gate=new Promise(r=>release=r),seen=new Promise(r=>started=r);await p.route('**/assets/lake.jpg',async route=>{started();await gate;await route.continue();});await click(p,'crop-example');await seen;await click(p,'sample');release();await p.waitForTimeout(600);assert.equal(await p.locator('.sample-scene').count(),1);assert.equal(await p.locator('#crop-stage').count(),0);return {newChoicePreserved:true};});});
 await flow('late-photo-response',async(p,c)=>{await step('ASYNC-01',async()=>{await click(p,'home-create-sticker');let release,started;const gate=new Promise(r=>release=r),seen=new Promise(r=>started=r);await p.route('**/assets/lake.jpg',async route=>{started();await gate;await route.continue();});await click(p,'crop-example');await seen;await nav(p,'shelf');release();await p.waitForTimeout(900);const title=await p.locator('h1').innerText();await shot(p,'late-photo-response');assert.match(title,/我的书架/,'Late photo response replaced current screen');return {shelfPreserved:true};});});
 for(const width of [390,320])await flow('mobile-'+width,async p=>{await step('MOBILE-'+width,async()=>{assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await shot(p,'home-mobile-'+width);await click(p,'home-create-sticker');await p.locator('#upload-zone').waitFor();await nav(p,'shelf');await A(p,'open-book').first().tap();assert.equal(await p.locator('.read-mode').count(),1);await A(p,'mode','edit').tap();await p.locator('#canvas-page .element').last().tap();assert.equal(await p.locator('#canvas-page .selected').count(),1);await A(p,'larger').tap();await A(p,'rotate-right').tap();await shot(p,'editor-mobile-'+width);const dimensions=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:document.querySelector('#canvas-page').getBoundingClientRect().width}));assert.equal(dimensions.scroll,width);await click(p,'shelve');await view(p,'shelf');return {dimensions,touchSelectScaleRotate:true,physicalDevice:false};});},{viewport:{width,height:844},isMobile:true,hasTouch:true});
}
main().catch(e=>{report.fatal=e.stack;console.error(e);}).finally(async()=>{if(browser)await browser.close();report.unchanged=protectedFiles.every(n=>hash(fs.readFileSync(n))===hashes[n]);report.finished=new Date().toISOString();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,pass:report.checks.filter(c=>c.status==='PASS').length,fail:report.checks.filter(c=>c.status==='FAIL').length,unchanged:report.unchanged,fatal:report.fatal||null}));process.exitCode=report.fatal?2:report.checks.some(c=>c.status==='FAIL')?1:0;});
