const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);let server,browser;const report={checks:[],errors:[]};
(async()=>{const {createApp}=await import(pathToFileURL(path.join(root,'dist/server/app.js')));const {app}=await createApp({runtime:fs.mkdtempSync(path.join(os.tmpdir(),'shiye-materials-')),staticRoot:path.join(root,'shiye-editorial-prototype')});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [1440,390,320]){const ctx=await browser.newContext({viewport:{width,height:950},isMobile:width<500,hasTouch:width<500,reducedMotion:'reduce'}),p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>report.errors.push(e.message));await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const A=a=>p.locator(`[data-action="${a}"]`).first(),tab=v=>p.locator(`[data-action="collection-tab"][data-value="${v}"]`),card=id=>p.locator(`[data-asset-id="${id}"]`),snap=n=>p.screenshot({path:path.join(out,n+'-'+width+'.png'),fullPage:n!=='menu'});
try{await p.goto(base,{waitUntil:'networkidle'});assert.ok((await p.locator('body').innerText()).length>100);assert.equal((await A('home-create-sticker').innerText()).trim(),'开始创作');await A('home-create-sticker').click();await p.locator('.books-grid').waitFor();const buttons=p.locator('.shelf-create-actions .button'),b1=await buttons.nth(0).boundingBox(),b2=await buttons.nth(1).boundingBox();assert.equal(b1.width,b2.width);assert.equal(b1.height,b2.height);assert.equal(b1.x,b2.x);assert.ok(b2.y>b1.y+b1.height);await snap('shelf');await buttons.nth(0).click();await p.locator('#new-title').waitFor();await A('close-dialog').click();await p.locator('[data-shelf-create-sticker]').click();await p.locator('#upload-zone').waitFor();await A('crop-example').click();await p.locator('#crop-stage').waitFor();assert.equal(await p.locator('.edge-private').count(),0);assert.equal((await p.locator('body').innerText()).includes('照片仅在本机处理'),false);
await A('edge-disable').click();for(const [x,y] of [[.2,.2],[.8,.2],[.8,.8],[.2,.8]]){const stage=p.locator('#crop-stage'),r=await stage.boundingBox();await stage.click({position:{x:r.width*x,y:r.height*y}});}await A('finish-scissors').click();await A('generate').click();await p.locator('#sticker-preview').waitFor();await A('save-stickers').click();await p.locator('.collection-header').waitFor();assert.equal(await p.evaluate(()=>state.assets.length===1&&state.assets[0].createdAt>0&&!state.assets[0].favorite),true);await p.evaluate(async()=>{state.assets=[{...builtin[0],id:'legacy-old',name:'旧素材'},{...builtin[1],id:'legacy-new',name:'较新素材'},{...builtin[2],id:'newest',name:'最新制作',createdAt:Date.now()}];state.books[0].pages[0].elements.push({id:'kept-sticker',type:'sticker',assetId:'legacy-old',x:20,y:20,w:30,rotation:0});mutationVersion++;await saveNow();});await p.locator('[data-action="nav"][data-view="collection"]:visible').first().click();assert.ok((await tab('mine').innerText()).includes('我的素材'));assert.equal(await tab('favorites').count(),1);assert.deepEqual(await p.locator('#collection-results .sticker-card').evaluateAll(es=>es.map(e=>e.dataset.assetId)),['newest','legacy-new','legacy-old']);assert.equal(await p.locator('.sticker-use svg').count(),0);await snap('materials');
async function menu(id,action){await card(id).locator('.sticker-more').click();await p.locator(`#sticker-menu-${id}:popover-open`).waitFor();await p.locator(`#sticker-menu-${id} [data-action="${action}"]`).click();await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');}
await card('newest').locator('.sticker-more').click();await p.locator('#sticker-menu-newest:popover-open').waitFor();await snap('menu');assert.equal(await p.locator('#sticker-menu-newest:popover-open').count(),1);await p.keyboard.press('Escape');assert.equal(await p.locator('.book-popover:popover-open').count(),0);await menu('legacy-new','favorite-sticker');await tab('favorites').click();assert.deepEqual(await p.locator('#collection-results .sticker-card').evaluateAll(es=>es.map(e=>e.dataset.assetId)),['legacy-new']);await menu('legacy-new','favorite-sticker');await p.locator('.empty').waitFor();await tab('mine').click();assert.equal(await p.locator('.sticker-card').count(),3);await menu('legacy-new','favorite-sticker');await menu('legacy-old','pin-sticker');assert.equal(await p.locator('.sticker-card').first().getAttribute('data-asset-id'),'legacy-old');
await p.reload({waitUntil:'networkidle'});await A('home-create-sticker').click();await p.locator('[data-action="nav"][data-view="collection"]:visible').first().click();assert.equal(await p.locator('.sticker-card').first().getAttribute('data-asset-id'),'legacy-old');await tab('favorites').click();assert.equal(await card('legacy-new').count(),1);await tab('mine').click();await card('legacy-old').locator('.sticker-more').click();await p.locator('#sticker-menu-legacy-old [data-action="delete-sticker-confirm"]').click();await p.locator('#dialog[open]').waitFor();await snap('delete');await A('close-dialog').click();assert.equal(await card('legacy-old').count(),1);await card('legacy-old').locator('.sticker-more').click();await p.locator('#sticker-menu-legacy-old [data-action="delete-sticker-confirm"]').click();await A('remove-sticker').click();await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');assert.equal(await card('legacy-old').count(),0);assert.equal(await p.evaluate(()=>!!asset('legacy-old')&&state.archivedAssets.some(a=>a.id==='legacy-old')&&state.books[0].pages[0].elements.some(e=>e.assetId==='legacy-old')),true);
await card('newest').locator('.sticker-use').click();await p.locator('.creation-books').waitFor();await A('close-dialog').click();await tab('builtin').click();await p.locator('.sticker-display').first().click();await A('collect').click();await tab('favorites').click();assert.equal(await p.locator('.sticker-card').count(),2);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await snap('favorites');report.checks.push({width,status:'PASS'});
}catch(e){report.checks.push({width,status:'FAIL',error:e.stack});await snap('failure');}finally{await ctx.close();}}
})().catch(e=>report.errors.push(e.stack)).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exitCode=report.errors.length||report.checks.some(c=>c.status==='FAIL')?1:0;});
