const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),sharp=require('/Users/song/Documents/拾页/node_modules/sharp');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='/Users/song/Documents/拾页',css=fs.readFileSync(path.join(root,'shiye-editorial-prototype/styles.css'),'utf8'),marker='/* Warm study UI — paint only.',split=css.indexOf(marker),oldCSS=css.slice(0,split),warmCSS=css.slice(split),checks=[],errors=[];let browser,server,p;
assert.ok(split>0);
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-warm-check-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'warm-test-user',password:'warm-fixture-only-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.route('**/styles.css',r=>r.fulfill({contentType:'text/css',body:css}));await context.addInitScript(()=>sessionStorage.setItem('shiye-auth-landing','shelf'));await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'warm-test-user',password:'warm-fixture-only-123'}});
 p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>state&&db&&currentIdentity?.accountId);await p.evaluate(()=>{const style=document.createElement('style');style.id='warm-comparison';document.head.append(style);const demo=seed();state.books=demo.books;state.assets=builtin.map(a=>({...a,favorite:true}));activeBookId=state.books[0].id;state.books[0].coverDesign=defaultCoverDesign(state.books[0]);currentView='shelf';render();});


const out=root+'/verification/specular-buttons-20260911/';
const button=p.locator('[data-action="new-book"]').first();await p.waitForTimeout(300);
assert.equal(await button.locator('.specular-rim').count(),1);
assert.equal(await p.locator('.icon-button.specular-button,input.specular-button,.chip.specular-button').count(),0);
const geometry=await button.boundingBox(),paint=await button.evaluate(e=>{const s=getComputedStyle(e);return [s.color,s.backgroundColor,s.fontSize,s.borderRadius,s.padding]});
await p.evaluate(()=>document.querySelector('link[href="/specular-buttons.css"]').disabled=true);assert.deepEqual(await button.boundingBox(),geometry);assert.deepEqual(await button.evaluate(e=>{const s=getComputedStyle(e);return [s.color,s.backgroundColor,s.fontSize,s.borderRadius,s.padding]}),paint);await p.evaluate(()=>document.querySelector('link[href="/specular-buttons.css"]').disabled=false);
console.log('PASS original geometry / color / typography; major buttons only');
await button.hover();await p.waitForTimeout(1000);assert.ok(await button.locator('.specular-rim').evaluate(e=>Number(getComputedStyle(e).opacity))>.9);const angle1=await button.locator('.specular-rim').evaluate(e=>e.style.getPropertyValue('--specular-angle'));await button.screenshot({path:out+'hover.png'});
await p.mouse.move(geometry.x-80,geometry.y+80);await p.waitForTimeout(800);const angle2=await button.locator('.specular-rim').evaluate(e=>e.style.getPropertyValue('--specular-angle'));assert.notEqual(angle1,angle2);assert.ok(await button.locator('.specular-rim').evaluate(e=>Number(getComputedStyle(e).opacity))>0);
await p.mouse.move(0,900);await p.waitForTimeout(1200);assert.ok(await button.locator('.specular-rim').evaluate(e=>Number(getComputedStyle(e).opacity))<.01);await button.screenshot({path:out+'idle.png'});console.log('PASS proximity fade, directional paired rim, idle fade-out');
await button.evaluate(e=>e.disabled=true);await button.hover({force:true});await p.waitForTimeout(200);assert.equal(await button.locator('.specular-rim').evaluate(e=>getComputedStyle(e).opacity),'0');await button.evaluate(e=>e.disabled=false);
await button.click();await p.locator('#new-title').fill('高光按钮验证');const create=p.locator('[data-action="create-book"]');await p.waitForTimeout(200);assert.equal(await create.locator('.specular-rim').count(),1);await create.click();await p.waitForTimeout(250);assert.equal(await p.locator('#book-title').inputValue(),'高光按钮验证');assert.equal(await p.locator('#book-title .specular-rim').count(),0);console.log('PASS disabled button, dynamic dialog, input and create action');
await p.emulateMedia({reducedMotion:'reduce'});const back=p.locator('[data-action="shelve"]').last();await back.hover();assert.equal(await back.locator('.specular-rim').evaluate(e=>getComputedStyle(e).display),'none');console.log('PASS reduced-motion fallback');await p.emulateMedia({reducedMotion:'no-preference'});
await p.evaluate(()=>{currentView='shelf';render();});for(const width of [800,390]){await p.setViewportSize({width,height:900});await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'shelf-'+width+'.png'});}console.log('PASS half-screen and mobile overflow checks');
await p.setViewportSize({width:1440,height:1000});await p.goto(base+'/admin');await p.waitForTimeout(500);assert.ok(await p.locator('button.primary .specular-rim').count()>0);assert.equal((await p.request.get(base+'/specular-buttons.js')).status(),200);assert.equal((await p.request.get(base+'/specular-buttons.css')).status(),200);console.log('PASS admin login primary button and public resources');
// Use a small same-origin entry fixture to verify the room's actual CSS / selectors without loading 3D assets.
await p.route('**/specular-room-fixture',r=>r.fulfill({contentType:'text/html',body:'<html><head><link rel="stylesheet" href="/room-home/assets/index-BylXNHBx.css"><link rel="stylesheet" href="/room-home/integration.css"><link rel="stylesheet" href="/specular-buttons.css"></head><body><button class="preloader__btn preloader__btn--primary">进入房间 · 有音乐</button><button class="preloader__btn preloader__btn--secondary">安静地进入</button><script src="/specular-buttons.js"></script></body></html>'}));await p.goto(base+'/specular-room-fixture');await p.waitForTimeout(300);assert.equal(await p.locator('.preloader__btn .specular-rim').count(),2);console.log('PASS room entrance button CSS fixture (not full 3D scene)');
await p.keyboard.press('Tab');assert.equal(await p.locator('.preloader__btn:focus-visible').count(),1);assert.equal(await p.locator('.preloader__btn:focus-visible .specular-rim').evaluate(e=>getComputedStyle(e).opacity),'0.85');console.log('PASS keyboard focus feedback');
await p.evaluate(()=>{const b=document.createElement('button');b.className='room-account';b.textContent='登录/注册';document.body.append(b);});await p.waitForTimeout(100);assert.equal(await p.locator('.room-account .specular-rim').count(),1);await p.evaluate(()=>{document.querySelector('.room-account').classList.add('is-account');});await p.waitForTimeout(100);assert.equal(await p.locator('.room-account .specular-rim').count(),0);console.log('PASS account avatar excluded after login');
assert.deepEqual(errors,[]);console.log('PASS no page errors');
})().catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
