const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);let server,browser;const report=[];
(async()=>{const {createApp}=await import(path.join(root,'dist/server/app.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js'));const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-access-ui-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config),{mode:0o600});const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),access:new InviteAccess(file)});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [1440,390,320]){const c=await browser.newContext({viewport:{width,height:900},isMobile:width<500,hasTouch:width<500}),p=await c.newPage(),errors=[],posts=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST')posts.push(new URL(r.url()).pathname);});p.setDefaultTimeout(10000);await c.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const A=a=>p.locator(`[data-action="${a}"]`).first();try{
await p.goto(base,{waitUntil:'networkidle'});await A('access-open').click();await p.locator('#invite-form').waitFor();assert.equal(await p.locator('.books-grid').count(),0);await p.screenshot({path:path.join(out,'invite-'+width+'.png')});await p.locator('[data-action="access-tab"][data-value="phone"]').click();assert.equal(await p.locator('.access-phone input:enabled').count(),0);assert.equal(await p.locator('.access-phone button:enabled').count(),0);await p.screenshot({path:path.join(out,'phone-closed-'+width+'.png')});assert.equal(posts.length,0);await p.keyboard.press('Escape');await A('home-create-sticker').click();await p.locator('#invite-form').waitFor();
await p.locator('#invite-code').fill('NOT-A-VALID-INVITE');await p.locator('#invite-code').press('Enter');await p.waitForFunction(()=>document.querySelector('#access-error')?.textContent.includes('无效'));assert.equal(await p.locator('.books-grid').count(),0);assert.equal(await p.locator('.access-submit').isEnabled(),true);
await p.locator('#invite-code').fill(batch.codes[0]);await p.locator('#invite-code').press('Enter');await p.locator('.books-grid').waitFor();assert.equal(posts.filter(x=>x==='/api/access/invite/verify').length,2);assert.equal(await p.evaluate(()=>state.books.length),3);
await p.reload({waitUntil:'networkidle'});await A('home-create-sticker').click();await p.locator('.books-grid').waitFor();assert.equal(await p.locator('#dialog[open]').count(),0);await p.locator('[data-shelf-create-sticker]').click();await A('seg-open').click();await p.locator('.seg-notice').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);assert.deepEqual(errors,[]);report.push({width,status:'PASS'});
}catch(e){report.push({width,status:'FAIL',error:e.stack});await p.screenshot({path:path.join(out,'failure-'+width+'.png')});}finally{await c.close();}}
})().catch(e=>report.push({fatal:e.stack})).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.some(r=>r.status==='FAIL'||r.fatal))process.exitCode=1;});
