const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,process.argv[2]||'run-01');fs.mkdirSync(out);const report={checks:[],errors:[],external:[],writes:[]};let browser;
const a=(p,n)=>p.locator(`[data-action="${n}"]`).first();
async function flow(name,fn,width=1440){const c=await browser.newContext({viewport:{width,height:1000}}),p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>report.errors.push(e.message));await c.route('**/*',r=>{const q=r.request();if(new URL(q.url()).origin!=='http://127.0.0.1:4176'){report.external.push(q.url());return r.abort();}if(q.method()!=='GET'){report.writes.push(q.method());return r.abort();}return r.continue();});try{await p.goto('http://127.0.0.1:4176',{waitUntil:'networkidle'});await fn(p);report.checks.push({name,status:'PASS'});}catch(e){report.checks.push({name,status:'FAIL',error:e.message});await p.screenshot({path:path.join(out,name+'-failure.png'),fullPage:true});}finally{await c.close();}}
async function enter(p){await a(p,'home-create-sticker').click();const above=await p.evaluate(()=>document.querySelector('.workshop-back').getBoundingClientRect().bottom<=document.querySelector('.page-heading h1').getBoundingClientRect().top);assert.equal(above,true);}
(async()=>{browser=await chromium.launch({channel:'chrome',headless:true});
await flow('local-steps-and-resume-without-refresh',async p=>{
 await enter(p);await a(p,'workshop-back').click();await a(p,'home-create-sticker').waitFor();await enter(p);await p.locator('#photo-input').setInputFiles(path.resolve(__dirname,'../../shiye-editorial-prototype/assets/coffee.jpg'));await p.waitForFunction(()=>document.querySelector('#crop-source')?.naturalWidth>0);
 await p.locator('.edge-selection-tools [data-value="rect"]').click();await p.locator('#crop-stage').scrollIntoViewIfNeeded();const g=await p.evaluate(()=>{const g=cropGeometry();return{x:g.rect.left+g.left,y:g.rect.top+g.top,w:g.width,h:g.height};});await p.mouse.move(g.x+g.w*.35,g.y+g.h*.115);await p.mouse.down();await p.mouse.move(g.x+g.w*.62,g.y+g.h*.465,{steps:8});await p.mouse.up();await p.waitForFunction(()=>document.querySelector('.edge-mask')&&!document.querySelector('[data-action="edge-confirm"]').disabled,null,{timeout:25000});
 const photo=await p.evaluate(()=>workshop.source),crops=await p.evaluate(()=>JSON.stringify(workshop.crops.map(({edgeAssetId,...region})=>region))),mask=await p.locator('.edge-mask').getAttribute('src');await a(p,'edge-confirm').click();await p.locator('#sticker-preview').waitFor();await a(p,'workshop-back').click();await p.locator('#crop-stage').waitFor();assert.equal(await p.locator('.edge-mask').getAttribute('src'),mask);
 await a(p,'workshop-back').click();await p.locator('#upload-zone').waitFor();await a(p,'workshop-back').click();await enter(p);await a(p,'workshop-resume').click();await p.locator('#crop-stage').waitFor();assert.equal(await p.evaluate(()=>workshop.source),photo);assert.equal(await p.evaluate(()=>JSON.stringify(workshop.crops.map(({edgeAssetId,...region})=>region))),crops);assert.equal(await p.evaluate(()=>state.assets.length),0);await p.screenshot({path:path.join(out,'desktop-return.png'),fullPage:true});
});
await flow('return-to-original-editor-and-collection',async p=>{
 await a(p,'new-book').click();await p.locator('#new-title').fill('返回入口检查');await a(p,'create-book').click();await p.waitForFunction(()=>currentView==='editor'&&saveStatus==='已保存到本机');const original=await p.evaluate(()=>JSON.stringify(currentBook()));await a(p,'workshop-from-editor').click();await a(p,'workshop-back').click();await p.locator('#canvas-page').waitFor();assert.equal(await p.evaluate(()=>editing),true);assert.equal(await p.evaluate(()=>JSON.stringify(currentBook())),original);
 await a(p,'shelve').click();await p.locator('[data-action="nav"][data-view="collection"]').click();await p.locator('[data-action="nav"][data-view="workshop"]').first().click();await a(p,'workshop-back').click();assert.equal(await p.evaluate(()=>currentView),'collection');
});
await flow('mobile-and-baidu-entry-return',async p=>{
 await enter(p);await a(p,'seg-open').click();await p.waitForFunction(()=>segmentedWorkshop.active&&!segmentedWorkshop.busy);assert.equal(await a(p,'workshop-back').isVisible(),true);await a(p,'workshop-back').click();await p.locator('#upload-zone').waitFor();assert.equal(await p.evaluate(()=>segmentedWorkshop.active),false);
 await a(p,'sample').click();await a(p,'generate').click();await p.locator('#sticker-preview').waitFor();await a(p,'workshop-back').click();await p.locator('.sample-scene').waitFor();await a(p,'workshop-back').click();await p.locator('#upload-zone').waitFor();assert.equal(await a(p,'workshop-resume').isVisible(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);await p.screenshot({path:path.join(out,'mobile-return.png'),fullPage:true});
},390);
assert.deepEqual(report.errors,[]);assert.deepEqual(report.external,[]);assert.deepEqual(report.writes,[]);
})().catch(e=>{report.fatal=e.message;}).finally(async()=>{await browser?.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exitCode=report.fatal||report.checks.some(c=>c.status==='FAIL')?1:0;});
