const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();



 await p.evaluate(async()=>{currentBook().pages[0].elements=samplePage('lake').elements;currentBook().pages[1].elements=samplePage('coffee').elements;dirty();await saveNow();renderEditor();});await p.evaluate(async()=>{await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});
 const frame=await p.locator('.page-frame').boundingBox();
 await p.evaluate(()=>{window.sourceCanvas=$('#canvas-page');window.savedGet=ShiyePageTextures.get;window.preparationGate=new Promise(r=>window.releasePreparation=r);ShiyePageTextures.get=async(...args)=>{await preparationGate;return savedGet(...args);};});
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>editingPageTurn?.front);await p.waitForTimeout(60);
 assert.equal(await p.evaluate(()=>$('#canvas-page')===sourceCanvas),true);assert.equal(await p.locator('.single-turn-viewport').evaluate(e=>getComputedStyle(e).visibility),'hidden');assert.deepEqual(await p.locator('.page-frame').boundingBox(),frame);checks.push('Preparation keeps the original page visible at its original size');
 await p.evaluate(()=>{releasePreparation();ShiyePageTextures.get=savedGet;});await p.waitForFunction(()=>editingPageTurn?.activated);await p.evaluate(()=>{cancelAnimationFrame(editingPageFrame);window.testTurn=editingPageTurn;window.targetImages=[...testTurn.targetCanvas.querySelectorAll('.element img')];drawSideTurn(testTurn,.85);});
 await p.evaluate(()=>drawSideTurn(testTurn,.25));await p.screenshot({path:path.join(__dirname,'single-lifting.png')});await p.evaluate(()=>drawSideTurn(testTurn,.85));
 assert.equal(await p.locator('.single-turn-viewport').evaluate(e=>getComputedStyle(e).overflow),'hidden');assert.deepEqual(await p.locator('.single-turn-viewport').boundingBox(),frame);await p.screenshot({path:path.join(__dirname,'single-forward.png')});checks.push('Forward turn is clipped to the single-page viewport without an extra spread');
 await p.evaluate(()=>{cancelEditingTurn();});assert.equal(await p.evaluate(()=>$('#canvas-page')===sourceCanvas),true);assert.equal(await p.evaluate(()=>currentBook().page),0);assert.equal(await p.locator('.page-frame').getAttribute('inert'),null);checks.push('Cancelling an active turn restores the original DOM page and interactions');
 await p.evaluate(()=>{window.retainedImages=null;window.observeTurn=function(){if(editingPageTurn?.activated)retainedImages=[...editingPageTurn.targetCanvas.querySelectorAll('.element img')];if(currentBook().page===0)requestAnimationFrame(observeTurn);};requestAnimationFrame(observeTurn);});
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===1&&!editingPageTurn);
 const landed=await p.evaluate(()=>({animation:getComputedStyle($('#canvas-page')).animationName,opacity:getComputedStyle($('#canvas-page')).opacity,images:[...$('#canvas-page').querySelectorAll('.element img')].every((im,i)=>im===retainedImages[i]&&im.complete&&im.naturalWidth>0),overlays:$$('.single-turn-viewport,.editing-turn-layer').length}));assert.deepEqual(landed,{animation:'none',opacity:'1',images:true,overlays:0});checks.push('Landing has no secondary fade and reuses the decoded target image nodes');
 await p.locator('[data-action="drawer"][data-value="text"]').click();const openFrame=await p.locator('.page-frame').boundingBox();await p.locator('[data-action="page-prev"]').click();await p.waitForFunction(()=>editingPageTurn?.activated);await p.evaluate(()=>{cancelAnimationFrame(editingPageFrame);drawSideTurn(editingPageTurn,.8);});await p.screenshot({path:path.join(__dirname,'single-reverse-panel.png')});assert.deepEqual(await p.locator('.page-frame').boundingBox(),openFrame);await p.evaluate(()=>cancelEditingTurn());assert.equal(await p.evaluate(()=>currentBook().page),1);
 await p.locator('[data-action="page-prev"]').click();await p.waitForFunction(()=>currentBook().page===0&&!editingPageTurn);assert.equal(await p.locator('.editor-tools-panel').count(),1);assert.equal(await p.locator('#canvas-page').evaluate(e=>getComputedStyle(e).animationName),'none');checks.push('Reverse navigation preserves an explicitly open tool panel and stable book geometry');
 await p.locator('[data-action="close-drawer"]').click();await p.locator('#canvas-page .element.text').first().dblclick();await p.locator('[data-element-command="edit"]').click();await p.locator('.inline-text-input').fill('单页翻完仍能编辑');await p.locator('.inline-text-input').press('Escape');assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'单页翻完仍能编辑');checks.push('Inline text editing continues after the completed turn');
 await p.evaluate(()=>{window.realSave=saveNow;saveNow=async()=>false;});await p.locator('[data-action="page-next"]').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>currentBook().page),0);assert.equal(await p.locator('.single-turn-viewport').count(),0);await p.evaluate(()=>saveNow=realSave);checks.push('Save failure keeps the current page and creates no turn overlay');
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>editingPageTurn?.activated);await p.setViewportSize({width:1300,height:900});await p.waitForFunction(()=>!editingPageTurn);assert.equal(await p.evaluate(()=>currentBook().page),0);assert.equal(await p.locator('.single-turn-viewport').count(),0);assert.equal(await p.locator('.page-frame').getAttribute('inert'),null);checks.push('Resizing during a turn restores the current page without a stuck overlay');
 await p.setViewportSize({width:390,height:844});await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===1&&!editingPageTurn);assert.equal(await p.locator('#canvas-page').evaluate(e=>getComputedStyle(e).animationName),'none');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(__dirname,'mobile-landed.png')});checks.push('Mobile single-page turn ends without a fade or horizontal page overflow');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
