const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-editor-tools-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();

 const rect=()=>p.locator('.page-frame').boundingBox();
 const same=(a,b)=>{for(const key of ['x','y','width','height'])assert.ok(Math.abs(a[key]-b[key])<1,`${key}: ${a[key]} -> ${b[key]}`);};
 const tool=async name=>{await p.locator(`[data-action="drawer"][data-value="${name}"]`).click();await p.waitForTimeout(80);};
 const initial=await rect();
 for(const name of ['sticker','text','paper','pages']){await tool(name);same(initial,await rect());const rail=await p.locator('.editor-tools-panel').boundingBox();assert.ok(rail.x>=initial.x+initial.width);assert.ok(rail.width>=340);}
 checks.push('Desktop tools reserve 340–380px at the right; all four tabs leave the book position and scale unchanged');
 await p.screenshot({path:path.join(__dirname,'desktop-pages.png')});
 await tool('sticker');assert.ok((await p.locator('.drawer .sticker-display').first().boundingBox()).width>120);await p.locator('.editor-tools-content').evaluate(e=>e.scrollTop=200);same(initial,await rect());await p.screenshot({path:path.join(__dirname,'desktop-stickers.png')});
 const beforeDrag=await p.evaluate(()=>currentPage().elements.length),target=await rect(),source=await p.locator('.drawer [data-action="insert-sticker"]').first().boundingBox();
 await p.mouse.move(source.x+source.width/2,source.y+source.height/2);await p.mouse.down();await p.mouse.move(target.x+target.width/2,target.y+target.height/2,{steps:15});await p.mouse.up();assert.equal(await p.evaluate(()=>currentPage().elements.length),beforeDrag+1);same(initial,await rect());await p.locator('[data-action="undo"]').first().click();checks.push('Dragging a sticker from the right rail onto the book still works and supports undo');

 await tool('paper');assert.ok((await p.locator('.paper-preview').first().boundingBox()).height>=150);await p.locator('[data-action="paper"]').first().click();same(initial,await rect());checks.push('Larger sticker and paper thumbnails; independent scroll and paper application do not move the preview');
 await tool('text');assert.equal(await p.locator('.text-font-preview').count(),0);await p.locator('#new-text-size').fill('28');await p.locator('#new-text-size').dispatchEvent('change');same(initial,await rect());
 await p.locator('#canvas-page [data-element="text"]').click();assert.equal(await p.locator('.context-toolbar').count(),1);assert.equal(await p.locator('#drawer-text-size').count(),1);assert.equal(await p.locator('#selected-text-size').count(),0);assert.equal(await p.locator('.editor-tools-panel .context-toolbar').count(),1);
 await p.locator('#drawer-text-size').fill('35');await p.locator('#drawer-text-size').dispatchEvent('change');same(initial,await rect());await p.locator('#drawer-text-bold').uncheck();same(initial,await rect());assert.equal(await p.evaluate(()=>currentElement().bold),false);assert.equal(await p.evaluate(()=>currentElement().size),35);await p.screenshot({path:path.join(__dirname,'desktop-text.png')});checks.push('One inspector within the rail, no duplicate text fields; font size and bold edits preserve the book frame');
 await p.locator('#canvas-page [data-element="text"]').dblclick();await p.locator('[data-element-command="edit"]').click();await p.locator('.inline-text-input').fill('右侧工具区测试');await p.locator('.inline-text-input').press('Escape');assert.equal(await p.evaluate(()=>currentElement().text),'右侧工具区测试');same(initial,await rect());checks.push('Double-click menu and original inline input continue to work');
 await tool('sticker');await p.locator('.drawer [data-action="insert-sticker"]').first().click();assert.equal(await p.evaluate(()=>currentPage().elements.length),3);same(initial,await rect());assert.equal(await p.locator('.editor-tools-panel [data-action="delete-element"]').count(),1);checks.push('Adding a sticker opens its controls in the same rail and leaves the book fixed');
 await p.locator('[data-action="editor-layout"][data-value="spread"]').click();const spread=await rect();for(const name of ['text','paper','pages']){await tool(name);same(spread,await rect());}await p.screenshot({path:path.join(__dirname,'desktop-spread.png')});
 await p.locator('.page-list-preview[data-value="1"]').click();assert.equal(await p.evaluate(()=>currentBook().page),1);assert.equal(await p.locator('.edit-spread').count(),1);same(spread,await rect());checks.push('Page preview selection works inside the larger page list without changing double-page layout');checks.push('Double-page editing remains stable across tool switches');
 await p.locator('[data-action="editor-layout"][data-value="single"]').click();
 for(const width of [1024,768,390,320]){
  await p.setViewportSize({width,height:width===320?667:844});await p.waitForTimeout(100);
  await p.evaluate(()=>{drawer='text';selectedId=null;renderEditor();});await p.waitForTimeout(80);const opened=await rect();
  for(const name of ['sticker','paper','pages','text']){await tool(name);same(opened,await rect());}
  const rail=await p.locator('.editor-tools-panel').boundingBox();assert.ok(opened.x>=-1&&opened.x+opened.width<=width+1);if(width<=800)assert.ok(opened.y+opened.height<=rail.y+1,`preview overlaps rail at ${width}`);else assert.ok(opened.x+opened.width<=rail.x);
  assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`horizontal overflow at ${width}`);
  await p.locator('#new-text-size').fill('26');await p.locator('#new-text-size').dispatchEvent('change');same(opened,await rect());
  await p.locator('.editor-tools-content').evaluate(e=>e.scrollTop=0);await p.screenshot({path:path.join(__dirname,`tools-${width}.png`)});
  if(width<=800){await p.locator('[data-action="close-drawer"]').click();assert.ok(await p.locator('.editor-tools-panel').evaluate(e=>e.getBoundingClientRect().height<=1));}
 }
 checks.push('1024/768/390/320px layouts fit the viewport; narrow layouts use a non-overlapping, collapsible bottom panel with stable tab switching');
 await p.evaluate(()=>saveNow());await ready();await p.reload();await ready();assert.equal(await p.evaluate(()=>state.books[0].pages[0].elements.find(e=>e.id==='text').text),'右侧工具区测试');checks.push('Edited content persists through automatic sync and reload');assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
