const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const label=process.argv[2];if(!/^[a-z0-9-]+$/.test(label||''))throw Error('unique label required');const out=path.join(__dirname,label);fs.mkdirSync(out);
const src=path.resolve(__dirname,'../../shiye-editorial-prototype'),url='http://127.0.0.1:4176';
const report={checks:[],errors:[],hashes:{},screenshots:[],external:[]};let browser;
const ids=['plain','dots','grid','lines','cotton','watercolor','kraft','letter','botanical','postmark','collage','album',...JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json'),'utf8')).textures.map(t=>t.id)];
const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
const click=(p,a,v)=>A(p,a,v).click();
const shot=async(p,name,selector)=>{await (selector?p.locator(selector):p).screenshot({path:path.join(out,name+'.png')});report.screenshots.push(name+'.png');};
async function saved(p){await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');return p.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('shiye-concept-v1',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('data').objectStore('data').get('workspace');q.onsuccess=()=>{db.close();resolve(q.result)};};}));}
async function book(p,title){await click(p,'new-book');await p.locator('#new-title').fill(title);await click(p,'create-book');await p.locator('#canvas-page').waitFor();return (await saved(p)).books.find(b=>b.title===title).id;}
async function text(p,s){await click(p,'drawer','text');await click(p,'add-text');await p.locator('#text-content').fill(s);await click(p,'save-text');}
async function paper(p,id){if(!await p.locator('.paper-drawer').count())await click(p,'drawer','paper');await click(p,'paper',id);await p.locator('#canvas-page.'+id).waitFor();}
async function flow(name,fn,opts={}){const c=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',...opts}),p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>report.errors.push(e.message));await c.route('**/*',r=>new URL(r.request().url()).origin===url&&r.request().method()==='GET'?r.continue():(report.external.push(r.request().url()),r.abort()));try{await p.goto(url,{waitUntil:'networkidle'});await fn(p);report.checks.push({name,status:'PASS'});console.log('PASS',name);}catch(e){report.checks.push({name,status:'FAIL',error:e.stack});console.log('FAIL',name,e.message);await shot(p,name+'-failure');}finally{await c.close();}}
async function main(){for(const file of ['app.js','styles.css','index.html']){const bytes=fs.readFileSync(path.join(src,file)),r=await fetch(url+'/'+file);assert.equal(r.status,200);assert.ok(bytes.equals(Buffer.from(await r.arrayBuffer())));report.hashes[file]=crypto.createHash('sha256').update(bytes).digest('hex');}for(const t of JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json'),'utf8')).textures){const bytes=fs.readFileSync(path.resolve(__dirname,'../../',t.asset)),r=await fetch(url+'/assets/'+path.basename(t.asset));assert.equal(r.status,200);assert.ok(bytes.equals(Buffer.from(await r.arrayBuffer())));}
 browser=await chromium.launch({channel:'chrome',headless:true});
 await flow('all-24-content-undo-persistence',async p=>{
  const id=await book(p,'纸样验收');await text(p,'把日子，慢慢收好。');await click(p,'drawer','sticker');await A(p,'insert-sticker').click();await click(p,'page-add');await text(p,'第二页不变');await click(p,'page-goto','0');const before=(await saved(p)).books.find(b=>b.id===id);
  await click(p,'drawer','paper');assert.equal(await p.locator('.paper-choice').count(),24);await shot(p,'01-paper-panel');
  for(const v of ids){await paper(p,v);assert.equal(await A(p,'paper',v).getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.paper-choice[aria-pressed="true"]').count(),1);const b=(await saved(p)).books.find(b=>b.id===id);assert.equal(b.pages[0].paper,v);assert.deepEqual(b.pages[0].elements,before.pages[0].elements);assert.deepEqual(b.pages[1],before.pages[1]);assert.ok(await p.locator('.page-thumb[data-value="0"] .'+v).count());await shot(p,'paper-'+v,'#canvas-page');}
  await shot(p,'02-decorative-panel');await click(p,'undo');assert.ok(await p.locator('#canvas-page.texture-0526').count());await click(p,'redo');assert.ok(await p.locator('#canvas-page.texture-0527').count());await saved(p);
  await p.reload({waitUntil:'networkidle'});await p.locator('[data-action="nav"][data-view="shelf"]').click();await p.locator(`[data-action="open-book"][data-id="${id}"]`).click();await p.locator('.read-mode').waitFor();assert.ok(await p.locator('.reader-spread > .texture-0527').count());assert.deepEqual((await saved(p)).books.find(b=>b.id===id).pages[0].elements,before.pages[0].elements);
 });
 await flow('turn-front-back-and-read-only',async p=>{
  await book(p,'两面的纸');await text(p,'第一页');await paper(p,'texture-0444');await click(p,'page-add');await text(p,'第二页');await paper(p,'texture-0526');await click(p,'mode','read');await p.locator('.read-mode').waitFor();assert.equal(await p.locator('.paper-drawer').count(),0);
  await click(p,'page-prev');await p.locator('.reader-turn-layer .side-strip').first().waitFor();assert.ok(await p.locator('.side-front .texture-0526').count());assert.ok(await p.locator('.side-back .texture-0444').count());await p.waitForTimeout(500);await shot(p,'03-two-papers-turn');await p.waitForFunction(()=>!document.querySelector('.reader-turn-layer'));assert.ok(await p.locator('.reader-spread > .texture-0444').count());
 },{reducedMotion:'no-preference'});
 await flow('mobile-paper-selection',async p=>{
  await book(p,'手机选纸');await text(p,'手机纸样');for(const v of ids.filter(id=>id.startsWith('texture-')))await paper(p,v);await shot(p,'04-mobile-panel');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),390);await click(p,'close-drawer');await shot(p,'05-mobile-album');await click(p,'mode','read');await p.locator('.read-mode').waitFor();assert.ok(await p.locator('.reader-spread.single > .texture-0527').count());
 },{viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 await flow('save-failure-and-retry',async p=>{
  await book(p,'纸张保存失败');await text(p,'内容必须保留');const before=(await saved(p)).books.at(-1);await p.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('test quota','QuotaExceededError');};});await paper(p,'kraft');await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='保存失败，请重试');await click(p,'mode','read');assert.equal(await p.locator('.read-mode').count(),0);assert.ok(await p.locator('#canvas-page.kraft').count());assert.equal(await p.locator('#canvas-page .text-content').innerText(),'内容必须保留');await p.evaluate(()=>{IDBObjectStore.prototype.put=window.originalPut;});await click(p,'mode','read');await p.locator('.read-mode').waitFor();assert.ok((await saved(p)).books.some(b=>b.pages.some(p=>p.paper==='kraft')));
 });
}
main().catch(e=>{report.fatal=e.stack;console.error(e);}).finally(async()=>{await browser?.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,checks:report.checks,errors:report.errors,fatal:report.fatal}));process.exitCode=report.fatal||report.errors.length||report.checks.some(x=>x.status==='FAIL')?1:0;});
