'use strict';
function profileAvatar(){return currentIdentity?.avatar?`<img src="${esc(currentIdentity.avatar)}" alt="个人头像">`:esc((currentIdentity?.username||'S').slice(0,1));}
function reloadIdentity(view='home',setup=false){sessionStorage.setItem('shiye-auth-landing',view);if(setup)sessionStorage.setItem('shiye-account-setup','yes');location.reload();}
async function accountRequest(path='',body){return ShiyeAPI.json('/api/account'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});}
async function openAccountPanel(){
 try{
  const data=await accountRequest();
  if(!data.account){
   showDialog('设置账户',`<p class="muted">设置后，可以直接用用户名和密码登录。</p><form id="profile-register" class="account-private"><label class="field"><span>用户名</span><input name="username" autocomplete="username" required minlength="2" maxlength="32" placeholder="2～32 位文字、数字或 _ . -"></label><label class="field"><span>密码（至少 12 位）</span><input name="password" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><label class="field"><span>确认密码</span><input name="confirm" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><p class="account-error" role="alert"></p><button type="submit" class="button primary">保存账户并登录</button></form><div class="account-footer"><button data-action="close-dialog" class="text-link">暂时跳过</button><button data-action="account-switch" class="text-link">切换账号</button></div>`);
   bindProfileForm('#profile-register',async f=>{const values=Object.fromEntries(new FormData(f));if(values.password!==values.confirm)throw Error('两次输入的密码不一致。');if(!(await saveNow()))throw Error('请先保存本机作品。');await accountRequest('/register',{username:values.username,password:values.password});f.reset();identityChannel?.postMessage('changed');reloadIdentity('shelf');});return;
  }
  const a=data.account;
  showDialog('账户信息',`<div class="account-summary"><label class="account-avatar" aria-label="更换头像">${a.avatar?`<img src="${esc(a.avatar)}" alt="个人头像">`:`<span>${esc(a.username.slice(0,1))}</span>`}<input id="profile-avatar" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><div><strong>${esc(a.username)}</strong><p class="muted">${a.role==='admin'?'管理员':'个人账号'}</p><label for="profile-avatar" class="text-link">更换头像</label></div></div><p id="avatar-error" class="account-error" role="alert"></p><form id="profile-details" class="account-private"><label class="field"><span>用户名</span><input name="username" value="${esc(a.username)}" required minlength="2" maxlength="32" autocomplete="username"></label><label class="field"><span>修改用户名时验证当前密码</span><input name="currentPassword" type="password" maxlength="128" autocomplete="current-password"></label><p class="account-error" role="alert"></p><button class="button outline" type="submit">保存用户名</button></form><div class="account-footer"><button data-action="account-password" class="button outline">修改密码</button><button data-action="account-switch" class="button outline">切换账号</button><button data-action="account-logout" class="text-link">退出登录</button></div>`);
  bindProfileForm('#profile-details',async f=>{const updated=await accountRequest('/profile',Object.fromEntries(new FormData(f)));const heading=$('.account-summary strong');if(heading)heading.textContent=updated.account.username;f.querySelector('[type=password]').value='';await refreshIdentity();identityChannel?.postMessage('changed');toast('用户名已更新，下次使用新用户名登录');});
  $('#profile-avatar').onchange=async e=>{const input=e.currentTarget,file=input.files[0];if(!file)return;const error=$('#avatar-error');error.textContent='';input.disabled=true;try{if(file.size>2*1024*1024)throw Error('请选择 2 MB 以内的图片。');const avatar=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('图片无法读取。'));r.readAsDataURL(file);});await accountRequest('/profile',{avatar});await refreshIdentity();identityChannel?.postMessage('changed');if(error.isConnected&&$('#dialog').open)await openAccountPanel();}catch(err){error.textContent=err.message;}finally{input.disabled=false;input.value='';}};
 }catch(e){toast(e.message);}
}
function bindProfileForm(selector,submit){const f=$(selector);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]'),error=f.querySelector('.account-error');b.disabled=true;error.textContent='';try{await submit(f);}catch(err){error.textContent=err.message;}finally{b.disabled=false;}};}
function accountPasswordPanel(){
 showDialog('修改密码',`<form id="profile-password" class="account-private"><label class="field"><span>当前密码</span><input name="oldPassword" type="password" required maxlength="128" autocomplete="current-password"></label><label class="field"><span>新密码（至少 12 位）</span><input name="newPassword" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><label class="field"><span>确认新密码</span><input name="confirm" type="password" required maxlength="128" autocomplete="new-password"></label><p class="account-error" role="alert"></p><button type="submit" class="button primary">保存并重新登录</button></form>`);
 bindProfileForm('#profile-password',async f=>{const v=Object.fromEntries(new FormData(f));if(v.newPassword!==v.confirm)throw Error('两次输入的密码不一致。');if(!(await saveNow()))throw Error('请先完成本机保存。');await accountRequest('/password',{oldPassword:v.oldPassword,newPassword:v.newPassword});f.reset();identityChannel?.postMessage('changed');sessionStorage.setItem('shiye-open-account-login','yes');reloadIdentity();});
}
async function leaveAccount(switching){if(!(await saveNow()))return;await accountRequest('/logout',{});identityChannel?.postMessage('changed');if(switching)sessionStorage.setItem('shiye-open-account-login','yes');reloadIdentity();}
function localRecord(key){return new Promise((resolve,reject)=>{const r=db.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function accountOnboarding(){
 if(sessionStorage.getItem('shiye-open-account-login')){sessionStorage.removeItem('shiye-open-account-login');openAccess('shelf','account');return;}
 if(currentIdentity?.accountId&&workspaceFresh){
  const marker='import-choice:'+currentIdentity.accountId;if(await localRecord(marker))return;
  await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put('offered',marker);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});
  const guest=await localRecord('workspace');if(!guest)return;
  showDialog('归入本机作品？',`<p>本机访客空间有 ${guest.books.length} 本手账、${guest.assets.length} 个素材。是否归入当前账号？</p><p class="muted">归入后只在此账号下展示；选择保留时，继续留在访客空间。归入的作品将随当前账号自动同步。</p><p id="import-error" class="account-error" role="alert"></p>`,`<button class="button outline" data-action="close-dialog">保留在访客空间</button><button class="button primary" id="import-guest">归入当前账号</button>`);
  const choiceClosed=new Promise(resolve=>$('#dialog').addEventListener('close',resolve,{once:true}));
  $('#import-guest').onclick=async e=>{e.currentTarget.disabled=true;try{
   const auth=await fetch('/api/access/session',{cache:'no-store'}).then(r=>r.json());if(workspaceFor(auth)!==workspaceKey)throw Error('账号已切换，请重新登录后再操作。');
   await new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite'),store=tx.objectStore('data');let error;tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(error||tx.error);const g=store.get('workspace'),a=store.get(workspaceKey);let count=0;const done=()=>{if(++count!==2)return;try{if(!same(g.result,guest)||!same(a.result,savedWorkspace))throw Error('作品刚刚发生变化，请保留当前内容，稍后再整理。');store.put(guest,workspaceKey);store.put(seed(),'workspace');store.put(guest,workspaceKey+':import-backup');for(const asset of [...guest.assets,...(guest.archivedAssets||[])])if(asset.blobKey){const b=store.get(asset.blobKey);b.onsuccess=()=>{if(b.result)store.put(b.result,scopedBlobKey(asset.blobKey));};}}catch(err){error=err;tx.abort();}};g.onsuccess=a.onsuccess=done;});reloadIdentity('shelf');
  }catch(err){$('#import-error').textContent=err.message;const button=$('#import-guest');if(button)button.disabled=false;}};await choiceClosed;return;
 }
 if(sessionStorage.getItem('shiye-account-setup')){sessionStorage.removeItem('shiye-account-setup');if(currentIdentity?.authorized&&!currentIdentity.accountId)await openAccountPanel();}
}
document.addEventListener('click',async e=>{const action=e.target.closest('[data-action]')?.dataset.action;try{if(action==='account-open')await openAccountPanel();if(action==='account-password')accountPasswordPanel();if(action==='account-switch')await leaveAccount(true);if(action==='account-logout')await leaveAccount(false);if(action==='identity-retry')await refreshIdentity();}catch(err){toast(err.message);}});
document.addEventListener('DOMContentLoaded',()=>{$('#dialog').addEventListener('close',()=>{$$('.account-private input[type=password]').forEach(i=>i.value='');});});
