'use strict';
const app=document.querySelector('#admin-app'),dialog=document.querySelector('#admin-dialog');let current='overview',user='',version=0,items=[],apiItems=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'未记录';
const labels={unused:'未使用',used:'已有访问',unknown:'历史未记录',disabled:'已停用',bound:'已绑定',expired:'已过期'};
async function request(path,body){const r=await fetch('/api/admin'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw Error('服务暂不可用，请稍后重试。');}if(!r.ok){if(data.error?.errorType==='ADMIN_REQUIRED'){dialog.close();login();}throw Error(data.error?.message||'操作未完成，请重试。');}return data;}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),3500);}
function login(){user='';items=[];apiItems=[];version++;app.innerHTML=`<main class="login"><section class="login-card"><div class="wordmark">拾页<small>SHIYE · 管理工具</small></div><h1>管理员登录</h1><p class="muted">使用独立的管理员账号进入。</p><form id="login-form"><label><span>用户名</span><input name="username" autocomplete="username" required maxlength="32"></label><label><span>密码</span><input name="password" type="password" autocomplete="current-password" required maxlength="128"></label><p class="error" role="alert"></p><button class="primary" type="submit">登录管理工具</button></form><a href="/">← 返回拾页</a></section></main>`;document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;try{await request('/login',Object.fromEntries(new FormData(form)));form.reset();await start();}catch(err){form.querySelector('.error').textContent=err.message;}finally{button.disabled=false;}};}
function shell(body){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="wordmark">拾页<small>管理工具</small></div><nav>${[['overview','概览'],['apis','API 管理'],['invites','邀请码管理'],['audit','操作记录']].map(([id,name])=>`<button data-view="${id}" class="${current===id?'active':''}">${name}</button>`).join('')}</nav><a href="/">← 返回用户页面</a></aside><main class="main"><header class="topbar"><span>管理工具 / ${{overview:'概览',apis:'API 管理',invites:'邀请码管理',audit:'操作记录'}[current]}</span><div><span>${esc(user)}</span><button data-action="password">修改密码</button><button data-action="logout">退出</button></div></header><div id="view-content">${body}</div></main></div>`;}
const logRows=rows=>rows.length?rows.map(r=>`<div class="log"><small>${date(r.at)}</small><div>${esc(r.action)}<br><small>${esc(r.target)}</small></div><small>${esc(r.actor)}</small></div>`).join(''):'<p class="empty">暂无记录</p>';
function apiCards(rows){return `<div class="api-grid">${rows.map(r=>`<article class="api-card"><header><h3>${esc(r.name)}</h3><span class="badge ${r.enabled?'':'off'}">${r.enabled?'已启用':'未启用'}</span></header><p>供应商：${esc(r.provider)}</p><p class="endpoint">${esc(r.endpoint)}</p><p>API Key：${esc(r.apiKeyMasked)}<br>Secret Key：${r.secretConfigured?'已配置，内容隐藏':'未配置'}</p><p class="muted">最近鉴权测试：${date(r.testedAt)}<br>最近调用：${r.lastCall?`${date(r.lastCall.at)} · ${esc(r.lastCall.status)} ${esc(r.lastCall.error||'')}`:'管理功能启用后尚无记录'}</p><button data-action="api-edit" data-kind="${r.kind}">编辑配置</button></article>`).join('')}</div>`;}
async function load(view=current){current=view;const task=++version;shell('<p class="loading">正在读取…</p>');try{let body='';if(view==='overview'){const d=await request('/overview');apiItems=d.apis;body=`<div class="heading"><div><h1>管理概览</h1><p class="muted">查看接口和邀请访问的当前状态。</p></div></div><div class="stats">${[['累计创建',d.total],['未使用',d.counts.unused],['已有访问',d.counts.used],['历史未记录',d.counts.unknown],['已停用',d.counts.disabled],['已过期 / 已绑定',d.counts.expired+' / '+d.counts.bound]].map(([name,count])=>`<div class="stat"><span class="muted">${name}</span><strong>${count}</strong></div>`).join('')}</div>${apiCards(d.apis)}<section class="panel"><h3>最近操作</h3>${logRows(d.recent)}</section>`;}
if(view==='apis'){const d=await request('/apis');apiItems=d.items;body=`<div class="heading"><div><h1>API 管理</h1><p class="muted">独立管理抠图与名称识别配置。</p></div></div>${apiCards(d.items)}<p class="muted">当前支持百度接口。其他供应商需要完成适配后才能切换。</p>`;}
if(view==='invites'){const d=await request('/invites');items=d.items;body=`<div class="heading"><div><h1>邀请码管理</h1><p class="muted">共 ${items.length} 个邀请码 · 停用会同时撤销已有邀请访问资格。</p></div><button class="primary" data-action="invite-create">＋ 创建邀请码</button></div><div class="toolbar"><input id="invite-search" aria-label="搜索邀请码" placeholder="搜索批次、备注或编号"><select id="invite-status" aria-label="筛选状态"><option value="">全部状态</option>${Object.entries(labels).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><button data-action="invite-export">导出当前结果</button></div><div id="invite-table">${inviteTable(items)}</div><p class="muted">历史邀请码从管理功能启用后开始记录使用；早期访问次数无法补回。</p>`;}
if(view==='audit'){const d=await request('/audit');body=`<div class="heading"><div><h1>操作记录</h1><p class="muted">按时间倒序展示最近 1000 条管理操作。</p></div><button data-view="audit">刷新</button></div><div class="panel">${logRows(d.items)}</div>`;}
if(task===version)shell(body);
}catch(e){if(task===version)shell(`<p class="error">${esc(e.message)}</p><button data-view="${view}">重试</button>`);}}
function filtered(){const q=document.querySelector('#invite-search')?.value.trim()||'',state=document.querySelector('#invite-status')?.value||'';return items.filter(r=>(!state||r.state===state)&&(!q||[r.id,r.batch,r.note,r.codeMasked].some(v=>v?.includes(q))));}
function inviteTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>邀请码 / 编号</th><th>批次 / 备注</th><th>创建 / 有效期</th><th>状态</th><th>使用记录</th><th>操作</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="code"><span id="code-${r.id}">${esc(r.codeMasked)}</span><small>${esc(r.id.slice(0,8))}</small></td><td>${esc(r.batch)}<small>${esc(r.note)}</small></td><td>${date(r.createdAt)}<small>${r.expiresAt?date(r.expiresAt):'长期有效'}</small></td><td><span class="badge ${['disabled','expired','bound'].includes(r.state)?'off':''}">${labels[r.state]}</span></td><td>${r.useCount} 次<small>首次：${date(r.firstUsedAt)}<br>最近：${date(r.lastUsedAt)}</small></td><td class="actions"><button class="link" data-action="invite-reveal" data-id="${r.id}" ${r.canReveal?'':'disabled'}>查看</button><button class="link" data-action="invite-status" data-id="${r.id}" ${r.status==='bound'?'disabled':''}>${r.status==='disabled'?'恢复':'停用'}</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">没有符合条件的邀请码</p>';}
function modal(title,body){dialog.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button data-action="dialog-close" aria-label="关闭">×</button></div>${body}`;dialog.showModal();}
function formDialog(title,fields,submit,onSubmit){modal(title,`<form id="manage-form">${fields}<p class="error" role="alert"></p><div class="dialog-actions"><button type="button" data-action="dialog-close">取消</button><button class="primary" type="submit">${submit}</button></div></form>`);const form=dialog.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);form.querySelector('.error').textContent='';try{await onSubmit(form);dialog.close();await load();}catch(err){form.querySelector('.error').textContent=err.message;}finally{buttons.forEach(b=>b.disabled=false);}};}
function editApi(kind){const row=apiItems.find(r=>r.kind===kind);formDialog(`编辑${esc(row.name)}`,`<p class="muted">留空保留现有密钥。新配置需先通过鉴权测试。</p><label><span>供应商</span><select disabled><option>百度智能云</option></select></label><label><span>API Key（当前 ${esc(row.apiKeyMasked)}）</span><input name="apiKey" type="password" autocomplete="new-password" maxlength="512" placeholder="留空保留现有值"></label><label><span>Secret Key</span><input name="secretKey" type="password" autocomplete="new-password" maxlength="512" placeholder="留空保留现有值"></label><label class="check"><input name="enabled" type="checkbox" ${row.enabled?'checked':''}><span>启用此功能</span></label><p class="warning">鉴权测试只验证密钥，不执行抠图或名称识别；功能权限仍需实际调用确认。</p><button type="button" id="api-test">测试鉴权</button><p id="api-test-result" class="muted" role="status"></p>`,`保存配置`,async form=>{await request('/apis/'+kind,apiBody(form,row));toast('配置已保存');});dialog.querySelector('#api-test').onclick=async e=>{const button=e.currentTarget;button.disabled=true;const result=dialog.querySelector('#api-test-result');try{const r=await request('/apis/'+kind+'/test',apiBody(dialog.querySelector('form'),row));result.textContent=r.message;}catch(err){result.textContent=err.message;}finally{button.disabled=false;}};}
function apiBody(form,row){const f=new FormData(form);return {apiKey:f.get('apiKey'),secretKey:f.get('secretKey'),enabled:f.get('enabled')==='on',revision:row.revision};}
document.addEventListener('input',e=>{if(e.target.id==='invite-search')document.querySelector('#invite-table').innerHTML=inviteTable(filtered());});document.addEventListener('change',e=>{if(e.target.id==='invite-status')document.querySelector('#invite-table').innerHTML=inviteTable(filtered());});
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button||button.disabled)return;if(button.dataset.view){await load(button.dataset.view);return;}const a=button.dataset.action,id=button.dataset.id;try{
if(a==='dialog-close'){dialog.close();return;}
if(a==='logout'){await request('/logout',{});dialog.close();login();return;}
if(a==='api-edit'){editApi(button.dataset.kind);return;}
if(a==='password'){modal('修改管理员密码',`<form id="password-form"><label><span>原密码</span><input name="oldPassword" type="password" autocomplete="current-password" required maxlength="128"></label><label><span>新密码（至少 12 位）</span><input name="newPassword" type="password" autocomplete="new-password" required minlength="12" maxlength="128"></label><label><span>再次输入新密码</span><input name="confirm" type="password" autocomplete="new-password" required></label><p class="error"></p><button class="primary wide" type="submit">保存并重新登录</button></form>`);dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget,v=Object.fromEntries(new FormData(f)),b=f.querySelector('button');if(v.newPassword!==v.confirm){f.querySelector('.error').textContent='两次新密码不一致。';return;}b.disabled=true;try{await request('/password',{oldPassword:v.oldPassword,newPassword:v.newPassword});f.reset();dialog.close();login();toast('密码已修改，请重新登录');}catch(err){f.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};return;}
if(a==='invite-create'){formDialog('创建邀请码',`<label><span>批次名称</span><input name="batch" required maxlength="50" placeholder="例如：第一批内测"></label><label><span>数量（1～100）</span><input name="count" type="number" min="1" max="100" value="10" required></label><label><span>有效期（留空长期有效）</span><input name="expiry" type="datetime-local"></label><label><span>备注</span><textarea name="note" maxlength="200" rows="2"></textarea></label>`,`创建`,async form=>{const f=new FormData(form);const r=await request('/invites',{count:Number(f.get('count')),batch:f.get('batch'),note:f.get('note'),expiresAt:f.get('expiry')?new Date(f.get('expiry')).getTime():null});toast(`已创建 ${r.ids.length} 个邀请码`);});return;}
if(a==='invite-status'){const row=items.find(i=>i.id===id),disabled=row.status!=='disabled';formDialog(disabled?'停用邀请码？':'恢复邀请码？',`<p>${disabled?'该码及已签发的邀请访问资格将停止生效，已有作品保留。':'恢复后，未过期且未绑定的码可以继续使用。'}</p>`,disabled?'确认停用':'确认恢复',async()=>{await request('/invites/'+id+'/status',{disabled});toast(disabled?'已停用':'已恢复');});return;}
if(a==='invite-reveal'){const r=await request('/invites/reveal',{ids:[id]});const cell=document.getElementById('code-'+id);cell.textContent=r.items[0].code;cell.classList.add('revealed');button.disabled=true;return;}
if(a==='invite-export'){const rows=filtered().filter(r=>r.canReveal);if(!rows.length){toast('没有可导出的完整邀请码');return;}formDialog('导出当前邀请码',`<p>将导出当前筛选结果中的 ${rows.length} 个完整邀请码，请妥善保存文件。</p>`,'导出',async()=>{const lines=[];for(let i=0;i<rows.length;i+=1000){const r=await request('/invites/reveal',{ids:rows.slice(i,i+1000).map(r=>r.id)});lines.push(...r.items.map(r=>r.code));}const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='拾页邀请码-'+new Date().toISOString().slice(0,10)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('邀请码已导出');});return;}
}catch(err){toast(err.message);}});
dialog.addEventListener('close',()=>{dialog.innerHTML='';});
async function start(){try{const s=await request('/session');if(!s.authenticated){login();return;}user=s.username;await load();}catch(e){login();document.querySelector('.error').textContent=e.message;}}
start();
