const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),sharp=require('sharp');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),css=fs.readFileSync(path.join(root,'shiye-editorial-prototype/styles.css'),'utf8'),marker='/* Warm study UI — paint only.',split=css.indexOf(marker),oldCSS=css.slice(0,split),warmCSS=css.slice(split),checks=[],errors=[];let browser,server,p;
assert.ok(split>0);
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-warm-check-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'warm-test-user',password:'warm-fixture-only-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.route('**/styles.css',r=>r.fulfill({contentType:'text/css',body:oldCSS}));await context.addInitScript(()=>sessionStorage.setItem('shiye-auth-landing','shelf'));await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'warm-test-user',password:'warm-fixture-only-123'}});
 p=await context.newPage();p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>state&&db&&currentIdentity?.accountId);await p.evaluate(()=>{const style=document.createElement('style');style.id='warm-comparison';document.head.append(style);const demo=seed();state.books=demo.books;state.assets=builtin.map(a=>({...a,favorite:true}));activeBookId=state.books[0].id;state.books[0].coverDesign=defaultCoverDesign(state.books[0]);currentView='shelf';render();});
 const shape=()=>p.evaluate(()=>{const selectors='main,.sidebar,.topbar,.editor-top,.workspace-meta,.layout-controls,.stage-wrap,.page-frame,.canvas-page,.editor-dock,.editor-tools-panel,.page-manager,.page-strip,.page-thumb,.book-item,.book-open,.sticker-card,.sticker-display,.chips,.chip,.button,.tool,input,select,textarea,.page-heading,.collection-header,dialog[open]';return [...document.querySelectorAll(selectors)].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,id:e.id,classes:e.className,action:e.dataset.action,box:[r.x,r.y,r.width,r.height].map(x=>Math.round(x*100)/100),font:[getComputedStyle(e).fontFamily,getComputedStyle(e).fontSize,getComputedStyle(e).fontWeight]};});});
 async function artwork(selector){const r=await p.locator(selector).first().boundingBox(),bottom=await p.evaluate(()=>{const side=document.querySelector('.sidebar')?.getBoundingClientRect();return side&&side.y>0?Math.min(innerHeight,side.y):innerHeight;});const y=Math.max(0,r.y)+8;return p.screenshot({style:'.page-arrow{visibility:hidden!important}',clip:{x:r.x+8,y,width:r.width-16,height:Math.min(r.y+r.height-8,bottom-1)-y}});}
 async function compare(name,setup,artSelector=null){
  await p.evaluate(()=>document.getElementById('warm-comparison').textContent='');await p.evaluate(setup);await p.mouse.move(0,0);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.page-frame img,.book-open img,.sticker-display img')].map(i=>i.decode().catch(()=>{})));});await p.waitForTimeout(250);
  const before=await shape(),stateBefore=await p.evaluate(()=>JSON.stringify(state.books)),artBefore=artSelector?await artwork(artSelector):null;
  await p.screenshot({path:path.join(__dirname,name+'-before.png')});await p.evaluate(css=>document.getElementById('warm-comparison').textContent=css,warmCSS);await p.waitForTimeout(250);const after=await shape();assert.equal(JSON.stringify(after),JSON.stringify(before),name+': geometry and typography unchanged');assert.equal(await p.evaluate(()=>JSON.stringify(state.books)),stateBefore,name+': book data unchanged');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name+': no overflow');
  let pixelMaxDelta=null;if(artSelector){const artAfter=await artwork(artSelector);if(!artAfter.equals(artBefore)){fs.writeFileSync(path.join(__dirname,'art-before.png'),artBefore);fs.writeFileSync(path.join(__dirname,'art-after.png'),artAfter);}const a=await sharp(artBefore).raw().toBuffer(),b=await sharp(artAfter).raw().toBuffer();assert.equal(a.length,b.length);pixelMaxDelta=0;for(let i=0;i<a.length;i++)pixelMaxDelta=Math.max(pixelMaxDelta,Math.abs(a[i]-b[i]));assert.ok(pixelMaxDelta<=1,name+': artwork differs beyond 1/255 rasterization tolerance: '+pixelMaxDelta);}
  await p.screenshot({path:path.join(__dirname,name+'-after.png')});checks.push({name,elements:before.length,geometry:'identical',typography:'identical',artwork:artSelector?'visible interior stable (1/255 tolerance)':'not-applicable',pixelMaxDelta});
 }
 for(const width of [1440,800,390]){
  await p.setViewportSize({width,height:width===1440?1000:900});
  await compare('shelf-'+width,()=>{currentView='shelf';render();},'.book-open .custom-cover');
  await compare('collection-'+width,()=>{currentView='collection';collectionTab='mine';filter='全部';search='';render();});
  await compare('workshop-'+width,()=>{currentView='workshop';render();});
  await compare('editor-'+width,()=>{currentView='editor';editing=true;coverEditingBookId=null;currentBook().editorLayout='single';drawer=null;selectedId=null;renderEditor();},'#canvas-page');
  for(const tool of ['text','sticker','paper','pages'])await compare(tool+'-'+width,new Function(`currentView='editor';editing=true;coverEditingBookId=null;drawer='${tool}';selectedId=null;renderEditor();`),'#canvas-page');
  await compare('cover-'+width,()=>{currentView='editor';editing=true;coverEditingBookId=activeBookId;drawer='cover';selectedId=null;renderEditor();},'#canvas-page');
 }
 await p.setViewportSize({width:1440,height:1000});await compare('spread-editor',()=>{coverEditingBookId=null;drawer=null;currentBook().editorLayout='spread';renderEditor();});await compare('reader',()=>{editing=false;readerCover=null;renderEditor();},'.reader-leaf');
 await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{currentView='collection';collectionTab='mine';render();});const sticker=p.locator('.sticker-display').first();await sticker.hover();await p.waitForTimeout(300);const transform=await sticker.locator('.sticker-preview-frame').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(transform,'none');await sticker.screenshot({path:path.join(__dirname,'sticker-hover.png')});checks.push({name:'existing sticker hover retained',transform});
 await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await sticker.locator('.sticker-preview-frame').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');checks.push({name:'reduced motion respected'});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks:checks.length,errors}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.message});if(p)await p.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({checks,errors},null,2));});
