const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;const originalFetch=global.fetch;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js')),{QWEN_COPY_ENDPOINT,QWEN_COPY_MODEL}=await import(path.join(root,'dist/server/copy-provider.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-qwen-ui-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'qwen-user',password:'fixture-password-123'});
 const sent=[];let fail=false;
 // Replace the isolated process's network transport. All model replies below are fixtures.
 global.fetch=async(url,options)=>{assert.equal(url,QWEN_COPY_ENDPOINT);const body=JSON.parse(options.body);sent.push(body);if(fail)return new Response('fixture-private-provider-error',{status:429});return new Response(JSON.stringify({id:'fixture-qwen-request',choices:[{finish_reason:'stop',message:{content:JSON.stringify({text:'今天在家读了几页书，把脚步放慢，也给自己留下一点安静。'})}}],usage:{prompt_tokens:2000,completion_tokens:200}}));};
 const {app,copy}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 const password=fs.readFileSync(path.join(dir,'receipt'),'utf8').match(/密码：(.+)/)[1];await context.request.post(base+'/api/admin/login',{headers:{origin:base},data:{username:'admin',password}});p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/admin');await p.locator('[data-view="apis"]').click();
 const edit=async()=>p.locator('[data-action="api-edit"][data-kind="copy"]').click();const submit=async()=>{await p.locator('#manage-form button[type="submit"]').click();await p.waitForFunction(()=>!document.querySelector('#admin-dialog').open);};
 await edit();assert.equal(await p.locator('[name="providerId"]').inputValue(),'qwen');assert.equal(await p.locator('[name="model"]').inputValue(),QWEN_COPY_MODEL);assert.equal(await p.locator('[name="inputRate"]').inputValue(),'0.2');assert.equal(await p.locator('[name="outputRate"]').inputValue(),'0.8');assert.equal(await p.locator('[name="enabled"]').isChecked(),false);await p.screenshot({path:path.join(__dirname,'admin-qwen.png')});
 await p.locator('[name="providerId"]').selectOption('ark');assert.equal(await p.locator('[name="model"]').inputValue(),'');await p.locator('[name="providerId"]').selectOption('qwen');assert.equal(await p.locator('[name="model"]').inputValue(),QWEN_COPY_MODEL);await submit();assert.equal(sent.length,0);checks.push('Fresh settings default to Qwen Beijing snapshot; switching updates defaults and draft Save does not call a model');
 await edit();await p.locator('[name="apiKey"]').fill('fixture-qwen-key');await p.locator('[name="approvedUntil"]').fill('2099-01-01T00:00');await p.locator('[name="enabled"]').check();await submit();assert.equal(sent.length,0);
 await p.reload();await p.locator('[data-view="apis"]').click();await edit();assert.equal(await p.locator('[name="apiKey"]').inputValue(),'');assert.equal(await p.locator('[name="enabled"]').isChecked(),true);await p.locator('[name="providerId"]').selectOption('ark');assert.equal(await p.locator('[name="enabled"]').isChecked(),false);await p.locator('#manage-form button[type="submit"]').click();await p.waitForFunction(()=>document.querySelector('#manage-form .error').textContent.includes('新'));assert.equal((await(await context.request.get(base+'/api/admin/apis')).json()).items.find(r=>r.kind==='copy').providerId,'qwen');await p.locator('[data-action="dialog-close"]').first().click();checks.push('Configured key is masked after reload; changing providers without a new key is rejected and preserves saved Qwen config');
 await p.setViewportSize({width:390,height:844});await edit();await p.screenshot({path:path.join(__dirname,'admin-qwen-mobile.png')});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('[data-action="dialog-close"]').first().click();await p.setViewportSize({width:1440,height:1000});checks.push('390px administrator configuration remains usable without horizontal overflow');
 await p.locator('[data-action="copy-prompt"]').click();await p.locator('#copy-prompt-text').fill('测试提示词：根据用户提供的事实写一小段自然记录。');await submit();
 await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'qwen-user',password:'fixture-password-123'}});assert.equal((await context.request.get(base+'/api/admin/apis')).status(),403);assert.equal((await context.request.post(base+'/api/admin/apis/copy',{headers:{origin:base},data:{providerId:'ark'}})).status(),403);checks.push('Ordinary users cannot read API configuration or change the provider');
 await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const book=seed().books[0];book.id='qwen-book';book.editorLayout='single';book.page=0;book.pages=[{id:'qwen-page',paper:'plain',elements:[{id:'text',type:'text',text:'今天在家读书。',font:'fangsong',direction:'vertical',size:30.5,color:'#556644',x:12,y:5,w:40,h:65,rotation:2},{id:'sticker',type:'sticker',assetId:builtin[3].id,x:60,y:30,w:35,rotation:0}]}];state.books=[book];dirty();await saveNow();openBook('qwen-book',true);selectedId='text';renderEditor();});await ready();
 await p.locator('[data-action="ai-copy-open"]').click();await p.locator('#ai-copy-generate:not([disabled])').waitFor();assert.equal(sent.length,0);await p.locator('[name="topic"]').fill('记录安静的周末');await p.locator('#ai-copy-generate').click();await p.locator('#ai-copy-preview').waitFor({state:'visible'});assert.equal(sent.length,1);assert.equal(sent[0].enable_thinking,false);assert.equal(sent[0].messages[0].content,'测试提示词：根据用户提供的事实写一小段自然记录。');assert.ok(sent[0].messages[1].content[1].image_url.url.startsWith('data:image/jpeg;base64,'));assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'今天在家读书。');await p.screenshot({path:path.join(__dirname,'qwen-fixture-preview.png')});checks.push('Explicit generation uses saved prompt and selected-page image via actual Qwen adapter with fixture transport; preview leaves the page unchanged');
 await p.locator('#ai-copy-apply').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);await ready();let e=await p.evaluate(()=>currentPage().elements[0]);assert.equal(e.aiSource.provider,'qwen');assert.equal(e.aiSource.model,QWEN_COPY_MODEL);assert.equal(e.size,30.5);assert.equal(e.direction,'vertical');assert.equal(e.font,'fangsong');
 await p.locator('[data-action="undo"]').first().click();assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'今天在家读书。');await p.locator('[data-action="redo"]').first().click();await p.evaluate(()=>saveNow());await ready();const workspace=await(await context.request.get(base+'/api/works/workspace')).json();assert.equal(workspace.content.books[0].pages[0].elements[0].aiSource.provider,'qwen');await p.reload();await ready();assert.equal(await p.evaluate(()=>state.books[0].pages[0].elements[0].aiSource.provider),'qwen');checks.push('Apply preserves font size and style; Qwen provenance survives undo, redo, account sync and reload');
 fail=true;await p.evaluate(()=>{sessionStorage.clear();openBook('qwen-book',true);selectedId='text';renderEditor();});await p.locator('[data-action="ai-copy-open"]').click();await p.locator('#ai-copy-generate:not([disabled])').waitFor();await p.locator('#ai-copy-generate').click();await p.waitForFunction(()=>document.querySelector('#ai-copy-error').textContent.includes('繁忙'));await copy.idle();assert.equal(sent.length,2);assert.equal((await copy.usage()).failed,1);assert.equal((await copy.usage()).succeeded,1);assert.equal((await copy.usage()).knownEstimatedYuan,0.00056);assert.equal((await(await context.request.get(base+'/api/ai/copy/status',{headers:{'x-shiye-copy-owner':await p.evaluate(()=>aiCopyOwner())}})).json()).used,1);assert.ok(!(await p.locator('body').innerText()).includes('fixture-private-provider-error'));checks.push('Supplier failure shows a safe error without retry or user-quota charge; usage and estimated cost remain correct');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png'),fullPage:true}).catch(()=>{});process.exitCode=1;}).finally(async()=>{global.fetch=originalFetch;await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
