const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();



 await p.evaluate(async()=>{currentBook().pages[0].elements=samplePage('lake').elements;currentBook().pages[1].elements=samplePage('coffee').elements;dirty();await saveNow();renderEditor();});
 async function inspectSingle(width,direction){
  await p.setViewportSize({width,height:width<600?844:1000});await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.evaluate(async direction=>{currentBook().page=direction>0?0:1;renderEditor();await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));},direction);
  const resting=await p.locator('.page-frame').boundingBox();await p.evaluate(direction=>turnEditingPage(direction),direction);await p.waitForFunction(()=>editingPageTurn?.activated);await p.evaluate(()=>{cancelAnimationFrame(editingPageFrame);window.testTurn=editingPageTurn;});
  for(const time of [240,650,1040,1320]){await p.evaluate(time=>drawSingleEditorTurn(testTurn,time),time);await p.screenshot({path:path.join(__dirname,`single-${width}-${direction}-${time}.png`)});if(time===1040){const target=await p.locator('.demo-fold-back-content').boundingBox();assert.ok(target.x>=0&&target.x+target.width<=width+1,'Landed page leaves viewport');}}
  const final=await p.locator('.demo-fold-back-content').boundingBox();for(const k of ['x','y','width','height'])assert.ok(Math.abs(final[k]-resting[k])<1,`Centering mismatch ${k}`);
  if(width<600)assert.ok(await p.evaluate(()=>testTurn.expandedScale<1));assert.equal(await p.evaluate(()=>testTurn.progress),1);assert.equal(await p.evaluate(()=>testTurn.phase),'centering');
  await p.evaluate(()=>cancelEditingTurn());assert.deepEqual(await p.locator('.page-frame').boundingBox(),resting);assert.equal(await p.locator('.single-turn-viewport').count(),0);assert.equal(await p.locator('#canvas-page').evaluate(e=>getComputedStyle(e).visibility),'visible');
  await p.locator(`[data-action="page-${direction>0?'next':'prev'}"]`).click();await p.waitForFunction(target=>currentBook().page===target&&!editingPageTurn,direction>0?1:0);assert.equal(await p.locator('#canvas-page').evaluate(e=>getComputedStyle(e).animationName),'none');for(const k of ['x','y','width','height'])assert.ok(Math.abs((await p.locator('.page-frame').boundingBox())[k]-resting[k])<1);
  checks.push(`Single ${width}px ${direction}: open, full turn, landed target, center, cancel, and natural completion`);
 }
 await inspectSingle(1440,1);await p.locator('[data-action="drawer"][data-value="text"]').click();const panel=await p.locator('.editor-tools-panel').boundingBox();await inspectSingle(1440,-1);assert.deepEqual(await p.locator('.editor-tools-panel').boundingBox(),panel);await p.locator('[data-action="close-drawer"]').click();await inspectSingle(390,1);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);console.error(await p?.evaluate(()=>({view:currentView,editing,layout:currentBook()?.editorLayout,page:currentBook()?.page,turn:editingPageTurn?{pending:editingPageTurn.pending,ready:editingPageTurn.ready,phase:editingPageTurn.phase}:null})));checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'single-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
