const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();



 await p.evaluate(async()=>{const b=currentBook();b.editorLayout='spread';b.pages[0].elements=samplePage('lake').elements;b.pages[1].elements=samplePage('lake').elements;b.pages[2].elements=samplePage('coffee').elements;b.pages[3].elements=samplePage('forest').elements;b.pages[2].paper='texture-0444';b.pages[3].paper='texture-0487';b.pages[2].elements.push({id:'spanning-flower',type:'sticker',assetId:'flower',spreadWith:'p3',x:88,y:45,w:30,rotation:0});dirty();await saveNow();renderEditor();});
 await p.evaluate(()=>{window.oldLeaves=$$('.edit-spread>.edit-leaf');window.realGet=ShiyePageTextures.get;window.waitGate=new Promise(r=>window.releaseGate=r);ShiyePageTextures.get=async(...args)=>{await waitGate;return realGet(...args);};});
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>editingPageTurn?.front);assert.equal(await p.evaluate(()=>oldLeaves.every(el=>el.isConnected)),true);assert.equal(await p.locator('.editing-turn-layer').evaluate(e=>getComputedStyle(e).visibility),'hidden');checks.push('Spread preparation retains both original pages until images and papers are ready');
 await p.evaluate(()=>{releaseGate();ShiyePageTextures.get=realGet;});await p.waitForFunction(()=>editingPageTurn?.activated);await p.evaluate(()=>{cancelAnimationFrame(editingPageFrame);drawSideTurn(editingPageTurn,.8);});await p.screenshot({path:path.join(__dirname,'spread-turn.png')});await p.evaluate(()=>cancelEditingTurn());assert.equal(await p.evaluate(()=>oldLeaves.every(el=>el.isConnected)),true);assert.equal(await p.locator('.editing-turn-layer').count(),0);checks.push('Cancelling a prepared spread restores both original leaf nodes');
 async function watchAndTurn(direction,target){await p.evaluate(()=>{window.retained=new Set();window.watch=()=>{const t=editingPageTurn;if(t?.spread&&t.activated){for(const root of [t.back.querySelector('.reader-leaf'),t.underPage])for(const img of root.querySelectorAll('.element img'))retained.add(img);}if(editingPageTurn||retained.size===0)requestAnimationFrame(watch);};requestAnimationFrame(watch);});await p.locator(`[data-action="page-${direction>0?'next':'prev'}"]`).click();await p.waitForFunction(target=>currentBook().page===target&&!editingPageTurn,target);const result=await p.evaluate(()=>({styles:$$('.edit-spread>.canvas-page').map(el=>({animation:getComputedStyle(el).animationName,opacity:getComputedStyle(el).opacity})),reused:$$('.edit-spread .element img').every(img=>retained.has(img)&&img.complete&&img.naturalWidth>0),count:$$('.edit-spread .element img').length}));assert.ok(result.reused);assert.ok(result.count>0);for(const item of result.styles)assert.deepEqual(item,{animation:'none',opacity:'1'});return result;}
 checks.push({check:'Forward spread landing reuses both pages of photos and stickers without a second fade',result:await watchAndTurn(1,2)});
 assert.equal(await p.locator('.edit-spread [data-element="spanning-flower"] img').count(),2);assert.equal(await p.locator('[data-edit-page="p2"]').evaluate(e=>e.classList.contains('texture-0444')),true);assert.equal(await p.locator('[data-edit-page="p3"]').evaluate(e=>e.classList.contains('texture-0487')),true);checks.push('Different paper styles and both halves of a spanning sticker survive landing');await p.screenshot({path:path.join(__dirname,'spread-landed.png')});
 await p.evaluate(async()=>{currentBook().pages[2].paperSpread={paper:'texture-star-heart-grid',side:'left'};currentBook().pages[3].paperSpread={paper:'texture-star-heart-grid',side:'right'};dirty();await saveNow();renderEditor();});await watchAndTurn(-1,0);await watchAndTurn(1,2);assert.equal(await p.locator('.edit-spread .spread-paper.texture-star-heart-grid').count(),2);assert.equal(await p.locator('.edit-spread [data-element="spanning-flower"] img').count(),2);checks.push('Changing to paper spanning both pages invalidates the old faces and survives reverse/forward turns');await p.screenshot({path:path.join(__dirname,'spread-paper-changed.png')});
 await p.locator('#canvas-page .element.text').first().dblclick();await p.locator('[data-element-command="edit"]').click();await p.locator('.inline-text-input').fill('双页翻完继续编辑');await p.locator('.inline-text-input').press('Escape');assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'双页翻完继续编辑');checks.push('Direct editing remains available after the paper and image handoff');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'spread-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
