// Replay Song's already-returned mask locally. Never contact Baidu.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict');const {pathToFileURL}=require('url');const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,'recorded-mountain');fs.mkdirSync(out);let browser,server,calls=0;const report={mode:'offline replay of already-returned mountain mask, no Baidu request',external:[],errors:[]};
(async()=>{
const prior=JSON.parse(fs.readFileSync(path.join(root,'verification/real-photo-acceptance-20260909/live-results.json')));const job=prior.jobs.find(j=>j.sample==='mountain'&&j.kind==='refine'),mask=fs.readFileSync(path.join(root,'.local/baidu-live-trial-20260908/media',job.candidates[0].maskRef+'.png'));
const {createApp}=await import(pathToFileURL(path.join(root,'dist/server/app.js')));
const service=await createApp({runtime:fs.mkdtempSync(path.join(os.tmpdir(),'shiye-recorded-retouch-')),staticRoot:path.join(root,'shiye-editorial-prototype'),mode:'live',ttl:600000,live:{approvedUntil:Date.now()+600000,maxCalls:1,provider:{segment:async()=>{calls++;return {mask,requestId:job.providerRequestId};}}}});
server=service.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));await ctx.route('**/*',r=>{if(new URL(r.request().url()).origin!==base){report.external.push(r.request().url());return r.abort();}return r.continue();});
const A=a=>p.locator(`[data-action="${a}"]`).first();await p.goto(base,{waitUntil:'networkidle'});await A('home-create-sticker').click();await A('seg-open').click();await p.locator('#seg-photo').setInputFiles('/Users/song/Pictures/桌面壁纸/山脉.jpg');await p.locator('#seg-consent').check();await A('seg-upload').click();await p.waitForFunction(()=>document.querySelectorAll('.seg-candidate').length===1&&!document.querySelector('[data-action="seg-confirm"]').disabled);await A('seg-retouch-open').click();await p.locator('#seg-retouch-canvas').waitFor();await p.screenshot({path:path.join(out,'before.png'),fullPage:true});
// Find a hole in the known right-hand shrub area and restore that original pixel.
const target=await p.locator('#seg-retouch-canvas').evaluate(c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;for(let y=Math.round(c.height*.5);y<c.height*.65;y++)for(let x=Math.round(c.width*.68);x<c.width*.78;x++)if(a[(y*c.width+x)*4+3]===0)return {x,y,width:c.width,height:c.height};throw Error('Expected shrub hole not found');});
await p.locator('#seg-retouch-size').fill('90');await p.locator('#seg-retouch-canvas').scrollIntoViewIfNeeded();const r=await p.locator('#seg-retouch-canvas').boundingBox();await p.mouse.click(r.x+target.x/target.width*r.width,r.y+target.y/target.height*r.height);await p.waitForTimeout(100);
const after=await p.locator('#seg-retouch-canvas').evaluate((c,t)=>[...c.getContext('2d').getImageData(t.x,t.y,1,1).data],target);assert.equal(after[3],255);report.restored={...target,alphaBefore:0,alphaAfter:after[3]};await p.screenshot({path:path.join(out,'restored.png'),fullPage:true});await A('seg-retouch-apply').click();await p.waitForFunction(()=>document.querySelector('[data-action="seg-retouch-open"]')?.textContent.includes('已修正'));await A('seg-confirm').click();await p.locator('#seg-sticker-preview').waitFor();await p.screenshot({path:path.join(out,'preview.png'),fullPage:true});assert.equal(calls,1);assert.deepEqual(report.external,[]);report.status='PASS';
})().catch(e=>{report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));report.recordedMaskReplays=calls;report.realBaiduRequests=0;fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));});
