const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(__dirname,process.argv[2]||'run-01');fs.mkdirSync(out);const results=[];let browser,server;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js')),{default:sharp}=await import(path.join(root,'node_modules/sharp/lib/index.js'));
 const avatar=await sharp({create:{width:100,height:100,channels:3,background:'#cc8866'}}).png().toBuffer();browser=await chromium.launch({channel:'chrome',headless:true});
 for(const width of [1440,390]){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-profile-ui-')),batch=generateInvites(3),file=path.join(dir,'invites.json'),receipt=path.join(dir,'receipt');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'test',secretKey:'test',cutout:false,naming:false},receipt);const adminPassword=fs.readFileSync(receipt,'utf8').match(/密码：(.+)/)[1];
  const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,contexts=[],errors=[];
  async function makePage(){const ctx=await browser.newContext({viewport:{width,height:1000},isMobile:width<500,hasTouch:width<500});contexts.push(ctx);await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());const p=await ctx.newPage();p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));return p;}
  let p;const password='ordinary-password-123';
  async function openProfile(){await p.locator('[data-action="account-open"]').click();await p.locator('#dialog[open]').waitFor();}
  async function newBook(title){await p.locator('[data-action="new-book"]').first().click();await p.locator('#new-title').fill(title);await p.locator('[data-action="create-book"]').click();await p.locator('[data-action="shelve"]').first().click();await p.locator('.shelf-grid, .book-grid').first().waitFor().catch(()=>p.locator('[data-action="new-book"]').first().waitFor());}
  async function invitation(code){await p.goto(base,{waitUntil:'networkidle'});await p.locator('[data-action="access-open"]').click();await p.locator('#invite-code').fill(code);await p.locator('#invite-form button').click();await p.locator('#profile-register').waitFor();}
  async function register(name){await p.locator('#profile-register [name="username"]').fill(name);await p.locator('#profile-register [name="password"]').fill(password);await p.locator('#profile-register [name="confirm"]').fill(password);await p.locator('#profile-register button').click();await p.locator('#import-guest').waitFor();}
  async function login(name,pass=password){await p.locator('#account-username').fill(name);await p.locator('#account-password').fill(pass);await p.locator('#account-form button').click();await p.locator('[data-action="account-open"]').waitFor();}
  try{
   p=await makePage();await invitation(batch.codes[0]);await p.locator('[data-action="close-dialog"]').first().click();await newBook('访客手账');await p.evaluate(async image=>{const key='blob:profile-test';pendingAssetBlobs.set(key,await(await fetch('data:image/png;base64,'+image)).blob());state.assets.push({id:'profile-test',name:'测试头像素材',category:'照片',blobKey:key});await saveNow();},avatar.toString('base64'));await openProfile();await register('普通用户甲');await p.screenshot({path:path.join(out,'import-'+width+'.png'),fullPage:true});await Promise.all([p.waitForEvent('load'),p.locator('#import-guest').click()]);await p.waitForFunction(()=>document.querySelector('#app')?.textContent.includes('访客手账'));assert.ok((await p.locator('#app').innerText()).includes('访客手账'));assert.equal(await p.locator('[data-view="admin"]').count(),0);
   const accountA=(await (await p.context().request.get(base+'/api/account')).json()).account;assert.equal(accountA.role,'user');assert.ok(await p.evaluate(async()=>await localRecord(scopedBlobKey('blob:profile-test')) instanceof Blob));await openProfile();await p.locator('#profile-avatar').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:avatar});await p.locator('.account-avatar img').waitFor();await p.screenshot({path:path.join(out,'profile-'+width+'.png'),fullPage:true});
   await p.locator('#profile-details [name="username"]').fill('新的用户名');await p.locator('#profile-details [name="currentPassword"]').fill(password);await p.locator('#profile-details button').click();await p.waitForFunction(()=>document.querySelector('.profile-name')?.textContent.includes('新的用户名'));await p.locator('[data-action="account-switch"]').click();await p.locator('#account-form').waitFor();await login('新的用户名');const stale=await p.context().newPage();await stale.goto(base,{waitUntil:'networkidle'});await stale.locator('[data-action="home-create-sticker"]').click();await stale.locator('[data-action="account-open"]').waitFor();await openProfile();await p.locator('[data-action="account-logout"]').click();await p.locator('[data-action="access-open"]').waitFor();
   await invitation(batch.codes[1]);await register('普通用户乙');await p.locator('[data-action="close-dialog"]').first().click();await stale.waitForFunction(()=>document.querySelector('[data-action="home-create-sticker"]'));await stale.locator('[data-action="home-create-sticker"]').click();await stale.locator('[data-action="account-open"]').waitFor();assert.ok(!(await stale.locator('#app').innerText()).includes('访客手账'));await stale.close();assert.ok(!(await p.locator('#app').innerText()).includes('访客手账'));await openProfile();await p.locator('[data-action="account-switch"]').click();await p.locator('#account-form').waitFor();await login('新的用户名');assert.ok((await p.locator('#app').innerText()).includes('访客手账'));
   await openProfile();await p.locator('[data-action="account-password"]').click();await p.locator('#profile-password [name="oldPassword"]').fill(password);await p.locator('#profile-password [name="newPassword"]').fill('changed-password-123');await p.locator('#profile-password [name="confirm"]').fill('changed-password-123');await p.locator('#profile-password button').click();await p.locator('#account-form').waitFor();await p.locator('#account-username').fill('新的用户名');await p.locator('#account-password').fill(password);await p.locator('#account-form button').click();await p.waitForFunction(()=>document.querySelector('#account-error')?.textContent.includes('不正确'));await login('新的用户名','changed-password-123');
   assert.equal((await (await p.context().request.get(base+'/api/account')).json()).account.id,accountA.id);assert.equal((await p.context().request.get(base+'/api/admin/overview')).status(),403);
   const first=p;p=await makePage();await p.goto(base,{waitUntil:'networkidle'});await p.locator('[data-action="access-open"]').click();await p.locator('[data-value="account"]').click();await login('新的用户名','changed-password-123');await p.locator('#import-guest').waitFor();await p.locator('[data-action="close-dialog"]').first().click();await openProfile();assert.ok((await (await p.context().request.get(base+'/api/account')).json()).account.avatar);assert.equal((await (await p.context().request.get(base+'/api/account')).json()).account.id,accountA.id);assert.ok(!(await p.locator('#app').innerText()).includes('访客手账'));
   p=first;await openProfile();await p.locator('[data-action="account-switch"]').click();await p.locator('#account-form').waitFor();await login('admin',adminPassword);await p.locator('#import-guest').waitFor();await p.locator('[data-action="close-dialog"]').first().click();await p.locator('[data-view="admin"]').waitFor();await openProfile();await p.locator('#profile-details [name="username"]').fill('管理员新名');await p.locator('#profile-details [name="currentPassword"]').fill(adminPassword);await p.locator('#profile-details button').click();await p.waitForFunction(()=>document.querySelector('.profile-name')?.textContent.includes('管理员新名'));await p.locator('[data-action="account-switch"]').click();await p.locator('#account-form').waitFor();await login('管理员新名',adminPassword);await p.locator('[data-view="admin"]').click();await p.locator('.stats').waitFor();assert.deepEqual(errors,[]);
   results.push({width,status:'PASS',checks:['invitation setup and single binding','explicit guest import','avatar and username update','password replacement and relogin','account A/B workspace isolation','same account restores local works','independent browser profile','administrator profile retains role']});
  }catch(e){results.push({width,status:'FAIL',error:e.stack});await p?.screenshot({path:path.join(out,'failure-'+width+'.png'),fullPage:true,timeout:5000}).catch(()=>{});}
  finally{for(const c of contexts)await c.close();await new Promise(r=>server.close(r));server=null;}
 }
})().catch(e=>results.push({fatal:e.stack})).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));if(results.some(r=>r.status==='FAIL'||r.fatal))process.exitCode=1;});
