const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);const report={checks:[],errors:[]};
const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
const clickAt=async(p,sel,x,y)=>{const r=await p.locator(sel).boundingBox();if(p.viewportSize().width===390)await p.touchscreen.tap(r.x+r.width*x,r.y+r.height*y);else await p.mouse.click(r.x+r.width*x,r.y+r.height*y);};
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,390]){
const c=await b.newContext({viewport:{width,height:1000},hasTouch:width===390,isMobile:width===390});await c.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:4176'&&r.request().method()==='GET'?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
await p.goto('http://127.0.0.1:4176');await A(p,'new-book').click();await p.locator('#new-title').fill('跨页与书架验证');await A(p,'create-book').click();await p.locator('#canvas-page').waitFor();const bookId=await p.evaluate(()=>currentBook().id);
await A(p,'editor-layout','spread').click();assert.equal(await p.locator('.edit-leaf').count(),1);await A(p,'add-spread').click();assert.equal(await p.locator('.edit-leaf').count(),2);
const ids=await p.evaluate(()=>spreadPages(pageSpread()).map(p=>p.id));const left=`[data-edit-page="${ids[0]}"]`,right=`[data-edit-page="${ids[1]}"]`;
await clickAt(p,left,.12,.15);await p.locator('.inline-text-input').fill('左页，原位书写');await p.keyboard.press('Escape');await clickAt(p,right,.15,.2);await p.locator('.inline-text-input').fill('右页，继续记录');await p.keyboard.press('Escape');assert.deepEqual(await p.evaluate(()=>spreadPages(pageSpread()).map(p=>p.elements[0].text)),['左页，原位书写','右页，继续记录']);
await p.locator('#selected-text-font').selectOption('hand');assert.equal(await p.evaluate(()=>currentPage().elements[0].font),'hand');
await A(p,'drawer','paper').click();await A(p,'paper-category','0').click();const choices=await p.locator('[data-action="paper"]').evaluateAll(ns=>ns.map(n=>n.dataset.value));await A(p,'paper',choices[1]).click();assert.equal(await p.evaluate(()=>currentPage().paper),choices[1]);
await A(p,'close-drawer').click();await clickAt(p,left,.2,.8);await p.keyboard.press('Escape');await A(p,'drawer','paper').click();await A(p,'paper',choices[2]).click();assert.notEqual(await p.evaluate(()=>currentPage().paper),choices[1]);
await A(p,'paper-scope','spread').click();assert.equal(await p.locator('.edit-leaf>.spread-paper-clip').count(),2);assert.deepEqual(await p.evaluate(()=>spreadPages(pageSpread()).map(p=>p.paperSpread.side)),['left','right']);
// Pick a patterned asset so visual checks can see both halves of the same image.
await A(p,'paper-category','2').click();const pattern=await p.locator('[data-action="paper"]').first().getAttribute('data-value');await A(p,'paper',pattern).click();assert.equal(await p.evaluate(()=>currentPage().paperSpread.paper),pattern);
await A(p,'close-drawer').click();await A(p,'drawer','sticker').click();await p.locator('#new-sticker-scope').selectOption('spread');await p.locator('[data-action="insert-sticker"][data-id="flower"]').click();const sid=await p.evaluate(()=>currentElement().id);assert.equal(await p.evaluate(()=>currentElement().spreadWith),ids[1]);
const sticker=p.locator(`${left} [data-element="${sid}"]`),box=await sticker.boundingBox(),leaf=await p.locator(left).boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+leaf.width*.62,box.y+box.height/2+20,{steps:12});await p.mouse.up();
assert.ok(await p.evaluate(()=>currentElement().x)>80);assert.equal(await p.evaluate(()=>currentBook().pages.flatMap(p=>p.elements).filter(e=>e.id===selectedId).length),1);assert.equal(await p.locator(`.edit-leaf [data-element="${sid}"]`).count(),2);
const halves=await p.locator(`.edit-leaf [data-element="${sid}"]`).evaluateAll(ns=>ns.map(n=>({x:n.getBoundingClientRect().x,w:n.getBoundingClientRect().width})));assert.ok(Math.abs(halves[0].x-halves[1].x)<1);assert.ok(Math.abs(halves[0].w-halves[1].w)<1);
await p.screenshot({path:path.join(out,`spread-${width}.png`)});
// Switching views preserves the original one-object state and per-half paper positioning.
const before=await p.evaluate(()=>JSON.stringify(currentBook().pages));await A(p,'editor-layout','single').click();assert.equal(await p.evaluate(()=>JSON.stringify(currentBook().pages)),before);assert.equal(await p.locator('#canvas-page>.spread-paper-clip').count(),1);
await p.screenshot({path:path.join(out,`single-${width}.png`)});await A(p,'editor-layout','spread').click();
// Select the right-hand projected fragment; it remains the original object.
const projection=await p.locator(`${right} [data-element="${sid}"]`).boundingBox(),rr=await p.locator(right).boundingBox();await p.mouse.click(Math.max(rr.x,projection.x)+8,projection.y+projection.height/2);assert.equal(await p.evaluate(()=>selectedId),sid);
await p.locator('#selected-sticker-scope').selectOption('page');assert.equal(await p.evaluate(id=>elementPage(id).elements.find(e=>e.id===id).spreadWith,sid),undefined);assert.equal(await p.locator(`.edit-leaf [data-element="${sid}"]`).count(),1);await A(p,'undo').click();assert.equal(await p.locator(`.edit-leaf [data-element="${sid}"]`).count(),2);
// Paired duplication remaps references, reorder moves the pair, deletion removes it as a unit.
await A(p,'drawer','pages').click();await A(p,'duplicate-page').click();assert.equal(await p.evaluate(()=>currentBook().pages.length),5);const copied=await p.evaluate(()=>spreadPages(pageSpread()).map(p=>({id:p.id,links:p.elements.filter(e=>e.spreadWith).map(e=>e.spreadWith)})));assert.equal(copied[0].links[0],copied[1].id);
await p.locator('[data-action="move-page-up"][data-value="3"]').click();assert.deepEqual(await p.evaluate(()=>spreadPages(pageSpread()).map(p=>p.id)),copied.map(p=>p.id));assert.deepEqual(await p.evaluate(()=>currentBook().pages.slice(1,3).map(p=>p.id)),copied.map(p=>p.id));
await A(p,'delete-page').click();assert.match(await p.locator('#dialog').innerText(),/这组双页/);await A(p,'confirm-delete-page').click();assert.equal(await p.evaluate(()=>currentBook().pages.length),3);await A(p,'undo').click();assert.equal(await p.evaluate(()=>currentBook().pages.length),5);await A(p,'redo').click();assert.equal(await p.evaluate(()=>currentBook().pages.length),3);
await A(p,'close-drawer').click();await A(p,'page-goto','1').click();await A(p,'mode','read').click();await p.locator('.read-mode').waitFor();await p.screenshot({path:path.join(out,`reader-${width}.png`)});assert.equal(await p.locator('.reader-spread .spread-paper-clip').count(),width===390?1:2);
await A(p,'page-prev').click();await p.waitForFunction(()=>!readerTurn);await A(p,'page-next').click();await p.waitForFunction(()=>!readerTurn);assert.equal(await p.evaluate(id=>currentBook().pages.flatMap(p=>p.elements).filter(e=>e.id===id).length,sid),1);
// Shelf pin persists, sorting honors it, delete is one confirmation and cancellation is harmless.
await A(p,'shelve').click();await p.locator('.books-grid').waitFor();await p.locator(`[data-action="pin-book"][data-id="${bookId}"]`).click();assert.equal(await p.locator('.book-open').first().getAttribute('data-id'),bookId);await p.locator('#book-sort').selectOption('name');assert.equal(await p.locator('.book-open').first().getAttribute('data-id'),bookId);await p.screenshot({path:path.join(out,`shelf-${width}.png`)});
await p.locator(`[data-action="delete-book-confirm"][data-id="${bookId}"]`).click();assert.match(await p.locator('#dialog').innerText(),/跨页与书架验证/);await A(p,'close-dialog').click();assert.ok(await p.evaluate(id=>state.books.some(b=>b.id===id),bookId));
await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');await p.reload();await p.locator('[data-action="nav"][data-view="shelf"]').click();assert.equal(await p.locator(`[data-action="pin-book"][data-id="${bookId}"]`).getAttribute('aria-pressed'),'true');await p.locator(`[data-action="open-book"][data-id="${bookId}"]`).click();await A(p,'mode','edit').click();assert.equal(await p.evaluate(()=>currentBook().editorLayout),'spread');assert.equal(await p.evaluate(id=>currentBook().pages.flatMap(p=>p.elements).filter(e=>e.id===id).length,sid),1);
assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.checks.push({width,status:'PASS',bookId,checks:'left/right inline text; fonts; independent/shared paper; one stored cross sticker with aligned projections; scope toggle; single/dual switching; duplicate/reorder/delete/undo/redo; reader turns; shelf pin/name sort; delete cancel; reload'});console.log(width+' PASS');await c.close();
}}finally{await b.close();}assert.deepEqual(report.errors,[]);})().catch(e=>{report.failure=e.stack;process.exitCode=1;console.error(e);}).finally(()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)));
