const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const out=path.join(__dirname,process.argv[2]);fs.mkdirSync(out);const report={checks:[],errors:[]};const A=(p,a,v)=>p.locator(`[data-action="${a}"]${v===undefined?'':`[data-value="${v}"]`}`).first();
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const c=await browser.newContext({viewport:{width:1440,height:1000}});await c.route('**/*',r=>new URL(r.request().url()).origin==='http://127.0.0.1:4176'&&r.request().method()==='GET'?r.continue():r.abort());const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:4176');await A(p,'new-book').click();await p.locator('#new-title').fill('边界测试');await A(p,'create-book').click();await p.locator('#canvas-page').waitFor();const bookId=await p.evaluate(()=>currentBook().id);
await A(p,'editor-layout','spread').click();await A(p,'add-spread').click();
// A deterministic non-sensitive fixture uses the app's real element/paper creation paths.
const ids=await p.evaluate(()=>{ensurePagePairs();const g=pageSpread();setSpreadPaper('texture-butterfly-botanical');const e=node('sticker',{assetId:'flower',x:84,y:33,w:36,rotation:23,spreadWith:g.right.id});g.left.elements.push(e);dirty();renderEditor();return {left:g.left.id,right:g.right.id,sticker:e.id};});
const thumbnail=await p.locator('.page-thumb').nth(1).evaluate(n=>{const a=n.getBoundingClientRect(),b=n.querySelector('.thumb-content').getBoundingClientRect();return {x:b.x-a.x,y:b.y-a.y};});assert.ok(thumbnail.x<=2&&thumbnail.y<=2);
await p.locator('.edit-leaf img').first().waitFor();await p.waitForFunction(()=>[...document.querySelectorAll('.edit-leaf img')].every(i=>i.complete));
const aligned=await p.locator(`.edit-leaf [data-element="${ids.sticker}"]`).evaluateAll(ns=>ns.map(n=>({x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));for(const k of ['x','y','w','h'])assert.ok(Math.abs(aligned[0][k]-aligned[1][k])<.05);
await p.screenshot({path:path.join(out,'rotated-spread.png')});
// Drag the visible right half of the same object; ownership and placement survive save/rebase.
const rr=await p.locator(`[data-edit-page="${ids.right}"]`).boundingBox(),box=aligned[1];await p.mouse.move(rr.x+20,box.y+box.h*.5);await p.mouse.down();await p.mouse.move(rr.x+60,box.y+box.h*.5+10,{steps:8});await p.mouse.up();assert.equal(await p.evaluate(()=>selectedId),ids.sticker);assert.equal(await p.evaluate(id=>elementPage(id).id,ids.sticker),ids.left);
await p.locator('#selected-sticker-scope').selectOption('page');const bounded=await p.locator(`[data-edit-page="${ids.left}"] [data-element="${ids.sticker}"]`).boundingBox(),lr=await p.locator(`[data-edit-page="${ids.left}"]`).boundingBox();assert.ok(bounded.x>=lr.x-1&&bounded.x+bounded.width<=lr.x+lr.width+1);await A(p,'undo').click();
// Changing paper mode restores each page's previously chosen paper.
await A(p,'drawer','paper').click();await A(p,'paper-scope','page').click();assert.ok(await p.evaluate(()=>spreadPages(pageSpread()).every(p=>!p.paperSpread)));await A(p,'undo').click();assert.equal(await p.locator('.edit-leaf>.spread-paper-clip').count(),2);await A(p,'close-drawer').click();
// Editing and reading turns use clipped paper faces, including the intermediate animation.
await A(p,'page-prev').click();await p.waitForSelector('.side-turn-layer');await p.waitForTimeout(350);await p.screenshot({path:path.join(out,'editing-turn.png')});await p.waitForFunction(()=>!editingPageTurn);assert.equal(await p.evaluate(()=>currentBook().page),0);await A(p,'page-next').click();await p.waitForFunction(()=>!editingPageTurn);assert.equal(await p.evaluate(()=>currentPage().id),ids.left);
await A(p,'mode','read').click();await A(p,'page-prev').click();await p.waitForSelector('.side-turn-layer');await p.waitForTimeout(350);await p.screenshot({path:path.join(out,'reading-turn.png')});await p.waitForFunction(()=>!readerTurn);await A(p,'page-next').click();await p.waitForFunction(()=>!readerTurn);
await p.setViewportSize({width:390,height:1000});await p.waitForSelector('.reader-spread.single');assert.equal(await p.locator(`.reader-spread [data-element="${ids.sticker}"]`).count(),1);await p.screenshot({path:path.join(out,'single-left.png')});await A(p,'page-next').click();await p.waitForFunction(()=>!readerTurn);assert.equal(await p.evaluate(()=>currentPage().id),ids.right);assert.equal(await p.locator(`.reader-spread [data-element="${ids.sticker}"]`).count(),1);await p.screenshot({path:path.join(out,'single-right.png')});
// Insertion never changes old IDs or joins the existing cross-page object to a new leaf.
await A(p,'mode','edit').click();await A(p,'page-add').click();assert.deepEqual(await p.evaluate(id=>spreadPages(pageSpread(currentBook().pages.find(p=>p.id===id))).map(p=>p.id),ids.left),[ids.left,ids.right]);await A(p,'undo').click();
await A(p,'shelve').click();await p.locator('.books-grid').waitFor();await p.locator(`[data-action="pin-book"][data-id="${bookId}"]`).click();await p.locator(`[data-action="pin-book"][data-id="${bookId}"]`).click();assert.equal(await p.locator(`[data-action="pin-book"][data-id="${bookId}"]`).getAttribute('aria-pressed'),'false');await p.setViewportSize({width:1440,height:1000});await A(p,'book-view','list').click();await p.setViewportSize({width:390,height:1000});await p.screenshot({path:path.join(out,'shelf-list-mobile.png')});
await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='已保存到本机');const assets=await p.evaluate(()=>JSON.stringify(state.assets));await p.locator(`[data-action="delete-book-confirm"][data-id="${bookId}"]`).click();assert.equal(await p.locator('#dialog [data-action="delete-book"]').count(),1);await p.screenshot({path:path.join(out,'delete-confirm-mobile.png')});
await p.evaluate(()=>{window.originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(){throw new DOMException('test quota','QuotaExceededError');};});await p.locator('#dialog [data-action="delete-book"]').click();await p.waitForFunction(()=>document.querySelector('.local-status')?.textContent==='保存失败，请重试');assert.ok(await p.evaluate(id=>state.books.some(b=>b.id===id),bookId));assert.equal(await p.locator('#dialog').evaluate(n=>n.open),true);assert.match(await p.locator('#toast').innerText(),/手帐已保留/);await p.evaluate(()=>IDBObjectStore.prototype.put=window.originalPut);
await p.locator('#dialog [data-action="delete-book"]').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);assert.ok(await p.evaluate(id=>!state.books.some(b=>b.id===id),bookId));assert.equal(await p.evaluate(()=>JSON.stringify(state.assets)),assets);await p.reload();await p.locator('[data-action="nav"][data-view="shelf"]').click();assert.equal(await p.locator(`[data-action="open-book"][data-id="${bookId}"]`).count(),0);
report.checks.push({status:'PASS',checks:'rotated projection alignment; drag right fragment; scope bounds; paper-mode undo; live editing/reader turns; mobile left/right clips; insertion fixed IDs; unpin/list; delete cancel/failure/retry/persistence/assets preserved'});console.log('edge cases PASS');await c.close();}finally{await browser.close();}assert.deepEqual(report.errors,[]);})().catch(e=>{report.failure=e.stack;process.exitCode=1;console.error(e);}).finally(()=>fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)));
