const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p,service,release;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-copy-ui-')),batch=generateInvites(3),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'test',secretKey:'test',cutout:false,naming:false},path.join(dir,'receipt'));
 for(const [i,name] of ['copy-user-a','copy-user-b'].entries()){const grant=await access.verify(batch.codes[i],name,'local');await admin.register(grant.token,{username:name,password:'test-password-123'});}
 const inputs=[];let hold=false,fail=false;
 const {app,copy}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async input=>{inputs.push(input);if(hold)await new Promise(r=>release=r);if(fail)throw Error('fixture failure');return {text:'午后的光落在书页上，慢慢读几页，让今天的脚步也跟着放缓。',provider:'test',model:'fixture',usage:{inputTokens:120,outputTokens:45}};}}});service=copy;
 server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1050}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 async function login(name){await context.request.get(base+'/api/access/session');assert.equal((await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:name,password:'test-password-123'}})).status(),200);}
 async function ready(){await p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务',{},{timeout:20000});}
 async function close(){await p.locator('#dialog [data-action="close-dialog"]').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);}
 async function preview(){await p.locator('#ai-copy-preview').waitFor({state:'visible'});await p.waitForFunction(()=>!aiCopyPanel.busy&&!aiCopyPanel.poll);}
 async function gen(topic='周末读书'){await p.locator('#ai-copy-form [name="topic"]').fill(topic);await p.locator('#ai-copy-generate').click();await preview();}
 await login('copy-user-a');p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>state&&currentIdentity?.username==='copy-user-a');await ready();
 assert.ok((await p.locator('body').innerText()).includes('开始创作'));assert.equal(await p.locator('.vite-error-overlay,[data-nextjs-dialog]').count(),0);checks.push('Home loads without blank screen or framework errors');
 await p.evaluate(async()=>{const book=seed().books[0];book.id='copy-book';book.title='文案验证';book.editorLayout='spread';book.page=0;book.pages=[{id:'left',paper:'plain',spreadKey:'pair',spreadSide:'left',elements:[{id:'original',type:'text',text:'今天在家读了几页书。',font:'fangsong',direction:'vertical',size:24,color:'#556644',x:12,y:5,w:40,h:65,rotation:2},{id:'sticker',type:'sticker',assetId:builtin[3].id,x:60,y:30,w:35,rotation:0}]},{id:'right',paper:'plain',spreadKey:'pair',spreadSide:'right',elements:[{id:'secret',type:'text',text:'OTHER_PAGE_PRIVATE',font:'serif',size:23,x:10,y:10,w:30,rotation:0}]}];state.books=[book];dirty();await saveNow();openBook('copy-book',true);selectedId='original';renderEditor();});await ready();
 await p.locator('[data-action="ai-copy-open"]').click();await p.locator('#ai-copy-generate:not([disabled])').waitFor();assert.equal(inputs.length,0);assert.equal(await p.locator('#ai-copy-form [name="draft"]').inputValue(),'今天在家读了几页书。');
 await p.screenshot({path:path.join(__dirname,'desktop-form.png')});await gen();assert.equal(inputs.length,1);assert.equal(inputs[0].mode,'polish');assert.ok(inputs[0].thumbnail.startsWith('data:image/jpeg;base64,'));assert.ok(!JSON.stringify(inputs[0]).includes('OTHER_PAGE_PRIVATE'));assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'今天在家读了几页书。');checks.push('Explicit request uses selected page thumbnail and draft only; preview does not alter page');
 await p.locator('#ai-copy-result').fill('我改过的手账文字。');await p.screenshot({path:path.join(__dirname,'desktop-preview.png')});await p.locator('#ai-copy-apply').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);await ready();
 const e=await p.evaluate(()=>currentPage().elements.find(e=>e.id==='original'));assert.equal(e.text,'我改过的手账文字。');assert.equal(e.font,'fangsong');assert.equal(e.direction,'vertical');assert.equal(e.rotation,2);assert.equal(e.aiSource.provider,'test');
 await p.locator('[data-action="undo"]').first().click();assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'今天在家读了几页书。');await p.locator('[data-action="redo"]').first().click();assert.equal(await p.evaluate(()=>currentPage().elements[0].aiSource.kind),'copy');checks.push('Apply preserves font, direction, position and rotation; undo/redo restores AI metadata');
 await p.locator('#canvas-page [data-element="original"]').dblclick();await p.locator('.inline-text-input').fill('放入之后继续原位写字');await ready();assert.ok(await p.locator('.inline-text-input').evaluate(e=>document.activeElement===e));await p.locator('.inline-text-input').press('Escape');await p.evaluate(()=>saveNow());await ready();
 const remote=await(await context.request.get(base+'/api/works/workspace')).json();assert.equal(remote.content.books[0].pages[0].elements[0].text,'放入之后继续原位写字');assert.equal(remote.content.books[0].pages[0].elements[0].aiSource.kind,'copy');await p.reload();await ready();await p.evaluate(()=>openBook('copy-book',true));assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'放入之后继续原位写字');checks.push('Inline editing remains focused and automatically syncs structured text with provenance; reload restores it');
 // Open through the ordinary text drawer, generate a new text node, close and recover same preview without another call.
 await p.evaluate(()=>{selectedId=null;drawer='text';renderEditor();});await p.locator('[data-action="ai-copy-open"]').click();await gen('安静的午后');const count=inputs.length;await close();await p.locator('[data-action="ai-copy-open"]').click();await preview();assert.equal(inputs.length,count);await p.locator('#ai-copy-again').click();await preview();assert.equal(inputs.length,count+1);await p.locator('#ai-copy-apply').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);assert.equal(await p.evaluate(()=>currentPage().elements.filter(e=>e.type==='text').length),2);checks.push('Text drawer can create AI text; reopening recovers preview; regenerate alone makes a new charge');
 // Lost submission acknowledgement reuses persisted operation, never repeats supplier call.
 await p.evaluate(()=>{selectedId=null;drawer='text';renderEditor();});await p.locator('[data-action="ai-copy-open"]').click();let lost=false;await context.route('**/api/ai/copy',async r=>{if(r.request().method()==='POST'&&!lost){lost=true;await r.fetch();await r.abort();}else await r.continue();});await p.locator('[name="topic"]').fill('雨天');await p.locator('#ai-copy-generate').click();await p.locator('#ai-copy-recover').waitFor({state:'visible'});await context.unroute('**/api/ai/copy');const before=inputs.length;await p.locator('#ai-copy-recover').click();await preview();assert.equal(inputs.length,before);checks.push('Lost acknowledgement queries original task without another supplier request');await close();
 // Stale page, then stale account, cannot receive late generated content.
 await p.locator('[data-action="ai-copy-open"]').click();await preview();await p.evaluate(()=>{currentPage().elements[0].text='另一处已经修改';});await p.locator('#ai-copy-apply').click();await p.waitForFunction(()=>document.querySelector('#ai-copy-error').textContent.includes('变化'));assert.equal(await p.evaluate(()=>currentPage().elements[0].text),'另一处已经修改');await close();checks.push('Applying an outdated preview does not overwrite a changed page');
 await p.evaluate(()=>{sessionStorage.clear();selectedId=null;drawer='text';renderEditor();});await p.locator('[data-action="ai-copy-open"]').click();hold=true;await p.locator('[name="topic"]').fill('迟到结果');await p.locator('#ai-copy-generate').click();while(!release)await new Promise(r=>setTimeout(r,20));await login('copy-user-b');release();hold=false;await service.idle();await p.waitForFunction(()=>document.querySelector('#ai-copy-error').textContent.includes('身份'));assert.equal(await p.evaluate(()=>currentPage().elements.some(e=>e.text==='迟到结果')),false);await p.reload();await ready();assert.equal(await p.evaluate(()=>state.books.length),0);checks.push('Changed account is rejected by server identity header; delayed result never enters another account');
 // Mobile form and inline insertion remain usable.
 await login('copy-user-a');await p.setViewportSize({width:390,height:844});await p.reload();await ready();await p.evaluate(()=>{openBook('copy-book',true);selectedId=null;drawer='text';renderEditor();sessionStorage.clear();});await p.locator('[data-action="ai-copy-open"]').click();await p.locator('#ai-copy-generate:not([disabled])').waitFor();await p.screenshot({path:path.join(__dirname,'mobile-form.png'),fullPage:true});assert.ok(await p.evaluate(()=>document.querySelector('#dialog').scrollWidth<=document.querySelector('#dialog').clientWidth+1));fail=true;await p.locator('[name="topic"]').fill('失败验证');await p.locator('#ai-copy-generate').click();await p.waitForFunction(()=>document.querySelector('#ai-copy-error').textContent.includes('不扣'));assert.equal(await p.locator('#ai-copy-preview').isVisible(),false);fail=false;checks.push('390px form has no horizontal overflow; failed generation reports error without preview or user charge');await close();
 // A sticker owned by the opposite leaf is part of this page's generation context.
 await p.evaluate(()=>{sessionStorage.clear();currentBook().pages[1].elements.push({id:'cross',type:'sticker',assetId:builtin[2].id,x:-20,y:30,w:40,rotation:0,spreadWith:'left'});selectedId=null;drawer='text';renderEditor();});await p.locator('[data-action="ai-copy-open"]').click();await gen('跨页素材');const matched=await p.evaluate(()=>aiCopySnapshot().stickers.some(r=>r.element.id==='cross'));assert.equal(matched,true);await p.evaluate(()=>{currentBook().pages[1].elements.find(e=>e.id==='cross').rotation=15;});await p.locator('#ai-copy-apply').click();await p.waitForFunction(()=>document.querySelector('#ai-copy-error').textContent.includes('变化'));checks.push('Opposite-leaf spanning stickers participate in context revision; late cross-page changes block apply');await close();

 // Admin copy card uses a separate safe configuration form; no auth-test generation on save.
 const password=fs.readFileSync(path.join(dir,'receipt'),'utf8').match(/密码：(.+)/)[1];await context.request.post(base+'/api/admin/login',{headers:{origin:base},data:{username:'admin',password}});await p.goto(base+'/admin');await p.locator('[data-view="apis"]').click();await p.locator('[data-kind="copy"]').click();assert.equal(await p.locator('[name="model"]').count(),1);assert.equal(await p.locator('#api-test').count(),0);const callsBefore=inputs.length;await p.locator('#manage-form button[type="submit"]').click();await p.waitForFunction(()=>!document.querySelector('#admin-dialog').open);assert.equal(inputs.length,callsBefore);await p.screenshot({path:path.join(__dirname,'admin-copy.png'),fullPage:true});checks.push('Admin has independent disabled copy configuration and usage; saving makes no model call');
 assert.deepEqual(errors,[]);checks.push('No uncaught JavaScript errors across desktop, mobile and admin flows');console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);console.error(await p?.evaluate(()=>({sync:typeof workSync!=='undefined'&&workSync?.error,copy:document.querySelector('#ai-copy-error')?.textContent})).catch(()=>null));checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png'),fullPage:true,timeout:3000}).catch(()=>{});process.exitCode=1;}).finally(async()=>{release?.();await browser?.close();await service?.idle();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
