const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();



 const sharp=require(path.join(root,'node_modules/sharp'));
 const imageBodies=await p.evaluate(()=>Object.fromEntries(['flower','tape'].map(id=>[id,decodeURIComponent(builtin.find(a=>a.id===id).src.split(',')[1])])));
 await context.route('**/assets/fixture-*',async route=>{await new Promise(r=>setTimeout(r,route.request().url().includes('?warm')?900:400));const name=new URL(route.request().url()).pathname.split('/').pop();if(name.startsWith('fixture-photo'))await route.fulfill({path:path.join(root,'shiye-editorial-prototype/assets/lake.jpg')});else await route.fulfill({contentType:'image/svg+xml',body:imageBodies[name.includes('flower')?'flower':'tape']});});
 await p.evaluate(async()=>{const lake=samplePage('lake');for(const id of ['flower','tape'])state.assets.push({...clone(builtin.find(a=>a.id===id)),src:`assets/fixture-${id}.svg`});lake.elements.find(e=>e.type==='photo').src='assets/fixture-photo.jpg';currentBook().pages[1].elements=lake.elements;currentBook().pages[2].elements=clone(lake.elements);editing=false;renderEditor();cancelPageWarm();ShiyePageTextures.clear();window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,0);});
 await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>!!testTurn.simple),false);
 const texture=await p.evaluate(()=>testTurn.strips[0].querySelector('.side-back').style.backgroundImage.match(/url\(["']?(.*?)["']?\)/)[1]);const png=Buffer.from(texture.split(',')[1],'base64');fs.writeFileSync(path.join(__dirname,'complete-texture.png'),png);
 for(const value of [.25,.65,.9,1]){await p.evaluate(value=>drawSideTurn(testTurn,value),value);await p.screenshot({path:path.join(__dirname,`turn-${value}.png`)});}
 const landed=await p.locator('.reader-spread').screenshot();await p.evaluate(()=>{currentBook().page=2;renderEditor();});await p.evaluate(async()=>{await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});const final=await p.locator('.reader-spread').screenshot();fs.writeFileSync(path.join(__dirname,'landed.png'),landed);fs.writeFileSync(path.join(__dirname,'final.png'),final);
 const reference=await p.locator('.reader-spread>.reader-leaf').first().screenshot();fs.writeFileSync(path.join(__dirname,'reference.png'),reference);
 const meta=await sharp(reference).metadata();
 async function regionDiff(a,b,box){const resized=await sharp(b).resize(meta.width,meta.height).toBuffer(),aa=await sharp(a).extract(box).removeAlpha().raw().toBuffer(),bb=await sharp(resized).extract(box).removeAlpha().raw().toBuffer();let total=0;for(let i=0;i<aa.length;i++)total+=Math.abs(aa[i]-bb[i]);return total/aa.length;}
 const regions={photo:[.15,.37,.65,.22],tape:[.33,.28,.24,.055],flower:[.65,.6,.23,.18]};
 for(const [name,[x,y,w,h]] of Object.entries(regions)){const diff=await regionDiff(reference,png,{left:Math.round(meta.width*x),top:Math.round(meta.height*y),width:Math.round(meta.width*w),height:Math.round(meta.height*h)});assert.ok(diff<8,`${name} missing/moved: ${diff}`);checks.push({check:`Delayed ${name} is present in the turning back face`,meanChannelDifference:diff});}
 const a=await sharp(landed).removeAlpha().raw().toBuffer(),b=await sharp(final).removeAlpha().raw().toBuffer();assert.equal(a.length,b.length);let sum=0;for(let i=0;i<a.length;i++)sum+=Math.abs(a[i]-b[i]);const landingDiff=sum/a.length;checks.push({check:'Last animation frame vs settled page',meanChannelDifference:landingDiff});assert.ok(landingDiff<10,'Contents jump on landing: '+landingDiff);
 // Cold idle preparation must wait for previously unseen photo/sticker dimensions too.
 await p.evaluate(()=>{currentBook().page=0;for(const page of currentBook().pages)for(const e of page.elements)if(e.type==='photo')e.src+='?warm';for(const a of state.assets)if(['flower','tape'].includes(a.id))a.src+='?warm';renderEditor();ShiyePageTextures.clear();schedulePageWarm();});
 await p.waitForFunction(()=>!pageWarmRunning&&adjacentTurnFaces().every(j=>ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey)));
 await p.evaluate(()=>{window.cacheHits=[];window.originalGet=ShiyePageTextures.get;ShiyePageTextures.get=function(src,w,h,owner){cacheHits.push(this.has(src.innerHTML,src.className,w,h,owner));return originalGet.call(this,src,w,h,owner);};window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.7);});await p.waitForFunction(()=>testTurn.ready);assert.deepEqual(await p.evaluate(()=>cacheHits),[true,true]);assert.equal(await p.evaluate(()=>!!testTurn.simple),false);const warmTexture=await p.evaluate(()=>testTurn.strips[0].querySelector('.side-back').style.backgroundImage.match(/url\(["']?(.*?)["']?\)/)[1]);assert.deepEqual(Buffer.from(warmTexture.split(',')[1],'base64'),png);checks.push('Idle preparation waits for delayed images; both cached faces are reused and back-face pixels match the complete cold texture');
 await p.evaluate(()=>{ShiyePageTextures.get=originalGet;cancelReaderTurn();renderEditor();cancelPageWarm();ShiyePageTextures.clear();});
 // Unfinished image preparation is cancelled safely when the book is removed.
 await p.evaluate(()=>{currentBook().pages[2].elements.find(e=>e.type==='photo').src='assets/fixture-photo-cancel.jpg';window.testTurn=prepareReaderTurn(1);drawSideTurn(testTurn,.4);cancelReaderTurn();currentView='shelf';render();});await p.waitForTimeout(1400);assert.equal(await p.locator('.side-strip').count(),0);assert.equal(await p.locator('.page-texture-prewarm').count(),0);checks.push('Leaving while photos decode does not resurrect a removed turn');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
