const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {chromium}=require('/Users/song/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),checks=[],errors=[];let browser,server,p;
(async()=>{
 const {Admin}=await import(path.join(root,'dist/server/admin.js')),{InviteAccess,generateInvites}=await import(path.join(root,'dist/server/access.js')),{createApp}=await import(path.join(root,'dist/server/app.js'));
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shiye-page-turn-')),batch=generateInvites(1),file=path.join(dir,'invites.json');fs.writeFileSync(file,JSON.stringify(batch.config));const access=new InviteAccess(file),admin=new Admin(path.join(dir,'admin.json'),access);await admin.init({apiKey:'fixture',secretKey:'fixture',cutout:false,naming:false},path.join(dir,'receipt'));
 const grant=await access.verify(batch.codes[0],'fixture','local');await admin.register(grant.token,{username:'style-user',password:'fixture-password-123'});
 const {app}=await createApp({runtime:path.join(dir,'runtime'),staticRoot:path.join(root,'shiye-editorial-prototype'),admin,access,copyProvider:{generate:async()=>({text:'把今天慢慢收好。',provider:'test',model:'fixture'})}});server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await context.request.get(base+'/api/access/session');await context.request.post(base+'/api/access/login',{headers:{origin:base},data:{username:'style-user',password:'fixture-password-123'}});
 p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const ready=()=>p.waitForFunction(()=>workSync&&!workSync.running&&workSync.label==='已同步到当前服务');await ready();
 await p.evaluate(async()=>{const b=seed().books[0];b.id='menu-book';b.page=0;b.editorLayout='single';state.assets=[clone(builtin.find(a=>a.id==='orange'))];b.pages=[{id:'p0',paper:'plain',spreadKey:'pair-a',spreadSide:'left',elements:[{id:'text',type:'text',text:'保留文字样式',font:'fangsong',size:30.5,bold:true,color:'#315b90',direction:'horizontal',x:12,y:12,w:45,rotation:2},{id:'sticker',type:'sticker',assetId:'orange',x:65,y:65,w:20,rotation:5}]},{id:'p1',paper:'plain',spreadKey:'pair-a',spreadSide:'right',elements:[]},{id:'p2',paper:'plain',spreadKey:'pair-b',spreadSide:'left',elements:[]},{id:'p3',paper:'plain',spreadKey:'pair-b',spreadSide:'right',elements:[]}];state.books=[b];dirty();await saveNow();openBook(b.id,true);});await ready();



 await p.emulateMedia({reducedMotion:'no-preference'});
 await p.evaluate(()=>{
  currentBook().pages.forEach((page,index)=>{page.elements=Array.from({length:24},(_,i)=>({id:`label-${index}-${i}`,type:'text',text:`山风 ${index} / ${i}`,font:'serif',size:16,color:'#315b90',x:5+(i%4)*23,y:5+Math.floor(i/4)*14,w:22,rotation:0}));});
  editing=false;renderEditor();window.getCalls=[];window.savedGet=ShiyePageTextures.get;
  ShiyePageTextures.get=function(source,w,h,owner){const start=performance.now(),hit=this.has(source.innerHTML,source.className,w,h,owner),warm=!!source.closest('.page-texture-prewarm');const call={hit,warm,w,h};getCalls.push(call);return savedGet.call(this,source,w,h,owner).then(result=>{call.ms=performance.now()-start;return result;});};
 });
 const warmed=async()=>{await p.waitForFunction(()=>{const jobs=adjacentTurnFaces();return jobs.length>0&&!pageWarmRunning&&jobs.every(j=>ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey));});};
 const measure=()=>p.evaluate(async()=>{const start=performance.now();const turn=prepareReaderTurn(1);drawSideTurn(turn,0);while(!turn.ready)await new Promise(requestAnimationFrame);window.measuredTexture=turn.strips?.[0].querySelector('.side-front').style.backgroundImage;return {ms:performance.now()-start,textureMs:getCalls.filter(c=>!c.warm).slice(-2).map(c=>c.ms),simple:!!turn.simple};});
 await p.evaluate(()=>{cancelPageWarm();ShiyePageTextures.clear();});
 const cold=await measure();assert.equal(cold.simple,false);await p.evaluate(()=>window.coldTexture=measuredTexture);
 await p.evaluate(()=>{cancelReaderTurn();renderEditor();ShiyePageTextures.clear();schedulePageWarm();});
 const rect=await p.locator('.reader-spread').boundingBox();await warmed();
 assert.deepEqual(await p.locator('.reader-spread').boundingBox(),rect);assert.equal(await p.locator('.reader-spread .reader-leaf').count(),2);assert.equal(await p.locator('.reader-turn-layer').count(),0);assert.equal(await p.locator('.page-texture-prewarm').count(),0);
 await p.evaluate(()=>getCalls=[]);const warm=await measure();
 assert.equal(warm.simple,false);assert.equal(await p.evaluate(()=>coldTexture===measuredTexture),true,'Warm and cold textures must have identical pixels');assert.ok(await p.evaluate(()=>getCalls.filter(c=>!c.warm).every(c=>c.hit)));
 checks.push({check:'Desktop reader prewarms adjacent faces without changing layout or live leaves; actual flip hits both faces',cold,warm});
 await p.evaluate(()=>{cancelReaderTurn();renderEditor();currentBook().pages[1].elements[0].text='新的内容';dirty();});
 assert.equal(await p.evaluate(()=>adjacentTurnFaces().every(j=>ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey))),false);await warmed();checks.push('Changed text invalidates its face and idle preparation refreshes it');
 await p.evaluate(()=>{cancelPageWarm();ShiyePageTextures.clear();document.dispatchEvent(new PointerEvent('pointerdown',{pointerId:17,bubbles:true}));schedulePageWarm();});await p.waitForTimeout(850);
 assert.equal(await p.evaluate(()=>adjacentTurnFaces().some(j=>ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey))),false);
 await p.evaluate(()=>document.dispatchEvent(new PointerEvent('pointerup',{pointerId:17,bubbles:true})));await warmed();checks.push('Pointer hold suspends new preparation; release resumes after idle');
 await p.evaluate(async()=>{editing=true;currentBook().page=0;currentBook().editorLayout='single';dirty();await saveNow();renderEditor();ShiyePageTextures.clear();schedulePageWarm();});await warmed();await p.evaluate(()=>getCalls=[]);
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===1&&!editingPageTurn);
 assert.ok(await p.evaluate(()=>getCalls.filter(c=>!c.warm).length===2&&getCalls.filter(c=>!c.warm).every(c=>c.hit)));checks.push('Single-page editing consumes the warmed faces and completes normally');
 await p.evaluate(()=>{startInlineText(null,20,20);ShiyePageTextures.clear();schedulePageWarm();});await p.waitForTimeout(850);assert.equal(await p.evaluate(()=>adjacentTurnFaces().some(j=>ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey))),false);
 await p.locator('.inline-text-input').fill('正在输入');await p.locator('.inline-text-input').press('Escape');await p.evaluate(()=>schedulePageWarm());await warmed();checks.push('Inline typing pauses preparation and retains direct on-page editing');
 await p.locator('[data-action="editor-layout"][data-value="spread"]').click();await warmed();await p.evaluate(()=>getCalls=[]);
 await p.locator('[data-action="page-next"]').click();await p.waitForFunction(()=>currentBook().page===2&&!editingPageTurn);assert.ok(await p.evaluate(()=>getCalls.filter(c=>!c.warm).length===2&&getCalls.filter(c=>!c.warm).every(c=>c.hit)));checks.push('Spread editing hits both warmed faces with its own dimensions');
 await p.evaluate(()=>{editing=false;currentBook().page=0;renderEditor();});await p.setViewportSize({width:390,height:844});await warmed();await p.evaluate(()=>getCalls=[]);await measure();assert.ok(await p.evaluate(()=>getCalls.filter(c=>!c.warm).every(c=>c.hit)));checks.push('Mobile viewport uses matching single-page cache dimensions');
 await p.evaluate(()=>{cancelReaderTurn();currentView='home';render();homeDemo.open=true;homeDemo.busy=false;document.querySelector('.home-stage').classList.add('is-open');document.querySelector('#home-book').classList.add('is-open');showHomeSpread();});await warmed();await p.evaluate(()=>{getCalls=[];window.testTurn=prepareHomeTurn(1);drawSideTurn(testTurn,.35);});await p.waitForFunction(()=>testTurn.ready);assert.equal(await p.evaluate(()=>!!testTurn.simple),false);assert.ok(await p.evaluate(()=>getCalls.filter(c=>!c.warm).every(c=>c.hit)));checks.push('Homepage prewarm keeps container-relative typography and cache hits');await p.screenshot({path:path.join(__dirname,'prewarm-home.png')});
 await p.evaluate(()=>{stopHomeDemo();currentView='shelf';render();ShiyePageTextures.clear();});await p.waitForTimeout(850);assert.equal(await p.locator('.page-texture-prewarm').count(),0);assert.equal(await p.evaluate(()=>pageWarmRunning),false);checks.push('Leaving the book cancels queued work and removes hidden staging');
 await p.evaluate(()=>{currentView='editor';editing=false;renderEditor();getCalls=[];ShiyePageTextures.clear();schedulePageWarm();applyIdentity(null);});await p.waitForTimeout(850);assert.equal(await p.evaluate(()=>getCalls.length),0);checks.push('Identity changes clear cache and cancel pending preparation');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',checks}));
})().catch(async e=>{console.error(e.stack);console.error(await p?.evaluate(()=>({currentView,editing,readerCover,inline:!!inlineText,pointers:[...pageWarmPointers],running:pageWarmRunning,version:pageWarmVersion,allowed:canWarmPages(),jobs:adjacentTurnFaces().map(j=>({w:j.w,h:j.h,hit:ShiyePageTextures.has(j.html,j.side,j.w,j.h,workspaceKey)})),calls:getCalls,fonts:document.fonts.status,hidden:document.hidden,dialog:$('#dialog').open,body:document.body.className})).catch(()=>null));checks.push({failure:e.stack});await p?.screenshot({path:path.join(__dirname,'prewarm-failure.png')}).catch(()=>{});process.exitCode=1;}).finally(async()=>{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.writeFileSync(path.join(__dirname,'prewarm-results.json'),JSON.stringify({status:process.exitCode?'FAIL':'PASS',checks,errors},null,2));});
